NextPageTransitionBehaviour
Image NextPageTransitionBehaviour.m_image
RectTransform NextPageTransitionBehaviour.m_rect
Material NextPageTransitionBehaviour.m_material
Referenced by NextPage.
string NextPageTransitionBehaviour.m_propertyName
Referenced by NextPage.
CaptureScreenToImage NextPageTransitionBehaviour.m_capture
Referenced by ScreenShot.
readonly float NextPageTransitionBehaviour.m_startUpValue
Referenced by NextPage, OnEvent.
readonly float NextPageTransitionBehaviour.m_finalValue
Referenced by NextPage.
GameObject NextPageTransitionBehaviour.m_endHideObject
Referenced by NextPageTransitionDirector.NextPageTransitionDirectorHandle.End.
float NextPageTransitionBehaviour.m_slideMoveTime
Referenced by NextPage, NextPageTransitionDirector.NextPageTransitionDirectorHandle.Start.
async void NextPageTransitionBehaviour.OnEvent()
References m_startUpValue, NextPage, ScreenShot.
UniTask NextPageTransitionBehaviour.LoadTexture()
References SceneCaptureManager.m_capturedImage, SceneCaptureManager.m_sizeDelta.
Referenced by NextPage.
async UniTask NextPageTransitionBehaviour.NextPage()
References m_slideMoveTime, NextPage.
Referenced by NextPage, TestNotingEntryPoint.OnEnter, OnEvent, NextPageTransitionDirector.NextPageTransitionDirectorHandle.Start.
async UniTask NextPageTransitionBehaviour.NextPage(float slideTime)
References LoadTexture, m_finalValue, m_material, m_propertyName, m_startUpValue.
UniTask NextPageTransitionBehaviour.ScreenShot()
References CaptureScreenToImage.Capture, m_capture.
Referenced by NextPageTransitionDirector.NextPageTransitionDirectorHandle.End, OnEvent.