PathFinding
NavMeshAgent PathFinding.m_agent
Referenced by Awake, SetDestination, UpdateAsync.
Transform PathFinding.m_myTransform
Referenced by Awake, UpdateAsync.
Vector3 PathFinding.DesiredVelocity
float PathFinding.RemainingDistance
Vector3 PathFinding.Destination
bool PathFinding.IsArrived
void PathFinding.Stop()
Referenced by PlayerSkillsParameters.PathfindingStop.
void PathFinding.SetDestination(Vector3 pos)
References m_agent.
Referenced by UpdateAsync.
void PathFinding.Awake()
References m_agent, m_myTransform.
void PathFinding.Start()
References UpdateAsync.
void PathFinding.Update()
async void PathFinding.UpdateAsync()
References m_agent, m_myTransform, SetDestination.
Referenced by Start.