CreateNonProXiWindow
GameObject CreateNonProXiWindow.m_windowController
Referenced by CreateWindow.
GameObject CreateNonProXiWindow.m_createWindow
Referenced by CreateWindow.
async UniTask CreateNonProXiWindow.CreateWindow()
ウィンドウを作成
References HideOtherUI, SoundManager.Instance, m_createWindow, m_windowController, ShowOtherUI, SoundManager.StartPlayback.
async UniTask CreateNonProXiWindow.HideOtherUI()
References ListCanvasGroup.
Referenced by CreateWindow.
async UniTask CreateNonProXiWindow.ShowOtherUI()
References ListCanvasGroup.
Referenced by CreateWindow.
List< CanvasGroup > CreateNonProXiWindow.ListCanvasGroup()
Referenced by HideOtherUI, ShowOtherUI.