CharacterCore
InputTypes
MoveTypes
CharacterGroupNumber CharacterCore.m_groupNo
bool CharacterCore.m_doFriendlyFire
MyCharacterController CharacterCore.m_charaCtrl
IInputProvider CharacterCore.m_inputProvider
InputTypes CharacterCore.m_inputType
MoveTypes CharacterCore.m_moveType
Renderer CharacterCore.m_renderer
Material CharacterCore.m_material
DG.Tweening.Sequence CharacterCore.m_seq
float CharacterCore.m_walkSpeed
float CharacterCore.m_dushSpeed
VisualEffect CharacterCore.m_dashEffect
float CharacterCore.m_speedChangeRate
bool CharacterCore.m_isRun
bool CharacterCore.m_isPush
bool CharacterCore.m_isNoKnockBack
float CharacterCore.m_knockBackMultiplier
Vector3 CharacterCore.m_knockBackVec
bool CharacterCore.m_isNoDamage
bool CharacterCore.m_isNoStamina
CharatcerStatus CharacterCore.m_characterStatus
Vector3 CharacterCore.m_initPos
GameObject CharacterCore.m_rushAttackEffect
CharacterGroupNumber CharacterCore.GroupNo
bool CharacterCore.DoFriendlyFire
Referenced by AttackApplicant.Start, AttackStayTrigerAppliciate.Start.
MyCharacterController CharacterCore.CharaCtrl
Referenced by ChildrenMember.SetPosition.
InputTypes CharacterCore.InputType
Referenced by HPBarController.Update.
MoveTypes CharacterCore.MoveType
float CharacterCore.HitStopRemainingTime
Referenced by Damaged, Start.
VisualEffect CharacterCore.TempPlayerAttackEffect
Referenced by Start.
CharatcerStatus CharacterCore.Status
Referenced by BPBarPresenter.BarSetting, BPSkill_1Presenter.BarSetting, BPSkill_2Presenter.BarSetting, HPBarPresenter.BarSetting, StaminaPresenter.BarSetting, BPBarPresenter.BarUpdate, BPSkill_1Presenter.BarUpdate, BPSkill_2Presenter.BarUpdate, HPBarPresenter.BarUpdate, StaminaPresenter.BarUpdate, IsDeadGangster.IsHPDead, LotteryTable.OnCalculate, RotateEnemyTarget.OnStateFixedUpdate, AttackApplicant.Start, AttackStayTrigerAppliciate.Start, BPBarPresenter.Start, BPSkill_1Presenter.Start, BPSkill_2Presenter.Start, HPBarPresenter.Start, StaminaPresenter.Start.
Animator CharacterCore.m_animator
Referenced by TimelineController.PlayerChangeState, TimelineController.PlayerContinue.
PlayerParameters CharacterCore.PlayerParameters
Referenced by BPSkill_1Presenter.BarUpdate, BPSkill_2Presenter.BarUpdate, SummonBarPresenter.InitSetting, ProximitySwitchShowActionUI.OnTriggerEnter, ProximitySwitchShowActionUI.OnTriggerExit, SummonBarPresenter.Start.
EnemyParameters CharacterCore.EnemyParameters
PlayerSkillsParameters CharacterCore.PlayerSkillsParameters
Referenced by SkillAnimeEventAttck.OnEvent, ChildrenMember.SetPosition.
readonly int CharacterCore.PROPERTY_COLOR
void CharacterCore.EnemyResetPos()
References MyCharacterController.SetPositionMotor.
Referenced by GameOverWindow.UpdateJudge, NoTimeWindow.UpdateJudge.
void CharacterCore.Move(float _targetSpeed)
References MyCharacterController.MoveSpeed.
void CharacterCore.SetMoveVec(Vector3 _moveVec)
void CharacterCore.SetRotateToTarget(Vector3 nextVec)
Referenced by Awake.
void CharacterCore.SetStorySkillBP()
References BaseManager< T >.instance, CharacterCore.CharatcerStatus.m_bpSkill_1, CharacterCore.CharatcerStatus.m_bpSkill_2.
Referenced by Awake.
bool CharacterCore.IsDoneTimeLine()
References PlayerSkillsParameters.m_playableDirector.
void CharacterCore.Awake()
References CharacterCore.CharatcerStatus.m_hp, CharacterCore.CharatcerStatus.m_stamina, SetRotateToTarget, SetStorySkillBP.
void CharacterCore.Start()
References HitStopRemainingTime, IMetaAI< T >.Instance, CharacterCore.CharatcerStatus.m_hp, TempPlayerAttackEffect.
void IDamageable. CharacterCore.Damaged(DamageNotification _dmgData, Collider _hitCol, float _knockBackMultiplier, bool _isStrongAttack)
References HitFadeBlink, HitStopRemainingTime, SoundManager.Instance, BaseManager< T >.instance, DamageNotification.m_damage, DamageNotification.m_hitStopTime, CharacterCore.CharatcerStatus.m_hp, CharacterCore.CharatcerStatus.m_knockBackDamage, SoundManager.Start3DPlayback.
async void CharacterCore.HitStop(DamageNotification _dmgData)
References DamageNotification.m_hitStopTime.
void CharacterCore.HitFadeBlink(Color color)
Referenced by Damaged.