PlayerParameters
float PlayerParameters.m_serchEnemyDist
float PlayerParameters.m_speedStick
StorySkill_ID PlayerParameters.m_storySkill1_ID
StorySkill_ID PlayerParameters.m_storySkill2_ID
GameObject PlayerParameters.m_obserbSkill1
GameObject PlayerParameters.m_obserbSkill2
bool PlayerParameters.m_useSkill1Flg
bool PlayerParameters.m_useSkill2Flg
bool PlayerParameters.m_triggerStorySkill_1
bool PlayerParameters.m_triggerStorySkill_2
FloatReactiveProperty PlayerParameters.m_castTimeProgress
TimelineAsset PlayerParameters.m_vanishWeaponEvent
Referenced by HideWeapon.
TimelineAsset PlayerParameters.m_appearWeaponEvent
Referenced by AppearWeapon, UpdateVanishWeapon.
float PlayerParameters.m_appearEventTime
Referenced by StartVanishWeapon.
float PlayerParameters.m_eventTime
Referenced by StartVanishWeapon, UpdateVanishWeapon.
ActionUIController PlayerParameters.m_actionUIController
Referenced by AddActionUIState, AddAnyActionUIState, RemoveActionUIState, RemoveAnyActionUIState.
Vector3 PlayerParameters.m_playerRestartPosition
Vector3 PlayerParameters.m_playerRestartForward
GameObject PlayerParameters.m_actionItemWindowController
float PlayerParameters.SearchEnemyDist
float PlayerParameters.SpeedStick
StorySkill_ID PlayerParameters.StorySkill1_ID
StorySkill_ID PlayerParameters.StorySkill2_ID
GameObject PlayerParameters.ObserbSkill1
GameObject PlayerParameters.ObserbSkill2
bool PlayerParameters.UseSkill1Flg
bool PlayerParameters.UseSkill2Flg
bool PlayerParameters.TriggerStorySkill_1
bool PlayerParameters.TriggerStorySkill_2
FloatReactiveProperty PlayerParameters.CastTimeProgress
Referenced by SummonBarPresenter.InitSetting, SummonBarPresenter.Start.
Vector3 PlayerParameters.PlayerRestartPosition
Vector3 PlayerParameters.PlayerRestartForward
GameObject PlayerParameters.ActionItemWindowController
float PlayerParameters.m_rollingPow
float PlayerParameters.m_rollingAnimeSpeed
PutItemInfo PlayerParameters.m_putItemInfo
AssignItemID PlayerParameters.m_ableGatheringItem
Transform PlayerParameters.m_holdTrans
Vector3 PlayerParameters.m_throwPower
GameObject PlayerParameters.m_mouseThrowAim
Transform PlayerParameters.m_handTrans
GameObject PlayerParameters.m_throwAimCamera
GameObject PlayerParameters.m_playerfollowCamera
GameObject PlayerParameters.m_skillPrefab
GameObject PlayerParameters.m_spellEffect
bool PlayerParameters.m_isVanishWeapon
Referenced by AppearWeapon, HideWeapon, UpdateVanishWeapon.
void PlayerParameters.SetPutItemInfo(ItemInfo.ItemTypeID _itemTypeID, uint _itemID)
void PlayerParameters.StartVanishWeapon()
References m_appearEventTime, m_eventTime.
void PlayerParameters.UpdateVanishWeapon(Animator animator)
References m_appearWeaponEvent, m_eventTime, m_isVanishWeapon.
void PlayerParameters.AppearWeapon(Animator animator)
References m_appearWeaponEvent, m_isVanishWeapon.
void PlayerParameters.HideWeapon(Animator animator)
References m_isVanishWeapon, m_vanishWeaponEvent.
Referenced by ActionItemWindow.CreateSelectUseCraftItemWindow, ActionItemControllerWindow.SelectItemAction.
void PlayerParameters.AddActionUIState(ActionUIController.ActionUIState _state)
References ActionUIController.AddState, m_actionUIController.
Referenced by ProximitySwitchShowActionUI.OnTriggerEnter.
void PlayerParameters.RemoveActionUIState(ActionUIController.ActionUIState _state)
References m_actionUIController, ActionUIController.RemoveState.
Referenced by ProximitySwitchShowActionUI.OnTriggerExit.
void PlayerParameters.AddAnyActionUIState(ActionUIController.ActionUIState _state, float _distance=1.0f)
References ActionUIController.AddAnyActionState, m_actionUIController.
Referenced by ProximitySwitchShowActionUI.OnTriggerEnter.
void PlayerParameters.RemoveAnyActionUIState(ActionUIController.ActionUIState _state)
References m_actionUIController, ActionUIController.RemoveAnyActionState.
Referenced by ProximitySwitchShowActionUI.OnTriggerExit.