ManagementGameManager
float ManagementGameManager.m_timeLimit
Referenced by IsTimeOver, TimeCount.
float ManagementGameManager.m_elapsedTime
Referenced by IsTimeOver, TimeCount.
uint ManagementGameManager.m_earnedMoney
Referenced by AddEarnedMoney, SetManagementData.
Dictionary<CameCustomerType, uint> ManagementGameManager.m_cameCustomerNumDictionary
Referenced by AddCameCustomerNum.
Dictionary<EventSolutionType, uint> ManagementGameManager.m_eventSolutionNumDictionary
Referenced by AddEventSolutionNum.
float ManagementGameManager.TimeLimit
float ManagementGameManager.ElapsedTime
uint ManagementGameManager.EarnedMoney
Dictionary<CameCustomerType, uint> ManagementGameManager.CameCustomerNumDictionary
Dictionary<EventSolutionType, uint> ManagementGameManager.EventSolutionNumDictionary
void ManagementGameManager.Update()
References TimeCount.
void ManagementGameManager.TimeCount()
References m_elapsedTime, m_timeLimit.
Referenced by Update.
void ManagementGameManager.AddEarnedMoney(uint _value)
稼いだ金額を追加
References m_earnedMoney.
void ManagementGameManager.AddCameCustomerNum(CameCustomerType _id, uint _value=1)
来客数を追加
References m_cameCustomerNumDictionary.
void ManagementGameManager.AddEventSolutionNum(EventSolutionType _id, uint _value=1)
イベント数を追加
References m_eventSolutionNumDictionary.
bool ManagementGameManager.IsTimeOver()
経過時間が制限時間を過ぎたかどうか
References m_elapsedTime, m_timeLimit.
Referenced by IsGameEnd.
bool ManagementGameManager.IsProvide()
料理が提供できるか
References BaseManager< T >.instance.
Referenced by IsGameEnd.
bool ManagementGameManager.IsGameEnd()
ゲームが終了したかどうか
References BaseManager< T >.instance, IsProvide, IsTimeOver.
void ManagementGameManager.SetManagementData()
経営情報を更新する この関数はプレイで稼いだ金額等を経営情報管理クラスに更新するものです 適切なところで使用してください
References BaseManager< T >.instance, m_earnedMoney.