BaseWindowUI
CanvasGroup BaseWindowUI.m_canvasGroup
Referenced by SetAlpha.
float BaseWindowUI.m_unUpdateAlpha
Referenced by SetAlpha.
virtual async UniTask BaseWindowUI.OnInitialize()
最初に一度初期化
virtual async UniTask BaseWindowUI.OnUpdate()
常に動作
virtual async UniTask BaseWindowUI.OnLateUpdate()
常に動作、OnUpdateの後処理
virtual async UniTask BaseWindowUI.OnSelectInitialize()
選択されたときに一度初期化
Referenced by WindowUIController.SetUI.
virtual async UniTask BaseWindowUI.OnSelectUpdate()
選択中の場合に動作(OnUpdateより先に行われる)
Referenced by WindowUIController.OnUpdate.
virtual async UniTask BaseWindowUI.OnSelectExit()
選択終了時に終了処理
Referenced by WindowUIController.SetUI.
void BaseWindowUI.SetAlpha(bool _isUpdate)
透明度をセットする
References m_canvasGroup, m_unUpdateAlpha.