SelectUIActionWindowController
bool SelectUIActionWindowController.m_isPut
Referenced by OnLateUpdate, OnPut.
bool SelectUIActionWindowController.m_isUse
Referenced by OnLateUpdate, OnUse.
bool SelectUIActionWindowController.m_isThrow
Referenced by OnLateUpdate, OnThrow.
Vector3 SelectUIActionWindowController.m_selectScale
Referenced by SetSelectUIScale.
Vector3 SelectUIActionWindowController.m_notSelectScale
Referenced by SetSelectUIScale.
float SelectUIActionWindowController.m_duration
Referenced by SetSelectUIScale.
bool SelectUIActionWindowController.IsPut
Referenced by ActionItemControllerWindow.SelectItemAction.
bool SelectUIActionWindowController.IsUse
Referenced by ActionItemControllerWindow.SelectItemAction.
bool SelectUIActionWindowController.IsThrow
Referenced by ActionItemControllerWindow.SelectItemAction.
override void SelectUIActionWindowController.OnUpdate()
References SelectUIController.m_alwaysCreateType, SelectUIController.NullCheck, OnPut, OnThrow, OnUse, SelectWindowUI, SetSelectUIScale.
Referenced by ActionItemControllerWindow.OnUpdate.
override void SelectUIActionWindowController.OnLateUpdate()
References m_isPut, m_isThrow, m_isUse.
Referenced by ActionItemControllerWindow.OnUpdate.
void SelectUIActionWindowController.CheckWithChange()
References SelectUIController.m_currentSelectUIData, SelectUIController.m_currentWidth.
Referenced by ActionItemControllerWindow.DeleteSprite.
override void SelectUIActionWindowController.AddUI(GameObject _ui, SelectUIType _type, int _lineBreak)
スロットリストに引数リストを追加する
References SelectUIController.SetUIActionWindowGameObject.
void SelectUIActionWindowController.SelectWindowUI()
References SoundManager.Instance, BaseManager< T >.instance, SelectUIController.Left, SelectUIController.m_currentSelectUIData, SelectUIController.m_currentWidth, SelectUIController.m_isSelectChangeFlg, SelectUIController.m_uiList, SelectUIController.Right, SoundManager.StartPlayback.
Referenced by OnUpdate.
void SelectUIActionWindowController.OnPut()
References BaseManager< T >.instance, m_isPut.
Referenced by OnUpdate.
void SelectUIActionWindowController.OnUse()
References BaseManager< T >.instance, m_isUse.
Referenced by OnUpdate.
void SelectUIActionWindowController.OnThrow()
References BaseManager< T >.instance, m_isThrow.
Referenced by OnUpdate.
void SelectUIActionWindowController.SetSelectUIScale()
References SelectUIController.m_currentSelectUIData, m_duration, m_notSelectScale, m_selectScale, SelectUIController.m_uiList.
Referenced by OnUpdate.