CreateNeedIngredientSlot
PocketType CreateNeedIngredientSlot.m_pocketType
Referenced by CreateSlotInstance, ProvideFoodCreateNeedIngredientSlotList.Start.
FoodID CreateNeedIngredientSlot.m_foodID
Referenced by CreateCreateFoodNeedIngredientSlotList.CreateSlotInstance, CreateSlotInstance, SetFoodID.
void CreateNeedIngredientSlot.SetFoodID(FoodID _id)
References m_foodID.
Referenced by FoodSlotData.CreateNeedIngredient, ChangeFoodItemDescription.CreateNeedIngredientSlot, ChangeItemDescription.CreateNeedIngredientSlot, SelectFoodDetailUI.SetCreateNeedIngredientSlot.
override void CreateNeedIngredientSlot.CreateSlotInstance()
References BaseCreateSlotList.AddSelectUIControler, BaseCreateSlotList.DestroySlotList, BaseManager< T >.instance, m_foodID, m_pocketType, BaseCreateSlotList.m_slot, BaseCreateSlotList.m_slotList.