BaseGameStateUpdateController
int BaseGameStateUpdateController.m_currentState
Referenced by ChangeState, IsState, LobbyStateUpdateManager.SetInitializeState, ManagementStateUpdateManager.SetInitializeState, SetStateUpdate, StartStateUpdate.
List<BaseGameStateUpdate> BaseGameStateUpdateController.m_stateUpdateList
Referenced by SetStateUpdate.
BaseGameStateUpdate BaseGameStateUpdateController.m_currentStateUpdate
Referenced by DestroyState, ExitState, InitializeState, SetStateUpdate, UpdateState.
void BaseGameStateUpdateController.Start()
References StartStateUpdate.
async UniTask BaseGameStateUpdateController.ChangeState(int _state)
References DestroyState, ExitState, InitializeState, m_currentState, SetStateUpdate, UpdateState.
Referenced by StartStateUpdate, UpdateState.
async UniTask BaseGameStateUpdateController.InitializeState()
初期処理
References m_currentStateUpdate, BaseGameStateUpdate.OnInitialize.
Referenced by ChangeState.
async UniTask BaseGameStateUpdateController.UpdateState()
毎フレーム実行される処理
References ChangeState, BaseGameStateUpdate.GetNextState, BaseGameStateUpdate.IsEnd, m_currentStateUpdate, BaseGameStateUpdate.OnUpdate.
Referenced by ChangeState.
async UniTask BaseGameStateUpdateController.ExitState()
終了処理
References m_currentStateUpdate, BaseGameStateUpdate.OnExit.
Referenced by ChangeState.
async UniTask BaseGameStateUpdateController.DestroyState()
削除処理
References m_currentStateUpdate, BaseGameStateUpdate.OnDestroy.
Referenced by ChangeState, SetStateUpdate.
bool BaseGameStateUpdateController.IsState(int _state)
References m_currentState.
virtual async UniTask BaseGameStateUpdateController.StartStateUpdate()
References ChangeState, m_currentState, SetInitializeState.
Referenced by Start.
virtual void BaseGameStateUpdateController.SetInitializeState()
References BaseManager< T >.instance.
Referenced by StartStateUpdate.
virtual void BaseGameStateUpdateController.SetState(string _sceneName, int _state)
async UniTask BaseGameStateUpdateController.SetStateUpdate()
一致するステートの処理をセット
References DestroyState, m_currentState, m_currentStateUpdate, m_stateUpdateList.
Referenced by ChangeState.