ManagementProvideFoodSlotData
TextMeshProUGUI ManagementProvideFoodSlotData.m_provideNumText
Referenced by SetProvideNumText.
TextMeshProUGUI ManagementProvideFoodSlotData.m_soldNumText
Referenced by SetSoldNumText.
TextMeshProUGUI ManagementProvideFoodSlotData.m_soldPriceText
Referenced by SetSoldPriceText.
void ManagementProvideFoodSlotData.Start()
References BaseManager< T >.instance, ItemSlotData.m_itemID, ItemSlotData.m_itemTypeID, ItemSlotData.m_pocketType, SetItemSlotData.
override void ManagementProvideFoodSlotData.SetItemSlotData(BaseItemData _itemData, PocketType _pocketType)
References SetProvideFoodData.
Referenced by Start.
override void ManagementProvideFoodSlotData.InitializeSlotData()
References SetProvideNumText, SetSoldNumText, SetSoldPriceText.
void ManagementProvideFoodSlotData.SetProvideFoodData()
References BaseManager< T >.instance, ItemSlotData.m_itemID, SetProvideNumText, SetSoldNumText, SetSoldPriceText.
Referenced by SetItemSlotData.
void ManagementProvideFoodSlotData.SetProvideNumText(ProvideFoodData _data, bool _active=true)
References m_provideNumText, ProvideFoodData.ProvideNum.
Referenced by InitializeSlotData, SetProvideFoodData.
void ManagementProvideFoodSlotData.SetSoldNumText(ProvideFoodData _data, bool _active=true)
References m_soldNumText, ProvideFoodData.SoldNum.
Referenced by InitializeSlotData, SetProvideFoodData.
void ManagementProvideFoodSlotData.SetSoldPriceText(ProvideFoodData _data, bool _active=true)
References ProvideFoodData.FoodID, BaseManager< T >.instance, m_soldPriceText.
Referenced by InitializeSlotData, SetProvideFoodData.