BlinkingSelectedButton
CanvasGroup BlinkingSelectedButton.m_canvasGroup
Referenced by Awake, EndEasing, StartEasing, Update.
Button BlinkingSelectedButton.m_button
Referenced by Awake, Update.
float BlinkingSelectedButton.m_blinkSpeed
Referenced by StartEasing.
float BlinkingSelectedButton.m_minAlpha
Referenced by StartEasing.
float BlinkingSelectedButton.m_maxAlpha
Referenced by EndEasing.
void BlinkingSelectedButton.Awake()
References m_button, m_canvasGroup.
void BlinkingSelectedButton.Update()
References EndEasing, m_button, m_canvasGroup, StartEasing.
void BlinkingSelectedButton.OnDisable()
References EndEasing.
void BlinkingSelectedButton.StartEasing()
References m_blinkSpeed, m_canvasGroup, m_minAlpha.
Referenced by Update.
void BlinkingSelectedButton.EndEasing()
References m_canvasGroup, m_maxAlpha.
Referenced by OnDisable, Update.