SoundManager
SoundManager SoundManager.Instance
Referenced by CreateToUpdateSelectUseItemWindow.Create< WindowType >, AnimEventAttack.CreateObject, CreateNonProXiWindow.CreateWindow, ProximityCreateWindow.CreateWindow, WindowController.CreateWindow< WindowType >, CharacterCore.Damaged, OrderFoodData.FindCounterPointData, BaseWindow.IsClose, OnHitDestoyObject.OnCollisionEnter, PlaySEOnEnable.OnEnable, CharacterCore.ActionState_PutItem.OnEnter, CharacterCore.ActionState_Rolling.OnEnter, CharacterCore.ActionState_UseItem.OnEnter, TitleEntryPoint.OnEnter, AnimatorEventPlaySE.OnEvent, TitleEntryPoint.OnFinalize, BaseWindow.OnShow, ActionItemWindow.OnUpdate, CharacterCore.ActionState_SkillLRR_Fall.OnUpdate, CuePlay.Play, CuePlay.Play3D, CuePlay.PlayBGM, PlayAnimationEvent_FootStepSound.PlayFootSound, SelectUIController.PlayPressSound, InputActionButton.PlaySE, SelectUIController.PlaySelectSound, SelectUIController.SelectActionWindowUI, SelectUIActionWindowController.SelectWindowUI, AttackApplicant.Start, AttackStayTrigerAppliciate.Start, BattleSceneBGM.Start, ManagemntSceneBGM.Start, StartBGM.Start, ThrowRock.Start, ThrowItemInstance.Throw, BattleSceneBGM.Update.
CriAtomExPlayer SoundManager.BGMPlayer
CriAtomExPlayer SoundManager.m_bgmPlayer
CriAtomExPlayback SoundManager.m_currentBGM
bool SoundManager.m_disposedValue
CriAtomExPlayback SoundManager.StartPlayback(string cueName, float vol=1.0f, float pitch=0)
2Dでのサウンド再生
cueName サウンドの識別名称 vol 音量設定(0~1) pitch 音程設定(-2400~2400) 1200で1オクターブ変わる CriAtomExPlayback
References player.
Referenced by CreateToUpdateSelectUseItemWindow.Create< WindowType >, CreateNonProXiWindow.CreateWindow, ProximityCreateWindow.CreateWindow, WindowController.CreateWindow< WindowType >, OrderFoodData.FindCounterPointData, BaseWindow.IsClose, PlaySEOnEnable.OnEnable, CharacterCore.ActionState_PutItem.OnEnter, CharacterCore.ActionState_Rolling.OnEnter, AnimatorEventPlaySE.OnEvent, BaseWindow.OnShow, ActionItemWindow.OnUpdate, CuePlay.Play, PlayAnimationEvent_FootStepSound.PlayFootSound, SelectUIController.PlayPressSound, InputActionButton.PlaySE, SelectUIController.PlaySelectSound, SelectUIController.SelectActionWindowUI, SelectUIActionWindowController.SelectWindowUI, ExtensionSoundManager.SetLoopPlayback, StartPlayback.
CriAtomExPlayback SoundManager.StartPlayback(SoundData data)
2Dでのサウンド再生
data サウンドデータクラス CriAtomExPlayback
References SoundData.m_pitch, SoundData.m_soundName, SoundData.m_volume, StartPlayback.
CriAtomExPlayback SoundManager.Start3DPlayback(string cueName, UnityEngine.Vector3 pos, float vol=1.0f, float pitch=0)
座標のみ指定での3D再生 指定された座標にオブジェクトを作成しCriAtomExPlayer,Instant3DSoundPlayerを紐づけ再生 再生終了時自動でオブジェクトが破棄される
cueName サウンドの識別名称 pos 座標 vol 音量設定(0~1) pitch 音程設定(-2400~2400) 1200で1オクターブ変わる CriAtomExPlayback
Referenced by AnimEventAttack.CreateObject, CharacterCore.Damaged, OnHitDestoyObject.OnCollisionEnter, PlaySEOnEnable.OnEnable, CharacterCore.ActionState_UseItem.OnEnter, AnimatorEventPlaySE.OnEvent, CharacterCore.ActionState_SkillLRR_Fall.OnUpdate, CuePlay.Play3D, AttackApplicant.Start, AttackStayTrigerAppliciate.Start, ThrowRock.Start, Start3DPlayback, Start3DPlayback, ThrowItemInstance.Throw.
CriAtomExPlayback SoundManager.Start3DPlayback(SoundData data, UnityEngine.Vector3 pos)
座標のみ指定での3D再生 指定された座標にオブジェクトを作成しCriAtomExPlayer,Instant3DSoundPlayerを紐づけ再生 再生終了時自動でオブジェクトが破棄される
data サウンドデータクラス pos 座標 CriAtomExPlayback
References SoundData.m_pitch, SoundData.m_soundName, SoundData.m_volume, Start3DPlayback.
CriAtomExPlayback SoundManager.Start3DPlayback(string cueName, GameObject obj, float vol=1.0f, float pitch=0)
3D再生 指定されたオブジェクトに音源を設定し再生
cueName サウンドの識別名称 obj オブジェクト vol 音量設定(0~1) pitch 音程設定(-2400~2400) 1200で1オクターブ変わる CriAtomExPlayback
CriAtomExPlayback SoundManager.Start3DPlayback(SoundData data, GameObject obj)
3D再生 指定されたオブジェクトに音源を設定し再生
cueName サウンドの識別名称 obj オブジェクト vol 音量設定(0~1) pitch 音程設定(-2400~2400) 1200で1オクターブ変わる CriAtomExPlayback
References SoundData.m_pitch, SoundData.m_soundName, SoundData.m_volume, Start3DPlayback.
void SoundManager.StartBGM(string cueName, float vol=1.0f, float pitch=0)
BGM再生
cueName サウンドの識別名称 vol 音量設定(0~1) pitch 音程設定(-2400~2400) 1200で1オクターブ変わる
Referenced by TitleEntryPoint.OnEnter, CuePlay.PlayBGM, BattleSceneBGM.Start, ManagemntSceneBGM.Start, StartBGM.Start, BattleSceneBGM.Update.
void SoundManager.StartBGM(SoundData sound)
References SoundData.m_pitch, SoundData.m_soundName, SoundData.m_volume.
void SoundManager.StopBGM()
BGM再生停止
Referenced by TitleEntryPoint.OnFinalize.
void SoundManager.PauseBGM()
BGM一時停止
void SoundManager.ResumeBGM()
BGM再開
void SoundManager.SetBGMVolumeAndPitch(float vol, float pitch)
BGMの音量とピッチを設定
vol 音量設定(0~1) pitch 音程設定(-2400~2400) 1200で1オクターブ変わる
bool SoundManager.IsBGMPaused()
BGM再生中かどうか
void SoundManager.Dispose()
破棄処理
References Dispose.
SoundManager.SoundManager()
void SoundManager.Dispose(bool disposing)
破棄処理
Referenced by Dispose, ~SoundManager.
SoundManager.~SoundManager()
References Dispose.