FoodData
FoodID FoodData.m_foodID
Referenced by SetData.
GameObject FoodData.m_managementFoodPrefab
List<NeedIngredientObject> FoodData.m_needIngredientObjectList
int FoodData.m_createDelay
uint FoodData.m_price
float FoodData.m_throwRange
GameObject FoodData.ManagementFoodPrefab
Referenced by CounterManager.CreateOrderFood.
List<NeedIngredientObject> FoodData.NeedIngredientObjectList
この料理に必要な材料の種類をまとめたリストを返す、読み取り専用プロパティ
料理に必要な材料の種類をまとめたリスト
int FoodData.CreateDelay
uint FoodData.Price
Referenced by ChangeFoodItemDescription.SetPriceText, FoodSlotData.SetPriceText.
float FoodData.ThrowRange
override void FoodData.SetData()
References m_foodID, BaseItemData.m_itemID, BaseItemData.m_itemTypeID.
Referenced by ItemDataBaseManager.SetID.
static void FoodData.CreateFood(PocketType _pocketType, FoodID _foodID, bool _removeFlg)
引数料理を作成後、ポケットに追加する
References IsCreate, RemoveNeedIngredient.
Referenced by CreateFoodController.CreateFood.
static bool FoodData.IsCreate(PocketType _pocketType, FoodID _id)
引数料理が作成できるか確認するメソッド
References GetCreateNum.
Referenced by RecipeItemSlotData.CheckCreate, CreateFood, CreateFoodInputActionButton.IsPress, RemoveNeedIngredient, CreateFoodController.SetFoodData.
static bool FoodData.IsProvide(PocketType _pocketType, FoodID _id)
引数料理が提供できるか確認するメソッド
References GetProvideNum.
Referenced by ProvideFoodRecipeSlotData.CheckCreate, ManagementProvideFoodManager.PublishSoldOutProvideFoodEvent.
static int FoodData.GetCreateNum(PocketType _pocketType, FoodID _id)
引数料理が作成できる数を確認するメソッド
References BaseManager< T >.instance.
Referenced by GetProvideNum, IsCreate, ChangeFoodItemDescription.SetCreateNumText, ChangeItemDescription.SetCreateNumText, FoodSlotData.SetCreateNumText, CreateFoodController.SetFoodData.
static int FoodData.GetProvideNum(PocketType _pocketType, FoodID _id)
引数料理が作成できるか確認するメソッド
References GetCreateNum.
Referenced by ManagementProvideFoodManager.AddProvideFoodList, IsProvide, ProvideFoodRecipeSlotData.SetProvideNumText.
static bool FoodData.RemoveNeedIngredient(PocketType _pocketType, FoodID _foodID)
必要食材をポケットから取り除く
References BaseManager< T >.instance, IsCreate.
Referenced by CreateFood, RemoveProvideNeedIngredient.
static bool FoodData.RemoveProvideNeedIngredient(PocketType _pocketType, FoodID _foodID)
既存の料理をポケットから取り除く 取り除けなかった場合は食材を取り除く
References RemoveNeedIngredient.
Referenced by ManagementProvideFoodManager.RemoveProvideFood.