FoodSlotData
TextMeshProUGUI FoodSlotData.m_priceNumText
Referenced by SetPriceText.
TextMeshProUGUI FoodSlotData.m_createNumText
Referenced by SetCreateNumText.
CreateNeedIngredientSlot FoodSlotData.m_createNeedIngredientSlot
Referenced by CreateNeedIngredient.
override void FoodSlotData.SetItemSlotData(BaseItemData _itemData, PocketType _pocketType)
References CreateNeedIngredient, SetCreateNumText, SetPriceText.
Referenced by CurrentSelectManagementProvideFoodSlotData.SetSlot.
override void FoodSlotData.InitializeSlotData()
References CreateNeedIngredient, SetCreateNumText, SetPriceText.
virtual void FoodSlotData.CreateNeedIngredient(bool _active=true)
References BaseCreateSlotList.CreateSlot, m_createNeedIngredientSlot, ItemSlotData.m_itemID, CreateNeedIngredientSlot.SetFoodID.
Referenced by InitializeSlotData, SetItemSlotData.
virtual void FoodSlotData.SetPriceText(BaseItemData _data, bool _active=true)
References m_priceNumText, FoodData.Price.
Referenced by InitializeSlotData, SetItemSlotData.
virtual void FoodSlotData.SetCreateNumText(BaseItemData _data, bool _active=true)
References FoodData.GetCreateNum, m_createNumText, ItemSlotData.m_pocketType.
Referenced by InitializeSlotData, SetItemSlotData.