BaseWindow
DepthOfFieldType
GameStopType
GameStopMoveType
HideUIType
CanvasGroup BaseWindow.m_canvasGroup
Referenced by OnDOAlpha.
float BaseWindow.m_doSpead
Referenced by OnClose, OnShow.
DepthOfFieldType BaseWindow.m_depthOfFieldType
Referenced by SetGlobalVolume.
GameStopType BaseWindow.m_gameStopType
Referenced by CreateToUpdateWindow< WindowType >, SetTimeScale.
GameStopMoveType BaseWindow.m_gameStopMoveType
Referenced by OnDOAlpha, OnDOScale.
HideUIType BaseWindow.m_hideUIType
Referenced by HideOtherUI, ShowOtherUI.
InputActionButtonController BaseWindow.m_inputActionButtonController
Referenced by OnInitialize, OnUpdate.
InputActionButton BaseWindow.m_closeInputActionButton
Referenced by IsClose.
Volume BaseWindow.m_globalVolume
Referenced by SetDepthOfField, SetGlobalVolume.
List<CanvasGroup> BaseWindow.m_hideCanvasGroupList
Referenced by HideOtherUI, SetCanvasGroupList, ShowOtherUI.
PlayerInput BaseWindow.m_input
Referenced by ActionItemControllerWindow.OnUpdate, ActionItemWindow.OnUpdate.
string BaseWindow.m_openSEName
Referenced by OnShow.
string BaseWindow.m_closeSEName
Referenced by IsClose.
PlayerInput BaseWindow.Input
virtual async UniTask BaseWindow.OnInitialize()
References HideOtherUI, m_inputActionButtonController, InputActionButtonController.OnInitialize, SetCanvasGroupList, SetGlobalVolume, SetTimeScale.
virtual async UniTask BaseWindow.OnShow()
References SoundManager.Instance, m_doSpead, m_openSEName, OnDOAlpha, SetDepthOfField, SoundManager.StartPlayback.
virtual async UniTask BaseWindow.OnUpdate()
References m_inputActionButtonController, InputActionButtonController.OnUpdate, SetDepthOfField, SetTimeScale.
virtual async UniTask BaseWindow.OnClose()
References m_doSpead, OnDOAlpha, SetDepthOfField, SetTimeScale, ShowOtherUI.
virtual async UniTask BaseWindow.OnDestroy()
async UniTask< WindowType > BaseWindow.CreateToUpdateWindow< WindowType >(WindowController _windowController, bool _isSelf, System.Func< WindowType, UniTask > onBeforeInitialize=null)
引数のウィンドウコントローラーを基に ウィンドウのインスタンスを生成して実行する 引数ウィンドウコントローラーは自身で作成して下さい
References m_gameStopType.
async UniTask BaseWindow.OnDOScale(Ease _ease, float _duration, bool _fromFlg, Vector3 _endValue=default)
References m_gameStopMoveType.
async UniTask BaseWindow.OnDOAlpha(float _duration, bool _fromFlg, float _endValue=0.0f)
References m_canvasGroup, m_gameStopMoveType.
Referenced by OnClose, OnShow.
virtual bool BaseWindow.IsClose()
References SoundManager.Instance, InputActionButton.IsInputActionTrriger, m_closeInputActionButton, m_closeSEName, SoundManager.StartPlayback.
Referenced by ConfirmationWindow.OnUpdate, CreateFoodWindow.OnUpdate, InventoryWindow.OnUpdate, ManagementResultWindow.OnUpdate, ManagementSelectProvideFoodWindow.OnUpdate, ManagementStandbyWindow.OnUpdate, NewItemWindow.OnUpdate, RecipeWindow.OnUpdate, SelectManagementWindow.OnUpdate, SelectStageWindow.OnUpdate, TutorialWindow.OnUpdate.
void BaseWindow.SetGlobalVolume()
References m_depthOfFieldType, m_globalVolume.
Referenced by OnInitialize.
void BaseWindow.SetDepthOfField(bool _isDepthOfField)
References m_globalVolume.
Referenced by OnClose, OnShow, OnUpdate.
void BaseWindow.SetTimeScale(float _timeScale)
References m_gameStopType.
Referenced by OnClose, OnInitialize, OnUpdate, InventoryWindow.OnUpdate.
async UniTask BaseWindow.HideOtherUI()
References m_hideCanvasGroupList, m_hideUIType.
Referenced by OnInitialize.
async UniTask BaseWindow.ShowOtherUI()
References m_hideCanvasGroupList, m_hideUIType.
Referenced by OnClose.
void BaseWindow.SetCanvasGroupList()
References m_hideCanvasGroupList.
Referenced by OnInitialize.