ManagementStateUpdate_Standby
WindowController ManagementStateUpdate_Standby.m_windowController
Referenced by CreateToUpdateWindow.
WindowController ManagementStateUpdate_Standby.m_createWindowController
Referenced by CreateToUpdateWindow, DestoryWindowController.
override async UniTask ManagementStateUpdate_Standby.OnInitialize()
初期処理
References CreateToUpdateWindow.
override async UniTask ManagementStateUpdate_Standby.OnExit()
終了処理
References DestoryWindowController.
async UniTask ManagementStateUpdate_Standby.CreateToUpdateWindow()
References DestoryWindowController, m_createWindowController, BaseManagementStateUpdate.m_nextManagementState, m_windowController, BaseManagementStateUpdate.SetEnd.
Referenced by OnInitialize.
void ManagementStateUpdate_Standby.DestoryWindowController()
References m_createWindowController.
Referenced by CreateToUpdateWindow, OnExit.