SelectFoodDetailUI
SelectUIController SelectFoodDetailUI.m_recipeSelectUIController
Referenced by OnUpdate, SetCreateNeedIngredientSlot.
CreateNeedIngredientSlot SelectFoodDetailUI.m_createNeedIngredientSlot
Referenced by SetCreateNeedIngredientSlot.
override async UniTask SelectFoodDetailUI.OnInitialize()
初期化処理
References SetCreateNeedIngredientSlot.
Referenced by ManagementSelectProvideFoodWindow.OnInitialize.
override async UniTask SelectFoodDetailUI.OnUpdate()
実行処理
References SelectUIController.IsSelectChangeFlg, m_recipeSelectUIController, SetCreateNeedIngredientSlot.
Referenced by ManagementSelectProvideFoodWindow.OnUpdate.
void SelectFoodDetailUI.SetCreateNeedIngredientSlot()
References BaseCreateSlotList.CreateSlot, SelectUIController.CurrentSelectUI, BaseManager< T >.instance, m_createNeedIngredientSlot, m_recipeSelectUIController, CreateNeedIngredientSlot.SetFoodID.
Referenced by OnInitialize, OnUpdate.