ProximityCreateUI
ProximityCreateUIDestroyType
string ProximityCreateUI.m_tag
Referenced by OnTriggerEnter, OnTriggerExitCollider.
bool ProximityCreateUI.m_showAgainFlg
Referenced by DestroyUI.
GameObject ProximityCreateUI.m_uiPrefab
Referenced by CreateUI.
GameObject ProximityCreateUI.m_createUI
Referenced by CreateUI, DestroyUI, GetCanvasGroup, OnTriggerExitCollider, UpdateCollider, UpdateEndCollider, UpdateTime.
float ProximityCreateUI.m_doDuration
Referenced by HideUI, ShowUI.
ProximityCreateUIDestroyType ProximityCreateUI.m_type
Referenced by OnTriggerExitCollider, UpdateCollider, UpdateEndCollider, UpdateTime.
bool ProximityCreateUI.m_isCreate
Referenced by CreateUI, OnTriggerEnter, OnTriggerExitCollider, UpdateEndCollider, UpdateTime.
ShareOnTrigger ProximityCreateUI.m_endTrriger
Referenced by UpdateEndCollider.
float ProximityCreateUI.m_hideDelay
Referenced by UpdateTime.
float ProximityCreateUI.m_currentDelay
Referenced by InitTime, UpdateTime.
void ProximityCreateUI.OnTriggerEnter(Collider other)
References m_isCreate, m_tag.
void ProximityCreateUI.OnTriggerExit(Collider other)
References OnTriggerExitCollider.
void ProximityCreateUI.Update()
References CreateUI, UpdateCollider, UpdateEndCollider, UpdateTime.
void ProximityCreateUI.CreateUI()
References m_createUI, m_isCreate, m_uiPrefab, ShowUI.
Referenced by Update.
void ProximityCreateUI.DestroyUI()
References m_createUI, m_showAgainFlg.
Referenced by HideUI.
CanvasGroup ProximityCreateUI.GetCanvasGroup()
References m_createUI.
Referenced by HideUI, ShowUI.
void ProximityCreateUI.ShowUI()
References GetCanvasGroup, m_doDuration.
Referenced by CreateUI.
void ProximityCreateUI.HideUI()
References DestroyUI, GetCanvasGroup, m_doDuration.
Referenced by OnTriggerExitCollider, UpdateEndCollider, UpdateTime.
List< CanvasGroup > ProximityCreateUI.GetCanvasGroupList()
void ProximityCreateUI.OnTriggerExitCollider(Collider other)
References HideUI, m_createUI, m_isCreate, m_tag, m_type.
Referenced by OnTriggerExit.
void ProximityCreateUI.UpdateCollider()
References m_createUI, m_type.
Referenced by Update.
void ProximityCreateUI.UpdateEndCollider()
References HideUI, ShareOnTrigger.IsTrigger, m_createUI, m_endTrriger, m_isCreate, m_type.
Referenced by Update.
void ProximityCreateUI.InitTime()
References m_currentDelay.
Referenced by UpdateTime.
void ProximityCreateUI.UpdateTime()
References HideUI, InitTime, m_createUI, m_currentDelay, m_hideDelay, m_isCreate, m_type, Time.
Referenced by Update.