BasePocketItemDataController
int BasePocketItemDataController.m_listMaxSize
Referenced by GetFreeSpaceNum, IsInList.
List<PocketItemData> BasePocketItemDataController.m_itemDataList
Referenced by AddItem, GetFreeSpaceNum, GetItemList, GetItemNum, GetRandomItemData, IsHave, IsInList, RemoveItem.
int BasePocketItemDataController.ListMaxSize
List<PocketItemData> BasePocketItemDataController.ItemDataList
Referenced by LobbyStateUpdate_ReturnAction.OnExit, LobbyStateUpdate_ReturnAction.Transfer.
List<DefaultPocketItemData> BasePocketItemDataController.m_defaultInventoryItemDataList
Referenced by AddDefaultItemData.
void BasePocketItemDataController.Start()
References AddDefaultItemData.
void BasePocketItemDataController.AddDefaultItemData()
References AddItem, m_defaultInventoryItemDataList.
Referenced by Start.
virtual bool BasePocketItemDataController.AddItem(ItemTypeID _itemTypeID, uint _itemID)
アイテムリストに引数アイテムを追加する
_itemTypeID 追加したいアイテムの種類 _itemID 追加したいアイテムのID /// true - 追加できた false - 追加できなかった
References PocketItemData.CreateItemData, BaseManager< T >.instance, IsInList, m_itemDataList, GlobalAddItemEvent.PublishGlobalAddItemEven.
Referenced by AddDefaultItemData, InventoryManager.AddItem, LobbyStateUpdate_ReturnAction.Transfer.
virtual bool BasePocketItemDataController.RemoveItem(ItemTypeID _itemTypeID, uint _itemID, int _removeNum=1)
アイテムリストに存在する引数アイテムを減算/削除する
_itemTypeID 減算/削除したいアイテムの種類 _itemID 減算/削除したいアイテムのID _removeNum 減算数 /// true - 減算/削除できた false - 減算/削除できなかった
References m_itemDataList.
Referenced by InventoryManager.RemoveItem.
virtual bool BasePocketItemDataController.IsInList()
ポケット空き容量が最大数に達しているか確認するメソッド
true - 達していない(取得可能) false - 達している(取得不可)
References m_itemDataList, m_listMaxSize.
Referenced by AddItem, GetItemObject.OnTriggerEnter.
virtual int BasePocketItemDataController.GetItemNum(ItemTypeID _itemTypeID, uint _itemID)
引数IDのアイテム所持数を取得するメソッド
_itemTypeID 取得したいアイテムの種類 _itemID 取得したいアイテムのID 引数IDのアイテム所持数
References m_itemDataList.
Referenced by ActionItemControllerWindow.DeleteSprite.
virtual List< PocketItemData > BasePocketItemDataController.GetItemList(ItemTypeID _typeID)
References m_itemDataList.
Referenced by CreateActionItemSlotList.GetItemSlotDataList.
virtual bool BasePocketItemDataController.IsHave(ItemTypeID _itemTypeID, uint _itemID)
引数アイテムを所持しているかどうか
References m_itemDataList.
virtual PocketItemData BasePocketItemDataController.GetRandomItemData(ItemTypeID _itemTypeID)
所持アイテムからランダムで取得
References m_itemDataList.
virtual int BasePocketItemDataController.GetFreeSpaceNum()
空き容量を取得
References m_itemDataList, m_listMaxSize.
static void BasePocketItemDataController.AllInitializePocketDataList()
全てのポケットデータを初期化
Referenced by LobbyStateUpdate_TrialSession.InitializeTrialSession.