StaminaController
float StaminaController.m_value
Referenced by SetValue, UpdateFillAmount.
List<HPBarColor> StaminaController.m_barColorList
Referenced by UpdateFillAmount.
Image StaminaController.m_image
Referenced by Start, UpdateFillAmount.
bool StaminaController.m_isView
Referenced by OnHide, OnShow, Start.
float StaminaController.m_showDuration
Referenced by OnShow.
float StaminaController.m_hideDuration
Referenced by OnHide.
List<Image> StaminaController.m_viewImageList
Referenced by OnHide, OnShow, Start.
float StaminaController.m_max
Referenced by SetValue, SetValue.
float StaminaController.Max
void StaminaController.Start()
References m_image, m_isView, m_viewImageList.
void ISerializationCallbackReceiver. StaminaController.OnBeforeSerialize()
インスペクターで値を変更した時に呼ばれる（保存前）
References UpdateFillAmount.
void ISerializationCallbackReceiver. StaminaController.OnAfterDeserialize()
インスペクターでの値の変更後、保存された値を読み込む際に呼ばれる
void StaminaController.UpdateFillAmount()
References m_barColorList, m_image, m_value.
Referenced by OnBeforeSerialize, SetValue.
void StaminaController.SetValue(float _current, float _max)
References m_max, SetValue.
Referenced by StaminaPresenter.BarSetting, StaminaPresenter.BarUpdate, SetValue.
void StaminaController.SetValue(float _current)
References m_max, m_value, UpdateFillAmount.
void StaminaController.OnShow()
References m_isView, m_showDuration, m_viewImageList.
Referenced by StaminaPresenter.Start.
void StaminaController.OnHide()
References m_hideDuration, m_isView, m_viewImageList.
Referenced by StaminaPresenter.Start.