BaseCustomerCalculator
FlexibleCustomerDataVariable BaseCustomerCalculator.m_flexibleCustomerDataVariable
Referenced by GetCustomerData.
OutputSlotVector3 BaseCustomerCalculator.m_outputPos
Referenced by CalcAppearPosCustomer.OnCalculate, CalcChairPosCustomer.OnCalculate, CalcQueueHeadPositionCustomer.OnCalculate, CalcQueuePointPosCustomer.OnCalculate, CalcTargetTablePositionCustomer.OnCalculate.
CustomerData BaseCustomerCalculator.GetCustomerData()
客情報が存在するかのチェック
References m_flexibleCustomerDataVariable.
Referenced by CalcAppearPosCustomer.OnCalculate, CalcChairPosCustomer.OnCalculate, CalcQueuePointPosCustomer.OnCalculate, CalcTargetTablePositionCustomer.OnCalculate.
GameObject BaseCustomerCalculator.GetRootGameObject()