WindowController
CreateWindowType
CreateWindowType WindowController.m_createWindowType
Referenced by UpdateInput, UpdateStart.
GameObject WindowController.m_window
Referenced by CreateWindow< WindowType >.
PlayerInput WindowController.m_input
Referenced by CreateWindow< WindowType >, UpdateInput.
GameObject WindowController.m_createWindowObject
Referenced by CreateWindow< WindowType >, DestroyWindow.
PlayerInput WindowController.Input
GameObject WindowController.CreateWindowObject
void WindowController.Start()
References UpdateStart.
void WindowController.Update()
References UpdateInput.
async UniTask WindowController.UpdateStart()
References m_createWindowType.
Referenced by Start.
async UniTask WindowController.UpdateInput()
References BaseManager< T >.instance, m_createWindowType, m_input.
Referenced by Update.
void WindowController.DestroyWindow()
References m_createWindowObject.
Referenced by CreateWindow< WindowType >.
async UniTask< WindowType > WindowController.CreateWindow< WindowType >(bool _bSelef=false, System.Func< WindowType, UniTask > onBeforeInitialize=null)
WindowType _bSelef 作成までは行い、その後の動作は自身で操作する _isType 停止などの処理を行うかどうか onBeforeInitialize 独自の処理を追加する場合
References DestroyWindow, SoundManager.Instance, m_createWindowObject, m_input, m_window, SoundManager.StartPlayback.