CaptureScreenToImage
Image CaptureScreenToImage.m_image
Referenced by Capture.
void CaptureScreenToImage.Button()
References Capture.
async UniTask CaptureScreenToImage.Capture()
References m_image.
Referenced by Button, TestNotingEntryPoint.OnExit, TitleEntryPoint.OnExit, NextPageTransitionBehaviour.ScreenShot.