HoldItemInstance
string HoldItemInstance.m_tag
Referenced by Awake.
GameObject HoldItemInstance.m_targetObject
Referenced by Awake.
Transform HoldItemInstance.m_holdPointTrans
Referenced by Craft, SetHoldPoint.
GameObject HoldItemInstance.m_itemObj
Referenced by Craft, DestroyPrefab, OnDestroy.
ItemTypeID HoldItemInstance.m_itemTypeID
Referenced by Craft, SetItemID.
uint HoldItemInstance.m_itemID
Referenced by Craft, SetItemID.
ItemTypeID HoldItemInstance.ItemTypeID
uint HoldItemInstance.ItemID
Referenced by CharacterCore.ActionState_HoldItem.OnUpdate.
void HoldItemInstance.Awake()
References m_tag, m_targetObject.
void HoldItemInstance.OnDestroy()
References m_itemObj.
void HoldItemInstance.SetItemID(ItemTypeID _itemTypeID, uint _itemID)
References m_itemID, m_itemTypeID.
Referenced by CharacterCore.ActionState_HoldItem.OnEnter, CharacterCore.ActionState_HoldItem.OnUpdate.
void HoldItemInstance.SetHoldPoint(Transform _holdPointTrans)
References m_holdPointTrans.
Referenced by CharacterCore.ActionState_HoldItem.OnEnter, CharacterCore.ActionState_HoldItem.OnUpdate.
void HoldItemInstance.Craft()
References BaseManager< T >.instance, m_holdPointTrans, m_itemID, m_itemObj, m_itemTypeID.
Referenced by CharacterCore.ActionState_HoldItem.OnEnter, CharacterCore.ActionState_HoldItem.OnUpdate.
void HoldItemInstance.DestroyPrefab()
References m_itemObj.
Referenced by CharacterCore.ActionState_HoldItem.OnUpdate.