ChangeSelectTutorialControllerDescription
SelectTutorialController ChangeSelectTutorialControllerDescription.m_selectTutorialController
Referenced by IsChangeDescription, SetDescription, SetPageText.
Image ChangeSelectTutorialControllerDescription.m_image
Referenced by SetImage.
TextMeshProUGUI ChangeSelectTutorialControllerDescription.m_text
Referenced by SetText.
TextMeshProUGUI ChangeSelectTutorialControllerDescription.m_pageNumText
Referenced by SetPageText.
virtual void ChangeSelectTutorialControllerDescription.OnInitialize()
References SetDescription.
Referenced by TutorialWindow.OnInitialize.
virtual void ChangeSelectTutorialControllerDescription.OnUpdate()
References IsChangeDescription, SetDescription.
Referenced by TutorialWindow.OnUpdate.
bool ChangeSelectTutorialControllerDescription.IsChangeDescription()
References SelectTutorialController.IsSelectChangeFlg, m_selectTutorialController.
Referenced by OnUpdate.
void ChangeSelectTutorialControllerDescription.SetDescription()
References SelectTutorialController.GetCurrentTutorialData, m_selectTutorialController, SetImage, SetPageText, SetText.
Referenced by OnInitialize, OnUpdate.
void ChangeSelectTutorialControllerDescription.SetImage(TutorialData _data)
References m_image, TutorialData.Sprite.
Referenced by SetDescription.
void ChangeSelectTutorialControllerDescription.SetText(TutorialData _data)
References m_text, TutorialData.Text.
Referenced by SetDescription.
void ChangeSelectTutorialControllerDescription.SetPageText()
References m_pageNumText, m_selectTutorialController, SelectTutorialController.TutorialDataList.
Referenced by SetDescription.