TitleMainMenuButton
bool TitleMainMenuButton.m_isSelected
Referenced by IsDeselectedUpdate, IsSelectedUpdate, OnDeselected, OnSelected, Start.
CanvasGroup TitleMainMenuButton.m_canvasGroup
Referenced by IsDeselectedUpdate, OnSelected, Start.
BlinkingCanvasGroup TitleMainMenuButton.m_blinkingCanvasGroup
Referenced by OnDeselected, OnSelected, Start.
Image TitleMainMenuButton.m_image
Referenced by IsDeselectedUpdate, OnSelected, Start.
float TitleMainMenuButton.m_deselectedAlpha
Referenced by IsDeselectedUpdate.
Color TitleMainMenuButton.m_deselectedColor
Referenced by IsDeselectedUpdate.
UnityEvent TitleMainMenuButton.m_onSelected
Referenced by OnSelected.
UnityEvent TitleMainMenuButton.m_onDeselected
Referenced by OnDeselected.
UnityEvent TitleMainMenuButton.m_onClick
Referenced by OnClick.
bool TitleMainMenuButton.IsSelected
void TitleMainMenuButton.Start()
References m_blinkingCanvasGroup, m_canvasGroup, m_image, m_isSelected, OnDeselected, OnSelected.
void TitleMainMenuButton.OnSelected()
References m_blinkingCanvasGroup, m_canvasGroup, m_image, m_isSelected, m_onSelected, BlinkingCanvasGroup.StartEasing.
Referenced by IsSelectedUpdate, Start.
void TitleMainMenuButton.OnDeselected()
References BlinkingCanvasGroup.EndEasing, m_blinkingCanvasGroup, m_isSelected, m_onDeselected.
Referenced by IsDeselectedUpdate, Start.
void TitleMainMenuButton.IsSelectedUpdate()
References m_isSelected, OnSelected.
void TitleMainMenuButton.IsDeselectedUpdate()
References m_canvasGroup, m_deselectedAlpha, m_deselectedColor, m_image, m_isSelected, OnDeselected.
void TitleMainMenuButton.OnClick()
References m_onClick.