AnyActionUIController
GameObject AnyActionUIController.m_anyActionUI
Referenced by ChangeStateUI.
TextMeshProUGUI AnyActionUIController.m_anyActionUIText
Referenced by ChangeStateUI.
InputActionButton_ChangeInputActionReference AnyActionUIController.m_inputAction
Referenced by ChangeStateUI.
SerializableDictionary<ActionUIState, AnyActionInfo> AnyActionUIController.m_actionInfoList
Referenced by ChangeStateUI.
ActionUIState AnyActionUIController.m_nowActionState
Referenced by ChangeNowStateUI, ChangeStateUI.
void AnyActionUIController.ChangeNowStateUI()
m_nowActionState に応じたUIを表示する
References ChangeStateUI, m_nowActionState.
Referenced by Start.
void AnyActionUIController.Start()
References ChangeNowStateUI.
void AnyActionUIController.ChangeStateUI(ActionUIState _actionState)
アクション状態を変更する
_actionState
References InputActionButton_ChangeInputActionReference.ChangeInputActionReference, InputActionButton.InputActionReference, m_actionInfoList, m_anyActionUI, m_anyActionUIText, m_inputAction, m_nowActionState.
Referenced by ChangeNowStateUI, ActionUIController.SwitchState.