DrawThrowItemArc
bool DrawThrowItemArc.m_showArc
放物線の描画ON/OFF
Referenced by Update.
int DrawThrowItemArc.segmentCount
放物線を構成する線分の数
Referenced by CreateLineRendererObjects, Update.
float DrawThrowItemArc.predictionTime
放物線を長さ計算するか
Referenced by Update.
Material DrawThrowItemArc.arcMaterial
放物線のMaterial
Referenced by CreateLineRendererObjects, OnMaterialLoaded.
float DrawThrowItemArc.arcWidth
放物線の幅
Referenced by CreateLineRendererObjects.
GameObject DrawThrowItemArc.arcObjectsParent
放物線描画の親オブジェクト
Referenced by CreateLineRendererObjects, OnDestroy, Update.
LineRenderer [] DrawThrowItemArc.lineRenderers
放物線を構成するLineRenderer
Referenced by CreateLineRendererObjects, SetLineRendererPosition, Update.
Vector3 DrawThrowItemArc.startPos
生成開始座標
Referenced by GetArcPositionAtTime.
Vector3 DrawThrowItemArc.throwPower
初速度
Referenced by GetArcPositionAtTime.
bool DrawThrowItemArc.ShowArc
Vector3 DrawThrowItemArc.StartPos
Vector3 DrawThrowItemArc.ThrowPower
void DrawThrowItemArc.Start()
References OnMaterialLoaded.
void DrawThrowItemArc.Update()
References arcObjectsParent, GetArcHitTime, GetArcPositionAtTime, lineRenderers, m_showArc, predictionTime, segmentCount, SetLineRendererPosition, ShowPointer.
Vector3 DrawThrowItemArc.GetArcPositionAtTime(float time)
指定時間に対するアーチの放物線上の座標を返す
time 経過時間 座標
References startPos, throwPower.
Referenced by GetArcHitTime, SetLineRendererPosition, Update.
void DrawThrowItemArc.SetLineRendererPosition(int index, float startTime, float endTime, bool draw=true)
LineRendererの座標を更新
index startTime endTime
References GetArcPositionAtTime, lineRenderers.
Referenced by Update.
void DrawThrowItemArc.CreateLineRendererObjects()
LineRendererオブジェクトを作成
References arcMaterial, arcObjectsParent, arcWidth, lineRenderers, segmentCount.
Referenced by OnMaterialLoaded.
void DrawThrowItemArc.ShowPointer(Vector3 position)
指定座標にマーカーを表示
position
Referenced by Update.
float DrawThrowItemArc.GetArcHitTime(float startTime, float endTime)
2点間の線分で衝突判定し、衝突する時間を返す
衝突した時間(してない場合はfloat.MaxValue)
References GetArcPositionAtTime.
Referenced by Update.
void DrawThrowItemArc.OnMaterialLoaded(AsyncOperationHandle< Material > handle)
References arcMaterial, CreateLineRendererObjects.
Referenced by Start.
void DrawThrowItemArc.OnDestroy()
References arcObjectsParent.