ManagementProvideFoodManager
PocketType ManagementProvideFoodManager.m_pocketType
Referenced by AddProvideFoodList, PublishSoldOutProvideFoodEvent, RemoveProvideFood.
uint ManagementProvideFoodManager.m_maxFoodListCount
Referenced by IsAddList.
List<ProvideFoodData> ManagementProvideFoodManager.m_provideFoodDataList
Referenced by AddProvideFoodList, GetProvideFood, GetRandomFoodData, IsAddedProvideFood, IsAddList, IsCreateAll, RemoveProvideFood, SetProvideFoodControllerData, SoldFood.
PocketType ManagementProvideFoodManager.PocketType
uint ManagementProvideFoodManager.MaxFoodListCount
List<ProvideFoodData> ManagementProvideFoodManager.ProvideFoodDataList
void ManagementProvideFoodManager.SetProvideFoodControllerData(SelectManagementProvideFoodController _controller)
コントローラーを基に提供料理をセットする
References AddProvideFoodList, m_provideFoodDataList.
bool ManagementProvideFoodManager.AddProvideFoodList(FoodID _foodID)
提供料理を追加する
References FoodData.GetProvideNum, IsAddedProvideFood, IsAddList, m_pocketType, m_provideFoodDataList, PublishAddListEvent, PublishChangeProvideFoodEvent.
Referenced by SetProvideFoodControllerData.
void ManagementProvideFoodManager.AddBonusNum(FoodID _foodID, uint _bonusNum=1)
ボーナスを追加
References GetProvideFood.
void ManagementProvideFoodManager.SoldFood(FoodID _id)
提供料理の売り上げ数を加算
References m_provideFoodDataList, PublishChangeProvideFoodEvent.
void ManagementProvideFoodManager.RemoveProvideFood(FoodID _id)
必要素材を取り除く
References m_pocketType, m_provideFoodDataList, PublishChangeProvideFoodEvent, PublishRemoveListEvent, PublishSoldOutProvideFoodEvent, FoodData.RemoveProvideNeedIngredient.
ProvideFoodData ManagementProvideFoodManager.GetProvideFood(FoodID _foodID)
引数提供料理を取得する 無ければNullを返す
References m_provideFoodDataList.
Referenced by AddBonusNum.
FoodData ManagementProvideFoodManager.GetRandomFoodData()
リストからランダムで料理データを取得 提供できるものが無ければnullを返す
References BaseManager< T >.instance, m_provideFoodDataList.
bool ManagementProvideFoodManager.IsCreateAll()
提供料理が作成可能かどうか確認する
References m_provideFoodDataList.
bool ManagementProvideFoodManager.IsAddList()
提供料理を追加できるか確認
References m_maxFoodListCount, m_provideFoodDataList.
Referenced by AddProvideFoodList.
bool ManagementProvideFoodManager.IsAddedProvideFood(FoodID _foodID)
追加済みかどうか確認する
References m_provideFoodDataList.
Referenced by AddProvideFoodList.
void ManagementProvideFoodManager.PublishSoldOutProvideFoodEvent(ProvideFoodData _data)
References ProvideFoodData.FoodID, FoodData.IsProvide, m_pocketType.
Referenced by RemoveProvideFood.
void ManagementProvideFoodManager.PublishAddListEvent(ProvideFoodData _data)
Referenced by AddProvideFoodList.
void ManagementProvideFoodManager.PublishRemoveListEvent(ProvideFoodData _data)
Referenced by RemoveProvideFood.
void ManagementProvideFoodManager.PublishChangeProvideFoodEvent()
Referenced by AddProvideFoodList, RemoveProvideFood, SoldFood.