ActionItemControllerWindow
CreateActionItemSlotList ActionItemControllerWindow.m_createSlotList
Referenced by DeleteSprite, OnInitialize, OnUpdate, SelectItemAction, SetItemInfomation.
SelectUIActionWindowController ActionItemControllerWindow.m_selectUIController
Referenced by CheckNullUIgameObjList, DeleteSprite, OnUpdate, SelectItemAction.
ChangeScrollViewPosition ActionItemControllerWindow.m_changeScrollViewPosition
Referenced by OnUpdate.
GameObject ActionItemControllerWindow.m_content
CreateActionItemSlotList ActionItemControllerWindow.CreateSlotList
Referenced by PutItemInstance.Craft.
GameObject ActionItemControllerWindow.ContentTrans
override async UniTask ActionItemControllerWindow.OnInitialize()
References m_createSlotList, BaseCreateSlotList.OnInitialize.
override async UniTask ActionItemControllerWindow.OnUpdate()
References CheckNullUIgameObjList, BaseCreateSlotList.CreateSlot, DeleteSprite, m_changeScrollViewPosition, m_createSlotList, BaseWindow.m_input, m_selectUIController, SelectUIActionWindowController.OnLateUpdate, SelectUIActionWindowController.OnUpdate, ChangeScrollViewPosition.OnUpdateEveryTime, SelectItemAction, SetItemInfomation.
void ActionItemControllerWindow.SetItemInfomation()
References BaseManager< T >.instance, m_createSlotList, BaseCreateSlotList.SlotList.
Referenced by OnUpdate.
void ActionItemControllerWindow.DeleteSprite()
References SelectUIActionWindowController.CheckWithChange, BasePocketItemDataController.GetItemNum, InventoryManager.instance, m_createSlotList, m_selectUIController, SelectUIController.SetUIActionWindowGameObject, BaseCreateSlotList.SlotList, SelectUIController.UIList.
Referenced by OnUpdate.
bool ActionItemControllerWindow.CheckNullUIgameObjList()
References m_selectUIController, SelectUIController.UIList.
Referenced by OnUpdate.
void ActionItemControllerWindow.SelectItemAction()
References SelectUIController.CurrentSelectUI, PlayerParameters.HideWeapon, BaseManager< T >.instance, SelectUIActionWindowController.IsPut, SelectUIActionWindowController.IsThrow, SelectUIActionWindowController.IsUse, m_createSlotList, m_selectUIController, player, BaseCreateSlotList.SlotList, SelectUIController.UIList.
Referenced by OnUpdate.