SelectManagementProvideFoodController
List<FoodID> SelectManagementProvideFoodController.m_provideFoodIDList
Referenced by AddProvideFoodID, IsAddedProvideFood, IsAddList, RemoveProvideFoodID.
bool SelectManagementProvideFoodController.m_isListChange
Referenced by AddProvideFoodID, OnLateUpdate, RemoveProvideFoodID.
List<FoodID> SelectManagementProvideFoodController.ProvideFoodIDList
Referenced by CreateManagementProvideFoodControllerSlotList.GetCreateList, StartManagementInputActionButton.IsPress.
bool SelectManagementProvideFoodController.IsListChange
Referenced by CurrentSelectManagementProvideFoodSlotData.Check, SelectProvideFoodMenuUI.CreateSlot.
void SelectManagementProvideFoodController.OnLateUpdate()
References m_isListChange.
Referenced by ManagementSelectProvideFoodWindow.OnUpdate.
void SelectManagementProvideFoodController.AddProvideFoodID(FoodID _id)
提供予定料理を追加
References IsAddedProvideFood, IsAddList, m_isListChange, m_provideFoodIDList.
Referenced by SelectProvideFoodUI.SetProvideFood.
void SelectManagementProvideFoodController.RemoveProvideFoodID(FoodID _id)
提供予定料理を取り除く
References m_isListChange, m_provideFoodIDList.
Referenced by SelectProvideFoodUI.SetProvideFood.
bool SelectManagementProvideFoodController.IsAddList()
提供料理を追加できるか確認
References BaseManager< T >.instance, m_provideFoodIDList.
Referenced by AddProvideFoodID, CurrentSelectManagementProvideFoodSlotData.SetSlot.
bool SelectManagementProvideFoodController.IsAddedProvideFood(FoodID _foodID)
追加済みかどうか確認する
References m_provideFoodIDList.
Referenced by AddProvideFoodID, ManagementProvideFoodControllerSlotData.Check, SelectProvideFoodUI.SetProvideFood, CurrentSelectManagementProvideFoodSlotData.SetSlot.
void SelectManagementProvideFoodController.SetManagementProvideFoodData()
提供料理をマネージャーにセットする
References BaseManager< T >.instance.
Referenced by ManagementSelectProvideFoodWindow.Transition.