HPBarController
float HPBarController.m_value
Referenced by SetHealthText, SetHealthValue, Update, UpdateFillAmount.
bool HPBarController.m_isCalc
Referenced by SetHealthValue.
float HPBarController.m_maxHealth
Referenced by SetHealth, SetHealthText, SetHealthValue.
Image HPBarController.m_image
Referenced by Start, UpdateFillAmount.
TextMeshProUGUI HPBarController.m_text
Referenced by SetHealthText.
List<HPBarColor> HPBarController.m_barColorList
Referenced by UpdateFillAmount.
ArborFSM HPBarController.m_arborFSM
Referenced by Start, Update.
bool HPBarController.m_isShow
Referenced by ShowHP, Update.
bool HPBarController.IsCalc
bool HPBarController.IsSetHealthValue
void HPBarController.SetHealth(float _current, float _max)
References m_maxHealth, SetHealthValue.
Referenced by BPBarPresenter.BarSetting, HPBarPresenter.BarSetting.
void HPBarController.SetHealthValue(float _currentHealth)
References m_isCalc, m_maxHealth, m_value, SetHealthText, UpdateFillAmount.
Referenced by BPBarPresenter.BarUpdate, HPBarPresenter.BarUpdate, SummonBarPresenter.BarUpdate, SummonBarPresenter.InitSetting, SetHealth.
void HPBarController.Update()
References CharacterCore.InputType, m_arborFSM, m_isShow, m_value, IMetaAI< T >.ObjectList, ShowHP.
void HPBarController.Start()
References m_arborFSM, m_image.
void ISerializationCallbackReceiver. HPBarController.OnBeforeSerialize()
インスペクターで値を変更した時に呼ばれる（保存前）
References SetHealthText, UpdateFillAmount.
void ISerializationCallbackReceiver. HPBarController.OnAfterDeserialize()
インスペクターでの値の変更後、保存された値を読み込む際に呼ばれる
void HPBarController.UpdateFillAmount()
References m_barColorList, m_image, m_value.
Referenced by OnBeforeSerialize, SetHealthValue.
void HPBarController.SetHealthText()
References m_maxHealth, m_text, m_value.
Referenced by OnBeforeSerialize, SetHealthValue.
void HPBarController.ShowHP(bool _isShow)
References m_isShow.
Referenced by Update.