CustomerCanvas
ImageProgressController CustomerCanvas.m_imageProgressController
怒りゲージ表現管理スクリプト
Referenced by Angry.
Image CustomerCanvas.m_foodImage
求めている料理の画像
Referenced by SetFoodImage.
CustomerData CustomerCanvas.m_targetCustomerData
客情報
Referenced by Angry, Check, SetFoodImage, Start.
CustomerData CustomerCanvas.TargetCustomerData
void CustomerCanvas.Start()
References m_targetCustomerData, SetFoodImage.
void CustomerCanvas.Update()
References Angry, Check.
void CustomerCanvas.SetFoodImage()
References OrderFoodData.FoodID, BaseManager< T >.instance, m_foodImage, m_targetCustomerData, CustomerData.TargetOrderFoodData.
Referenced by Start.
void CustomerCanvas.Angry()
怒りゲージの表示情報を更新する
References CustomerData.AngryCount, CustomerData.AngryTime, m_imageProgressController, m_targetCustomerData.
Referenced by Update.
void CustomerCanvas.Check()
ターゲットの客が料理を待っている状態( CustomerState.WaitFood )でなければ削除する
References CustomerData.CurrentCustomerState, m_targetCustomerData.
Referenced by Update.