ChangeScrollViewPosition
ChangeScrollViewPositionType
SelectUIController ChangeScrollViewPosition.m_selectUIController
Referenced by OnUpdate, OnUpdateEveryTime.
GridLayoutGroup ChangeScrollViewPosition.m_gridLayoutGroup
Referenced by Edge.
ScrollRect ChangeScrollViewPosition.m_scrollRect
Referenced by ChangePosEdge, DoMove, Scroll.
RectTransform ChangeScrollViewPosition.m_scrollRectTransform
Referenced by Center, ChangePosEdge, Edge, Scroll.
ChangeScrollViewPositionType ChangeScrollViewPosition.m_type
Referenced by Scroll.
bool ChangeScrollViewPosition.m_isVertical
Referenced by Center, Edge.
bool ChangeScrollViewPosition.m_isHorizontal
Referenced by Center, Edge.
bool ChangeScrollViewPosition.m_isStop
Referenced by DoMove.
void ChangeScrollViewPosition.OnUpdate()
実行処理
References SelectUIController.CurrentSelectUI, SelectUIController.IsSelectChangeFlg, m_selectUIController, Scroll.
Referenced by SelectProvideFoodUI.OnSelectUpdate, ActionItemWindow.OnUpdate, InventoryWindow.OnUpdate, ManagementResultWindow.OnUpdate, NewItemWindow.OnUpdate, RecipeWindow.OnUpdate, SelectProvideFoodMenuUI.OnUpdate.
void ChangeScrollViewPosition.OnUpdateEveryTime()
References SelectUIController.CurrentSelectUI, m_selectUIController, Scroll.
Referenced by ActionItemControllerWindow.OnUpdate.
void ChangeScrollViewPosition.ChangePosEdge(GameObject _object)
References Center, DoMove, m_scrollRect, m_scrollRectTransform.
void ChangeScrollViewPosition.Scroll(GameObject _ui)
References Center, DoMove, Edge, m_scrollRect, m_scrollRectTransform, m_type.
Referenced by OnUpdate, OnUpdateEveryTime.
bool ChangeScrollViewPosition.Center(RectTransform _objectTransform, ref Vector2 _dist)
真ん中に座標を変更する
References m_isHorizontal, m_isVertical, m_scrollRectTransform.
bool ChangeScrollViewPosition.Edge(RectTransform _objectTransform, ref Vector2 _dist)
端に座標を変更する
References m_gridLayoutGroup, m_isHorizontal, m_isVertical, m_scrollRectTransform.
void ChangeScrollViewPosition.DoMove(Vector2 _goalPos)
References m_isStop, m_scrollRect.
Referenced by ChangePosEdge, Scroll.