SelectStageController
StageID SelectStageController.m_currentSelectStageID
Referenced by Back, GetCurrentSelectStageData, IsGoBack, IsGoNext, Next.
bool SelectStageController.m_isSelectChangeFlg
Referenced by Back, Next, OnLateUpdate.
InputActionButton SelectStageController.m_nextInputActionButton
Referenced by Next.
InputActionButton SelectStageController.m_backInputActionButton
Referenced by Back.
InputActionButton SelectStageController.m_startInputActionButton
Referenced by IsStart.
StageID SelectStageController.CurrentSelectStageID
Referenced by ChangeSelectStageDescription.ChangeDescription.
bool SelectStageController.IsSelectChangeFlg
現在選択しているステージが変更されたかどうか確認する、読み取り専用プロパティ
<return> true - 変更された false - 変更されていない
Referenced by ChangeSelectStageDescription.IsChangeDescription.
void SelectStageController.OnUpdate()
References Select.
Referenced by SelectStageWindow.OnUpdate.
void SelectStageController.OnLateUpdate()
References m_isSelectChangeFlg.
Referenced by SelectStageWindow.OnUpdate.
StageData SelectStageController.GetCurrentSelectStageData()
References BaseManager< T >.instance, m_currentSelectStageID.
Referenced by SelectStageWindow.Transion.
bool SelectStageController.IsStart()
References IsGoStart, InputActionButton.IsInputActionTrriger, m_startInputActionButton.
Referenced by SelectStageWindow.Transion.
bool SelectStageController.IsGoNext()
References m_currentSelectStageID.
Referenced by SelectStageInputActionButton.IsPress, Next.
bool SelectStageController.IsGoBack()
References m_currentSelectStageID.
Referenced by Back, SelectStageInputActionButton.IsPress.
bool SelectStageController.IsGoStart()
Referenced by SelectStageInputActionButton.IsPress, IsStart.
void SelectStageController.Select()
References Back, Next.
Referenced by OnUpdate.
void SelectStageController.Next()
References IsGoNext, InputActionButton.IsInputActionTrriger, m_currentSelectStageID, m_isSelectChangeFlg, m_nextInputActionButton.
Referenced by Select.
void SelectStageController.Back()
References IsGoBack, InputActionButton.IsInputActionTrriger, m_backInputActionButton, m_currentSelectStageID, m_isSelectChangeFlg.
Referenced by Select.