BlindAnimator
CanvasGroup BlindAnimator.m_cutInCanvas
Referenced by InSequence, OutSequence.
RectTransform BlindAnimator.m_rectTrans
Referenced by InSequence, OutSequence.
Material BlindAnimator.m_material
Referenced by CutIn, In, OutSequence, Start.
int BlindAnimator.m_blindID
Referenced by CutIn, In, OutSequence, Start.
float BlindAnimator.m_cutInFadeDuration
Referenced by InSequence.
float BlindAnimator.m_cutInDisplayDuration
Referenced by InSequence.
float BlindAnimator.m_blindFadeDuration
Referenced by OutSequence.
float BlindAnimator.m_cutInFadeOutDelay
Referenced by OutSequence.
float BlindAnimator.m_cutInFadeOutDuration
Referenced by OutSequence.
float BlindAnimator.m_initialPositionX
Referenced by OutSequence.
float BlindAnimator.m_finalPositionX
Referenced by InSequence.
string BlindAnimator.m_propertyName
Referenced by Start.
float BlindAnimator.m_startUpValue
Referenced by CutIn, In, Start.
UniTask BlindAnimator.Method()
References CutIn.
UniTask BlindAnimator.INN()
References In.
UniTask BlindAnimator.OUTT()
References Out.
void BlindAnimator.Start()
References m_blindID, m_material, m_propertyName, m_startUpValue.
UniTask BlindAnimator.InSequence(Sequence seq)
References m_cutInCanvas, m_cutInDisplayDuration, m_cutInFadeDuration, m_finalPositionX, m_rectTrans.
Referenced by CutIn, In.
UniTask BlindAnimator.OutSequence(Sequence seq)
References m_blindFadeDuration, m_blindID, m_cutInCanvas, m_cutInFadeOutDelay, m_cutInFadeOutDuration, m_initialPositionX, m_material, m_rectTrans.
Referenced by CutIn, Out.
UniTask BlindAnimator.In()
References InSequence, m_blindID, m_material, m_startUpValue.
Referenced by BlindTransitionDirectorBehaviour.In, INN.
UniTask BlindAnimator.Out()
References OutSequence.
Referenced by BlindTransitionDirectorBehaviour.Out, OUTT.
UniTask BlindAnimator.CutIn()
References InSequence, m_blindID, m_material, m_startUpValue, OutSequence.
Referenced by BlindTransitionDirectorBehaviour.CutIn, Method.