BaseManagementStateUpdate
ManagementState BaseManagementStateUpdate.m_managementState
Referenced by GetState.
ManagementState BaseManagementStateUpdate.m_nextManagementState
Referenced by ManagementStateUpdate_Result.CreateToUpdateWindow, ManagementStateUpdate_Standby.CreateToUpdateWindow, GetNextState, ManagementStateUpdate_End.OnUpdate, ManagementStateUpdate_Start.OnUpdate, ManagementStateUpdate_Update.OnUpdate, SetEnd.
override int BaseManagementStateUpdate.GetState()
References m_managementState.
override int BaseManagementStateUpdate.GetNextState()
References m_nextManagementState.
virtual void BaseManagementStateUpdate.SetEnd(ManagementState _state)
ステート処理を終了する
References BaseGameStateUpdate.m_isEnd, m_nextManagementState.
Referenced by ManagementStateUpdate_Result.CreateToUpdateWindow, ManagementStateUpdate_Standby.CreateToUpdateWindow, ManagementStateUpdate_End.OnUpdate, ManagementStateUpdate_Start.OnUpdate, ManagementStateUpdate_Update.OnUpdate.