JumpingUI
RectTransform JumpingUI.m_rectTransform
Referenced by OnValidate, Start, StartJumpAnimation.
Vector2 JumpingUI.m_originalPosition
Referenced by OnValidate, StartJumpAnimation.
Tween JumpingUI.m_jumpTween
Referenced by StartJumpAnimation, StopAnimation.
float JumpingUI.m_jumpHeight
Referenced by StartJumpAnimation.
float JumpingUI.m_jumpDuration
Referenced by StartJumpAnimation.
bool JumpingUI.isTweenInitialized
Referenced by Start.
void JumpingUI.Start()
References isTweenInitialized, m_rectTransform, StartJumpAnimation.
void JumpingUI.StartJumpAnimation()
References m_jumpDuration, m_jumpHeight, m_jumpTween, m_originalPosition, m_rectTransform, StopAnimation.
Referenced by OnEnable, OnValidate, Start.
void JumpingUI.OnValidate()
References m_originalPosition, m_rectTransform, StartJumpAnimation.
void JumpingUI.OnDestroy()
References StopAnimation.
void JumpingUI.OnDisable()
References StopAnimation.
void JumpingUI.OnEnable()
References StartJumpAnimation.
void JumpingUI.StopAnimation()
References m_jumpTween.
Referenced by OnDestroy, OnDisable, StartJumpAnimation.