ItemSlotData
PocketType ItemSlotData.m_pocketType
Referenced by ProvideFoodRecipeSlotData.CheckCreate, RecipeItemSlotData.CheckCreate, CreateFoodNeedIngredientSlotData.SetComparisonNumText, NeedIngredientSlotData.SetComparisonNumText, FoodSlotData.SetCreateNumText, SetItemNum, SetItemSlotData, ProvideFoodRecipeSlotData.SetProvideNumText, CurrentSelectManagementProvideFoodSlotData.SetSlot, CurrentSelectManagementProvideFoodSlotData.Start, ManagementProvideFoodControllerSlotData.Start, ManagementProvideFoodSlotData.Start, ProvideFoodRecipeSlotData.Start, ProvideFoodUseIngredientSlotData.Start.
Image ItemSlotData.m_itemImage
Referenced by SetItemImage.
TextMeshProUGUI ItemSlotData.m_nameText
Referenced by SetItemName.
TextMeshProUGUI ItemSlotData.m_descriptionText
Referenced by SetDescription.
Image ItemSlotData.m_typeImage
Referenced by SetItemTypeImage.
TextMeshProUGUI ItemSlotData.m_numText
Referenced by SetItemNum.
Image ItemSlotData.m_conditionImage
Referenced by SetConditionImage.
Image ItemSlotData.m_conditionBackColor
Referenced by SetConditionBackColor.
float ItemSlotData.m_conditionBackAlpha
Referenced by SetConditionBackColor.
ItemTypeID ItemSlotData.m_itemTypeID
Referenced by CreateFoodNeedIngredientSlotData.SetComparisonNumText, SetItemNum, SetItemSlotData, SetItemTypeImage, ManagementProvideFoodSlotData.Start.
uint ItemSlotData.m_itemID
Referenced by ManagementProvideFoodControllerSlotData.Check, ProvideFoodRecipeSlotData.CheckCreate, RecipeItemSlotData.CheckCreate, FoodSlotData.CreateNeedIngredient, CreateFoodNeedIngredientSlotData.SetComparisonNumText, SetItemNum, SetItemSlotData, ManagementProvideFoodSlotData.SetProvideFoodData, ManagementProvideFoodSlotData.Start, SoldOutProvideFoodSlotData.Start.
PocketType ItemSlotData.PocketType
virtual ItemTypeID ItemSlotData.ItemTypeID
Referenced by ChangeItemDescription.ChangeDesctiptionSelectUI.
virtual uint ItemSlotData.ItemID
Referenced by ChangeItemDescription.ChangeDesctiptionSelectUI.
virtual void ItemSlotData.SetItemSlotData(BaseItemData _itemData, PocketType _pocketType)
References BaseItemData.ItemDescriptionText, BaseItemData.ItemID, BaseItemData.ItemName, BaseItemData.ItemSprite, BaseItemData.ItemTypeID, m_itemID, m_itemTypeID, m_pocketType, SetConditionBackColor, SetConditionImage, SetDescription, SetItemImage, SetItemName, SetItemNum, SetItemTypeImage.
virtual void ItemSlotData.InitializeSlotData()
References SetConditionBackColor, SetConditionImage, SetDescription, SetItemImage, SetItemName, SetItemNum, SetItemTypeImage.
virtual void ItemSlotData.SetItemImage(Sprite _sprite, bool _active=true)
References m_itemImage.
Referenced by InitializeSlotData, SetItemSlotData.
virtual void ItemSlotData.SetItemName(string _nameText, bool _active=true)
References m_nameText.
Referenced by InitializeSlotData, SetItemSlotData.
virtual void ItemSlotData.SetDescription(string _description, bool _active=true)
References m_descriptionText.
Referenced by InitializeSlotData, SetItemSlotData.
virtual void ItemSlotData.SetItemNum(bool _active=true)
References m_itemID, m_itemTypeID, m_numText, m_pocketType.
Referenced by InitializeSlotData, SetItemSlotData.
virtual void ItemSlotData.SetItemTypeImage(bool _active=true)
References BaseManager< T >.instance, m_itemTypeID, m_typeImage.
Referenced by InitializeSlotData, SetItemSlotData.
virtual void ItemSlotData.SetConditionImage(BaseItemData _itemData, bool _active=true)
References BaseEdibleItem.ConditionID, BaseManager< T >.instance, m_conditionImage.
Referenced by InitializeSlotData, SetItemSlotData.
virtual void ItemSlotData.SetConditionBackColor(BaseItemData _itemData, bool _active=true)
References BaseEdibleItem.ConditionID, BaseManager< T >.instance, m_conditionBackAlpha, m_conditionBackColor.
Referenced by InitializeSlotData, SetItemSlotData.