ChangeFoodItemDescription
TextMeshProUGUI ChangeFoodItemDescription.m_priceText
Referenced by SetActiveList, SetPriceText.
List<GameObject> ChangeFoodItemDescription.m_priceTextList
Referenced by SetActiveList.
TextMeshProUGUI ChangeFoodItemDescription.m_createNumText
Referenced by SetActiveList, SetCreateNumText.
List<GameObject> ChangeFoodItemDescription.m_createNumTextList
Referenced by SetActiveList.
CreateNeedIngredientSlot ChangeFoodItemDescription.m_createNeedIngredientSlot
Referenced by CreateNeedIngredientSlot.
override void ChangeFoodItemDescription.SetDescription(BaseItemData _itemData)
References CreateNeedIngredientSlot, SetCreateNumText, SetPriceText.
override void ChangeFoodItemDescription.InitDescription()
References SetCreateNumText, SetPriceText.
override void ChangeFoodItemDescription.SetActiveList()
References m_createNumText, m_createNumTextList, m_priceText, m_priceTextList.
void ChangeFoodItemDescription.CreateNeedIngredientSlot(BaseItemData _itemData)
References BaseCreateSlotList.CreateSlot, BaseItemData.ItemID, m_createNeedIngredientSlot, CreateNeedIngredientSlot.SetFoodID.
Referenced by SetDescription.
void ChangeFoodItemDescription.SetPriceText(BaseItemData _data, bool _active=true)
References m_priceText, FoodData.Price.
Referenced by InitDescription, SetDescription.
void ChangeFoodItemDescription.SetCreateNumText(BaseItemData _data, bool _active=true)
References FoodData.GetCreateNum, BaseItemData.ItemID, m_createNumText, ChangeItemDescription.m_pocketType.
Referenced by InitDescription, SetDescription.