PlayerInputManager
PlayerInput PlayerInputManager.m_playerInput
Referenced by Awake.
InputActionMap PlayerInputManager.m_playerInputActionMap
Referenced by Awake, GetInputActionMap.
InputActionMap PlayerInputManager.m_cameraInputActionMap
Referenced by Awake, GetInputActionMap.
InputActionMap PlayerInputManager.m_uiInputActionMap
Referenced by Awake, GetInputActionMap.
InputActionButtonDataBase PlayerInputManager.m_inputActionButtonDataBase
ReactiveProperty<DeviceTypes> PlayerInputManager.m_currenrDevice
InputAction PlayerInputManager.m_detrctionKeyboard
Referenced by ObservationDevice.
InputAction PlayerInputManager.m_detrctionXBOX
Referenced by ObservationDevice.
InputAction PlayerInputManager.m_detrctionPlayStation
Referenced by ObservationDevice.
InputActionButtonDataBase PlayerInputManager.InputActionButtonDataBase
System.IObservable<DeviceTypes> PlayerInputManager.CurrentDevice
DeviceTypes PlayerInputManager.CurrentDeviceTypes
void PlayerInputManager.Awake()
References m_cameraInputActionMap, m_playerInput, m_playerInputActionMap, m_uiInputActionMap.
void PlayerInputManager.Update()
References ObservationDevice.
void PlayerInputManager.ObservationDevice()
References m_detrctionKeyboard, m_detrctionPlayStation, m_detrctionXBOX.
Referenced by Update.
InputActionMap PlayerInputManager.GetInputActionMap(InputActionMapTypes _type)
引数InputActionMapを取得
References m_cameraInputActionMap, m_playerInputActionMap, m_uiInputActionMap.
Referenced by GetInputAction.
InputAction PlayerInputManager.GetInputAction(InputActionMapTypes _type, string _action)
References GetInputActionMap.
Referenced by IsInputActionPressed, IsInputActionTrigger, IsInputActionWasPressed, IsInputActionWasReleased.
bool PlayerInputManager.IsInputActionTrigger(InputActionMapTypes _type, string _action)
引数InputActionのトリガー 押された1フレームのみtrueを返す
References GetInputAction.
bool PlayerInputManager.IsInputActionWasPressed(InputActionMapTypes _type, string _action)
引数InputActionが押されたか 押された1フレームのみtrueを返す
References GetInputAction.
bool PlayerInputManager.IsInputActionPressed(InputActionMapTypes _type, string _action)
引数InputActionが押され続けているか
References GetInputAction.
bool PlayerInputManager.IsInputActionWasReleased(InputActionMapTypes _type, string _action)
引数InputActionが離されたか 離された1フレームのみtrueを返す
References GetInputAction.