PressKeyEffectController
Image PressKeyEffectController.m_image
Referenced by Play, Start.
Material PressKeyEffectController.m_material
Referenced by Start.
float PressKeyEffectController.m_duration
Referenced by Play.
Vector3 PressKeyEffectController.m_minScale
Referenced by End, Play.
Vector3 PressKeyEffectController.m_maxScale
Referenced by Play.
bool PressKeyEffectController.m_playing
Referenced by End, Play.
void PressKeyEffectController.Start()
References End, m_image, m_material.
void PressKeyEffectController.End()
References m_minScale, m_playing.
Referenced by Play, Start.
void PressKeyEffectController.Play()
References End, m_duration, m_image, m_maxScale, m_minScale, m_playing.
Referenced by PlayPressKeyEffect.Update.