BaseStaffCalculator
FlexibleStaffDataVariable BaseStaffCalculator.m_flexibleStaffDataVariable
Referenced by GetStaffData.
OutputSlotVector3 BaseStaffCalculator.m_outputPos
Referenced by CalcCarryPosStaff.OnCalculate, CalcDefaultPosStaff.OnCalculate, CalcOrderFoodPositionStaff.OnCalculate, CalcRotateBeenTargetObjectStaff.OnCalculate, CalcTargetOrderFoodPosStaff.OnCalculate.
StaffData BaseStaffCalculator.GetStaffData()
スタッフ情報が存在するかのチェック
References m_flexibleStaffDataVariable.
Referenced by CalcCarryPosStaff.OnCalculate, CalcDefaultPosStaff.OnCalculate, CalcOrderFoodPositionStaff.OnCalculate, CalcRotateBeenTargetObjectStaff.OnCalculate, CalcTargetOrderFoodPosStaff.OnCalculate.
GameObject BaseStaffCalculator.GetRootGameObject()