AppearObject
List<GameObject> AppearObject.m_objectList
Referenced by CreateObject.
float AppearObject.m_appearDelay
Referenced by Appear.
int AppearObject.m_maxAppear
Referenced by Appear.
List<GameObject> AppearObject.m_createObjectList
Referenced by Appear, CreateObject.
float AppearObject.m_appearDelayCount
Referenced by Appear.
void AppearObject.Update()
References Appear.
void AppearObject.Appear()
References m_appearDelay, m_appearDelayCount, m_createObjectList, m_maxAppear, UpdateCreate.
Referenced by Update.
virtual void AppearObject.UpdateCreate()
References CreateObject.
Referenced by Appear.
GameObject AppearObject.CreateObject()
References m_createObjectList, m_objectList.
Referenced by AppearCustomer.UpdateCreate, UpdateCreate.