ChangeSelectStageDescription
SelectStageController ChangeSelectStageDescription.m_selectStageController
Referenced by ChangeDescription, IsChangeDescription.
Image ChangeSelectStageDescription.m_stageImage
Referenced by SetImage.
TextMeshProUGUI ChangeSelectStageDescription.m_stageNameTextMeshProUGUI
Referenced by SetStageNameText.
TextMeshProUGUI ChangeSelectStageDescription.m_descriptionTextMeshProUGUI
Referenced by SetDescriptionText.
virtual void ChangeSelectStageDescription.OnInitialize()
References ChangeDescription.
Referenced by SelectStageWindow.OnInitialize.
virtual void ChangeSelectStageDescription.OnUpdate()
References ChangeDescription, IsChangeDescription.
Referenced by SelectStageWindow.OnUpdate.
bool ChangeSelectStageDescription.IsChangeDescription()
References SelectStageController.IsSelectChangeFlg, m_selectStageController.
Referenced by OnUpdate.
void ChangeSelectStageDescription.ChangeDescription()
References SelectStageController.CurrentSelectStageID, BaseManager< T >.instance, m_selectStageController, SetDescription.
Referenced by OnInitialize, OnUpdate.
void ChangeSelectStageDescription.SetDescription(StageData _data)
References SetDescriptionText, SetImage, SetStageNameText.
Referenced by ChangeDescription.
void ChangeSelectStageDescription.SetStageNameText(StageData _data)
References m_stageNameTextMeshProUGUI, StageData.StageNameText.
Referenced by SetDescription.
void ChangeSelectStageDescription.SetImage(StageData _data)
References m_stageImage, StageData.StageSprite.
Referenced by SetDescription.
void ChangeSelectStageDescription.SetDescriptionText(StageData _data)
References m_descriptionTextMeshProUGUI, StageData.StageDescriptionText.
Referenced by SetDescription.