SelectUseItemWindow
SelectUIController SelectUseItemWindow.m_selectUIController
Referenced by AddButton, CheckPressSelectUseItemButton, OnUpdate.
GameObject SelectUseItemWindow.m_parentUI
Referenced by AddButton.
GameObject SelectUseItemWindow.m_button
Referenced by AddButton.
SelectUseItemID SelectUseItemWindow.m_currentSelectUseItemID
Referenced by CheckPressSelectUseItemButton, OnUpdate.
void SelectUseItemWindow.EditActionWindow(ItemTypeID _typeID, uint _id)
// 選択ウィンドウ(アクションアイテムウィンドウ版)作成
References EditSelectionWindowforActionWindow_Food, EditSelectionWindowforActionWindow_Ingredient, BaseManager< T >.instance.
Referenced by SetData.
void SelectUseItemWindow.EditSelectionWindowforActionWindow_Ingredient(BaseItemData _itemData)
References AddButton.
Referenced by EditActionWindow.
void SelectUseItemWindow.EditSelectionWindowforActionWindow_Food(BaseItemData _itemData)
References AddButton.
Referenced by EditActionWindow.
void SelectUseItemWindow.EditInventoryWindow(ItemTypeID _typeID, uint _id)
// 選択ウィンドウ(インベントリアイテムウィンドウ版)作成
References EditSelectionWindowforInventoryWindow_Food, EditSelectionWindowforInventoryWindow_Ingredient, BaseManager< T >.instance.
Referenced by SetData.
void SelectUseItemWindow.EditSelectionWindowforInventoryWindow_Ingredient(BaseItemData _itemData)
References AddButton.
Referenced by EditInventoryWindow.
void SelectUseItemWindow.EditSelectionWindowforInventoryWindow_Food(BaseItemData _itemData)
References AddButton.
Referenced by EditInventoryWindow.
bool SelectUseItemWindow.CheckPressSelectUseItemButton()
References SelectUIController.CurrentSelectUI, SelectUseItemButton.ID, SelectUIController.IsPress, m_currentSelectUseItemID, m_selectUIController.
Referenced by OnUpdate.
void SelectUseItemWindow.AddButton(SelectUseItemID _id, bool _active, string _text)
References SelectUIController.AddUI, m_button, m_parentUI, m_selectUIController, SelectUseItemButton.SetData.
Referenced by EditSelectionWindowforActionWindow_Food, EditSelectionWindowforActionWindow_Ingredient, EditSelectionWindowforInventoryWindow_Food, EditSelectionWindowforInventoryWindow_Ingredient.
void SelectUseItemWindow.SetData(SelectUseItemWindowType _windowType, ItemTypeID _typeID, uint _id)
References EditActionWindow, EditInventoryWindow.
new async UniTask< SelectUseItemID > SelectUseItemWindow.OnUpdate()
References CheckPressSelectUseItemButton, BaseManager< T >.instance, m_currentSelectUseItemID, m_selectUIController, SelectUIController.OnLateUpdate, SelectUIController.OnUpdate.