CurrentSelectManagementProvideFoodSlotData
SelectManagementProvideFoodController CurrentSelectManagementProvideFoodSlotData.m_managementProvideFoodController
Referenced by Check, SetSlot.
SelectUIController CurrentSelectManagementProvideFoodSlotData.m_recipeSelectUIController
Referenced by Check, InitSlot, SetSlot.
CanvasGroup CurrentSelectManagementProvideFoodSlotData.m_canvasGroup
Referenced by InitSlot, SetSlot.
float CurrentSelectManagementProvideFoodSlotData.m_alpha
Referenced by SetSlot.
Color CurrentSelectManagementProvideFoodSlotData.m_possibleColor
Referenced by SetColor.
Color CurrentSelectManagementProvideFoodSlotData.m_inpossibleColor
Referenced by SetColor.
List<TextMeshProUGUI> CurrentSelectManagementProvideFoodSlotData.m_colorTextList
Referenced by SetColor.
void CurrentSelectManagementProvideFoodSlotData.Start()
References BaseManager< T >.instance, ItemSlotData.m_pocketType.
void CurrentSelectManagementProvideFoodSlotData.OnUpdate()
References Check.
Referenced by SelectProvideFoodMenuUI.OnUpdate.
void CurrentSelectManagementProvideFoodSlotData.Check()
References InitSlot, SelectManagementProvideFoodController.IsListChange, SelectUIController.IsSelectChangeFlg, m_managementProvideFoodController, m_recipeSelectUIController, SetSlot.
Referenced by OnUpdate.
void CurrentSelectManagementProvideFoodSlotData.InitSlot()
References m_canvasGroup, m_recipeSelectUIController.
Referenced by Check.
void CurrentSelectManagementProvideFoodSlotData.SetSlot()
References SelectUIController.CurrentSelectUI, BaseManager< T >.instance, SelectManagementProvideFoodController.IsAddedProvideFood, SelectManagementProvideFoodController.IsAddList, m_alpha, m_canvasGroup, m_managementProvideFoodController, ItemSlotData.m_pocketType, m_recipeSelectUIController, SetColor, FoodSlotData.SetItemSlotData.
Referenced by Check.
void CurrentSelectManagementProvideFoodSlotData.SetColor(RecipeItemSlotData _slotData)
References RecipeItemSlotData.IsCreate, m_colorTextList, m_inpossibleColor, m_possibleColor.
Referenced by SetSlot.