GenerateCleaningEvent
GameObject GenerateCleaningEvent.m_dirtPrefab
汚れのプレハブ
todo上甲 汚れの種類追加? 必要かは不明
Referenced by CreateDirt.
float GenerateCleaningEvent.ｍ_randomRange
座標からのずれる範囲
Referenced by CreateDirt, SetRandomRange.
float GenerateCleaningEvent.m_endTime
Referenced by CountEndTime.
float GenerateCleaningEvent.m_currentEndCount
Referenced by CountEndTime.
GameObject GenerateCleaningEvent.m_createDirt
Referenced by CheckDirt, CreateDirt, OnExit.
bool GenerateCleaningEvent.m_isPositionSet
Referenced by CreateDirt, SetPosition.
Vector3 GenerateCleaningEvent.m_position
Referenced by CreateDirt, SetPosition.
void GenerateCleaningEvent.SetRandomRange(float range)
References ｍ_randomRange.
override void GenerateCleaningEvent.OnStart()
イベントの開始 継承先でオーバーライドする
イベント開始処理
References CreateDirt.
override void GenerateCleaningEvent.OnUpdate()
イベント実行処理
References CheckDirt, CountEndTime.
override void GenerateCleaningEvent.OnExit()
イベント終了処理
References m_createDirt.
void GenerateCleaningEvent.SetPosition(Vector3 position)
References m_isPositionSet, m_position.
Referenced by AddCleaningProbabilityEvent.EventInitializeProcess.
void GenerateCleaningEvent.CreateDirt()
汚れオブジェクトを生成する
todo汚れの生成位置調整機能追加 汚れの位置を地形にある程度沿わす処理追加
References ｍ_randomRange, m_createDirt, m_dirtPrefab, m_isPositionSet, m_position.
Referenced by OnStart.
void GenerateCleaningEvent.CountEndTime()
References m_currentEndCount, m_endTime, BaseManagementEvent.SetEventEnd.
Referenced by OnUpdate.
void GenerateCleaningEvent.CheckDirt()
References m_createDirt, BaseManagementEvent.SetEventEnd.
Referenced by OnUpdate.