CharacterCore::ActionState_ReadyToThrow
DrawThrowItemArc CharacterCore.ActionState_ReadyToThrow.m_drawArc
float CharacterCore.ActionState_ReadyToThrow.m_playerMoveSpeed
float CharacterCore.ActionState_ReadyToThrow.m_arrivalTime
bool CharacterCore.ActionState_ReadyToThrow.m_cancelFlg
Camera CharacterCore.ActionState_ReadyToThrow.m_mainCamera
GameObject CharacterCore.ActionState_ReadyToThrow.m_lunchObj
GameObject CharacterCore.ActionState_ReadyToThrow.m_mousePosObj
AimCameraController CharacterCore.ActionState_ReadyToThrow.m_aimCameraController
override void CharacterCore.ActionState_ReadyToThrow.OnEnter()
References Camera, BaseManager< T >.instance, CharacterCore.ActionState_ReadyToThrow.SwitchCamera.
override void CharacterCore.ActionState_ReadyToThrow.OnUpdate()
References CharacterCore.ActionState_ReadyToThrow.CalculateThrowPower, CharacterCore.ActionState_ReadyToThrow.HitRay, BaseManager< T >.instance.
override void CharacterCore.ActionState_ReadyToThrow.OnFixedUpdate()
References CharacterCore.ActionState_ReadyToThrow.MovePlayer, CharacterCore.ActionState_ReadyToThrow.RotatePlayer.
override void CharacterCore.ActionState_ReadyToThrow.OnExit()
References CharacterCore.ActionState_ReadyToThrow.SwitchCamera.
void CharacterCore.ActionState_ReadyToThrow.MovePlayer()
Referenced by CharacterCore.ActionState_ReadyToThrow.OnFixedUpdate.
void CharacterCore.ActionState_ReadyToThrow.RotatePlayer()
References AimCameraController.Horizontal.
Referenced by CharacterCore.ActionState_ReadyToThrow.OnFixedUpdate.
void CharacterCore.ActionState_ReadyToThrow.CalculateThrowPower(Vector3 _startpos, Vector3 _endPos)
Referenced by CharacterCore.ActionState_ReadyToThrow.OnUpdate.
bool CharacterCore.ActionState_ReadyToThrow.HitRay(out RaycastHit _hit)
Referenced by CharacterCore.ActionState_ReadyToThrow.OnUpdate.
void CharacterCore.ActionState_ReadyToThrow.SwitchCamera(bool _aimCamera)
Referenced by CharacterCore.ActionState_ReadyToThrow.OnEnter, CharacterCore.ActionState_ReadyToThrow.OnExit.