QueueManager
GameObject QueueManager.m_headPoint
Referenced by UpdateQueueData.
float QueueManager.m_distance
Referenced by UpdateQueueData.
int QueueManager.m_maxQueue
Referenced by IsInQueue.
List<QueueData> QueueManager.m_queueDataList
Referenced by AddQueueObject, GetQueueObject, IsInQueue, IsQueue, NullCheck, RemoveQueueObject, UpdateQueueDataList.
GameObject QueueManager.HeadPoint
bool QueueManager.IsQueue()
References m_queueDataList.
bool QueueManager.IsInQueue()
References m_maxQueue, m_queueDataList.
Referenced by AddQueueObject.
QueueData QueueManager.AddQueueObject(GameObject _object)
待ち列に引数オブジェクトを追加
References IsInQueue, m_queueDataList, NullCheck, UpdateQueueData.
void QueueManager.RemoveQueueObject(QueueData _data)
待ち列リストから引数オブジェクトを取り除く
References m_queueDataList, NullCheck, UpdateQueueDataList.
QueueData QueueManager.GetQueueObject(GameObject _object)
引数と一致するデータを取得する
References m_queueDataList.
void QueueManager.UpdateQueueDataList()
目的地を計算する
References m_queueDataList, UpdateQueueData.
Referenced by RemoveQueueObject.
void QueueManager.UpdateQueueData(QueueData _data, int _number)
References m_distance, m_headPoint.
Referenced by AddQueueObject, UpdateQueueDataList.
void QueueManager.NullCheck()
References m_queueDataList.
Referenced by AddQueueObject, RemoveQueueObject.