ManagementEventUI
Image ManagementEventUI.m_eventImage
Referenced by SetEventImage.
TextMeshProUGUI ManagementEventUI.m_eventNameText
Referenced by SetEventNameText.
TextMeshProUGUI ManagementEventUI.m_eventDescriptionText
Referenced by SetEventDescriptionText.
BaseManagementEvent ManagementEventUI.m_targetManagementEvent
Referenced by CheckDestroy, SetUI.
BaseManagementEvent ManagementEventUI.TargetManagementEvent
void ManagementEventUI.Update()
References CheckDestroy.
void ManagementEventUI.SetEventImage(ManagementEventData _data)
References ManagementEventData.EventSprite, m_eventImage.
Referenced by SetUI.
void ManagementEventUI.SetEventNameText(ManagementEventData _data)
References ManagementEventData.EventName, m_eventNameText.
Referenced by SetUI.
void ManagementEventUI.SetEventDescriptionText(ManagementEventData _data)
References ManagementEventData.EventDescription, m_eventDescriptionText.
Referenced by SetUI.
void ManagementEventUI.CheckDestroy()
References m_targetManagementEvent.
Referenced by Update.
void ManagementEventUI.SetUI(BaseManagementEvent _baseManagementEvent)
IDを基にUIをセットする
References BaseManagementEvent.EventID, BaseManager< T >.instance, m_targetManagementEvent, SetEventDescriptionText, SetEventImage, SetEventNameText.