GetItemObject
BoolReactiveProperty GetItemObject.m_isGet
Referenced by Get, SwitchItemName, SwitchOutline.
AppearanceItemName GetItemObject.m_appearName
Referenced by Start, SwitchItemName.
AppearanceItemOutline GetItemObject.m_appearOutline
Referenced by Start, SwitchOutline.
bool GetItemObject.IsGet
Referenced by AppearanceItemName.Fade, CharacterCore.ActionState_IdleAndMove.SearchGatheringItem.
float GetItemObject.m_doSpead
Referenced by SwitchItemName, SwitchOutline.
void GetItemObject.Start()
References m_appearName, m_appearOutline, SwitchItemName, SwitchOutline.
void GetItemObject.OnTriggerEnter(Collider other)
References InventoryManager.instance, BasePocketItemDataController.IsInList.
void GetItemObject.OnTriggerExit(Collider other)
void GetItemObject.Update()
void GetItemObject.SwitchItemName()
References m_appearName, m_doSpead, m_isGet, AppearanceItemName.OnHide, AppearanceItemName.OnShow.
Referenced by Start.
void GetItemObject.SwitchOutline()
References m_appearOutline, m_doSpead, m_isGet, AppearanceItemOutline.OnHide, AppearanceItemOutline.OnShow.
Referenced by Start.
void GetItemObject.Get()
References InventoryManager.AddItem, DebugGet, BaseManager< T >.instance, InventoryManager.instance, m_isGet.
void GetItemObject.DebugGet()
References InventoryManager.AddItem, InventoryManager.instance.
Referenced by Get.
void GetItemObject.GetItem()
References InventoryManager.AddItem, InventoryManager.instance.
Referenced by CharacterCore.ActionState_Gathering.OnExit.