BaseLobbyStateUpdate
LobbyState BaseLobbyStateUpdate.m_lobbyState
Referenced by GetState.
LobbyState BaseLobbyStateUpdate.m_nextLobbyState
Referenced by LobbyStateUpdate_GoActionTutorial.CreateWindow, LobbyStateUpdate_GoManagementTutorial.CreateWindow, LobbyStateUpdate_ReturnAction.CreateWindow, LobbyStateUpdate_TrialSession.CreateWindow, GetNextState, SetEnd.
override int BaseLobbyStateUpdate.GetState()
References m_lobbyState.
override int BaseLobbyStateUpdate.GetNextState()
References m_nextLobbyState.
virtual void BaseLobbyStateUpdate.SetEnd(LobbyState _state)
ステート処理を終了する
References BaseGameStateUpdate.m_isEnd, m_nextLobbyState.
Referenced by LobbyStateUpdate_GoActionTutorial.CreateWindow, LobbyStateUpdate_GoManagementTutorial.CreateWindow, LobbyStateUpdate_ReturnAction.CreateWindow, LobbyStateUpdate_TrialSession.CreateWindow, LobbyStateUpdate_Normal.OnUpdate.