LogLayoutGroup
DirectionType
ShiftType
StandardType
Vector2 LogLayoutGroup.m_cellSize
Referenced by Layout.
Vector2 LogLayoutGroup.m_spaceSize
Referenced by Layout.
DirectionType LogLayoutGroup.m_directionType
Referenced by Layout.
ShiftType LogLayoutGroup.m_shiftType
Referenced by Layout.
StandardType LogLayoutGroup.m_standardType
Referenced by Layout.
Ease LogLayoutGroup.m_ease
Referenced by Layout.
float LogLayoutGroup.m_duration
Referenced by Layout.
List<Tween> LogLayoutGroup.m_tweenList
Referenced by KillTween, Layout.
void LogLayoutGroup.OnTransformChildrenChanged()
References Layout.
void LogLayoutGroup.OnDestroy()
References KillTween.
void LogLayoutGroup.KillTween()
References m_tweenList.
Referenced by Layout, OnDestroy.
void LogLayoutGroup.Layout()
レイアウトを操作
References KillTween, m_cellSize, m_directionType, m_duration, m_ease, m_shiftType, m_spaceSize, m_standardType, m_tweenList.
Referenced by OnTransformChildrenChanged.