CreateFoodController
FoodID CreateFoodController.m_foodID
Referenced by CreateConfirmationItemWindow, CreateFood, SetFoodData, SetFoodData.
PocketType CreateFoodController.m_pocketType
Referenced by CreateConfirmationItemWindow, CreateFood, IsCreate, SetFoodData, SetFoodData.
int CreateFoodController.m_currentCreateNum
Referenced by CreateFood, Decrement, Increment, IsCreate, IsDecrement, IsIncrement, SetFoodData, SetSliderValue, Slider.
int CreateFoodController.m_minCreateNum
Referenced by IsDecrement, SetFoodData, SetSliderValue.
int CreateFoodController.m_maxCreateNum
Referenced by IsIncrement, SetFoodData, SetSliderValue.
bool CreateFoodController.m_isSelectChangeFlg
Referenced by Decrement, Increment, OnLateUpdate, SetFoodData, Slider.
InputActionButton CreateFoodController.m_incrementInputActionButton
Referenced by Increment.
InputActionButton CreateFoodController.m_decrementInputActionButton
Referenced by Decrement.
InputActionButton CreateFoodController.m_createInputActionButton
Referenced by CreateFood, IsPressCreateButton.
Slider CreateFoodController.m_createNumSlider
Referenced by SetSliderValue, Slider.
WindowController CreateFoodController.m_confirmationItemWindowController
Referenced by CreateConfirmationItemWindow.
PocketType CreateFoodController.PocketType
Referenced by CreateCreateFoodNeedIngredientSlotList.CreateSlotInstance.
int CreateFoodController.CurrentCreateNum
Referenced by CreateFoodNeedIngredientSlotData.SetComparisonNumText, ChangeCreateFoodControllerDescription.SetCurrentCreateNumText.
int CreateFoodController.MinCreateNum
Referenced by ChangeCreateFoodControllerDescription.SetMinCreateNumText.
int CreateFoodController.MaxCreateNum
Referenced by ChangeCreateFoodControllerDescription.SetMaxCreateNumText.
bool CreateFoodController.IsSelectChangeFlg
Referenced by ChangeCreateFoodControllerDescription.IsChangeDescription, CreateFoodWindow.OnUpdate.
void CreateFoodController.Start()
References SetFoodData.
void CreateFoodController.SetFoodData()
References FoodData.GetCreateNum, FoodData.IsCreate, m_currentCreateNum, m_foodID, m_isSelectChangeFlg, m_maxCreateNum, m_minCreateNum, m_pocketType, SetSliderValue.
Referenced by CreateFood, SetFoodData, Start.
void CreateFoodController.Select()
References Decrement, Increment, Slider.
Referenced by OnUpdate.
void CreateFoodController.Increment()
References IsIncrement, InputActionButton.IsInputActionTrriger, m_currentCreateNum, m_incrementInputActionButton, m_isSelectChangeFlg, SetSliderValue.
Referenced by Select.
void CreateFoodController.Decrement()
References IsDecrement, InputActionButton.IsInputActionTrriger, m_currentCreateNum, m_decrementInputActionButton, m_isSelectChangeFlg, SetSliderValue.
Referenced by Select.
void CreateFoodController.Slider()
References m_createNumSlider, m_currentCreateNum, m_isSelectChangeFlg.
Referenced by Select.
void CreateFoodController.SetSliderValue()
References m_createNumSlider, m_currentCreateNum, m_maxCreateNum, m_minCreateNum.
Referenced by Decrement, Increment, SetFoodData.
async UniTask CreateFoodController.CreateFood()
References CreateConfirmationItemWindow, FoodData.CreateFood, InputActionButton.IsInputActionTrriger, m_createInputActionButton, m_currentCreateNum, m_foodID, m_pocketType, SetFoodData.
Referenced by OnUpdate.
async UniTask CreateFoodController.CreateConfirmationItemWindow()
References m_confirmationItemWindowController, m_foodID, m_pocketType.
Referenced by CreateFood.
void CreateFoodController.SetFoodData(PocketType _pocketType, FoodID _id)
作成する料理のデータをセットする
References m_foodID, m_pocketType, SetFoodData.
Referenced by CreateFoodWindow.OnInitialize.
async UniTask CreateFoodController.OnUpdate()
実行処理
References CreateFood, Select.
Referenced by CreateFoodWindow.OnUpdate.
void CreateFoodController.OnLateUpdate()
後実行処理
References m_isSelectChangeFlg.
Referenced by CreateFoodWindow.OnUpdate.
bool CreateFoodController.IsPressCreateButton()
料理を作成するボタンが押されたか
References InputActionButton.IsInputActionTrriger, m_createInputActionButton.
bool CreateFoodController.IsIncrement()
足せるか
References m_currentCreateNum, m_maxCreateNum.
Referenced by Increment, CreateFoodControllerInputActionButton.IsPress.
bool CreateFoodController.IsDecrement()
減らせるか
References m_currentCreateNum, m_minCreateNum.
Referenced by Decrement, CreateFoodControllerInputActionButton.IsPress.
bool CreateFoodController.IsCreate()
料理が作成可能か
References m_currentCreateNum, m_pocketType.
Referenced by CreateFoodControllerInputActionButton.IsPress.