SelectTutorialController
List<TutorialData> SelectTutorialController.m_tutorialDataList
Referenced by GetCurrentTutorialData, IsGoClose, IsGoNext.
int SelectTutorialController.m_currentTutorial
Referenced by Back, GetCurrentTutorialData, IsGoBack, IsGoClose, IsGoNext, Next.
bool SelectTutorialController.m_isSelectChangeFlg
Referenced by Back, Next, OnLateUpdate.
SelectTutorialTutorialInputActiomButton SelectTutorialController.m_nextInputActionButton
Referenced by Next.
SelectTutorialTutorialInputActiomButton SelectTutorialController.m_backInputActionButton
Referenced by Back.
SelectTutorialTutorialInputActiomButton SelectTutorialController.m_closeInputActionButton
List<TutorialData> SelectTutorialController.TutorialDataList
Referenced by ChangeSelectTutorialControllerDescription.SetPageText.
int SelectTutorialController.CurrentTutorial
bool SelectTutorialController.IsSelectChangeFlg
Referenced by ChangeSelectTutorialControllerDescription.IsChangeDescription.
void SelectTutorialController.OnUpdate()
実行処理
References Select.
Referenced by TutorialWindow.OnUpdate.
void SelectTutorialController.OnLateUpdate()
後実行処理
References m_isSelectChangeFlg.
Referenced by TutorialWindow.OnUpdate.
TutorialData SelectTutorialController.GetCurrentTutorialData()
現在のチュートリアル情報を取得
References m_currentTutorial, m_tutorialDataList.
Referenced by ChangeSelectTutorialControllerDescription.SetDescription.
bool SelectTutorialController.IsGoNext()
References m_currentTutorial, m_tutorialDataList.
Referenced by SelectTutorialTutorialInputActiomButton.IsPress, Next.
bool SelectTutorialController.IsGoBack()
References m_currentTutorial.
Referenced by Back, SelectTutorialTutorialInputActiomButton.IsPress.
bool SelectTutorialController.IsGoClose()
References m_currentTutorial, m_tutorialDataList.
Referenced by SelectTutorialTutorialInputActiomButton.IsPress.
void SelectTutorialController.Select()
References Back, Next.
Referenced by OnUpdate.
void SelectTutorialController.Next()
References IsGoNext, InputActionButton.IsInputActionTrriger, m_currentTutorial, m_isSelectChangeFlg, m_nextInputActionButton.
Referenced by Select.
void SelectTutorialController.Back()
References IsGoBack, InputActionButton.IsInputActionTrriger, m_backInputActionButton, m_currentTutorial, m_isSelectChangeFlg.
Referenced by Select.