LobbyStateUpdate_GoActionTutorial
WindowController LobbyStateUpdate_GoActionTutorial.m_windowController
Referenced by CreateWindow.
WindowController LobbyStateUpdate_GoActionTutorial.m_createWindowController
Referenced by CreateWindow, DestoryControllerWindow.
override async UniTask LobbyStateUpdate_GoActionTutorial.OnInitialize()
初期処理
References CreateWindow.
override async UniTask LobbyStateUpdate_GoActionTutorial.OnExit()
終了処理
References DestoryControllerWindow.
async UniTask LobbyStateUpdate_GoActionTutorial.CreateWindow()
References DestoryControllerWindow, m_createWindowController, BaseLobbyStateUpdate.m_nextLobbyState, m_windowController, BaseLobbyStateUpdate.SetEnd.
Referenced by OnInitialize.
void LobbyStateUpdate_GoActionTutorial.DestoryControllerWindow()
References m_createWindowController.
Referenced by CreateWindow, OnExit.