RecipeItemSlotData
Color RecipeItemSlotData.m_validSlotColor
Referenced by SetSlotColor.
Color RecipeItemSlotData.m_invalidSlotColor
Referenced by SetSlotColor.
bool RecipeItemSlotData.m_isCreate
Referenced by ProvideFoodRecipeSlotData.CheckCreate, CheckCreate, SetSlotColor.
bool RecipeItemSlotData.IsCreate
Referenced by CurrentSelectManagementProvideFoodSlotData.SetColor.
override void RecipeItemSlotData.SetItemSlotData(BaseItemData _itemData, PocketType _pocketType)
References CheckCreate.
override void RecipeItemSlotData.InitializeSlotData()
References CheckCreate.
virtual void RecipeItemSlotData.CheckCreate()
References FoodData.IsCreate, m_isCreate, ItemSlotData.m_itemID, ItemSlotData.m_pocketType, SetSlotColor.
Referenced by InitializeSlotData, SetItemSlotData.
void RecipeItemSlotData.SetSlotColor()
References m_invalidSlotColor, m_isCreate, m_validSlotColor.
Referenced by ProvideFoodRecipeSlotData.CheckCreate, CheckCreate.