StorySkillUIChangeColor
Image [] StorySkillUIChangeColor.m_imagesList
Referenced by ChangeNoUseColor, ChangeUseColor, Start.
CharacterCore StorySkillUIChangeColor.m_playerCharacterCore
Color StorySkillUIChangeColor.m_originColor
Referenced by ChangeUseColor, Start.
Color StorySkillUIChangeColor.m_dontUseSkillColor
Referenced by ChangeNoUseColor.
void StorySkillUIChangeColor.Start()
References m_imagesList, m_originColor.
void StorySkillUIChangeColor.Update()
void StorySkillUIChangeColor.ChangeNoUseColor()
References m_dontUseSkillColor, m_imagesList.
Referenced by BPSkill_1Presenter.BarUpdate, BPSkill_2Presenter.BarUpdate.
void StorySkillUIChangeColor.ChangeUseColor()
References m_imagesList, m_originColor.
Referenced by BPSkill_1Presenter.BarSetting, BPSkill_2Presenter.BarSetting, BPSkill_1Presenter.BarUpdate, BPSkill_2Presenter.BarUpdate.