HideAlphaDitherAreaObject
Shader HideAlphaDitherAreaObject.m_hideAlphaDitherShader
Referenced by SetHideShader.
bool HideAlphaDitherAreaObject.m_HideWhenInside
Referenced by OnTriggerEnter, OnTriggerExit.
List<HideAreaObjctData> HideAlphaDitherAreaObject.m_hideObjectList
Referenced by GetHideAreaObjctData, Hide, SetHideShader.
void HideAlphaDitherAreaObject.Start()
References GetHideAreaObjctData, SetHideShader.
void HideAlphaDitherAreaObject.OnTriggerEnter(Collider other)
References Hide, m_HideWhenInside.
void HideAlphaDitherAreaObject.OnTriggerExit(Collider other)
References Hide, m_HideWhenInside.
void HideAlphaDitherAreaObject.Hide(bool _isInside)
References m_hideObjectList.
Referenced by OnTriggerEnter, OnTriggerExit.
void HideAlphaDitherAreaObject.GetHideAreaObjctData(GameObject _obj)
References m_hideObjectList, HideAlphaDitherAreaObject.HideAreaObjctData.Renderer.
Referenced by Start.
void HideAlphaDitherAreaObject.SetHideShader()
References m_hideAlphaDitherShader, m_hideObjectList.
Referenced by Start.