ThrowItemInstance
string ThrowItemInstance.m_tag
Referenced by Awake.
GameObject ThrowItemInstance.m_targetObject
Referenced by Awake.
ItemTypeID ThrowItemInstance.m_itemTypeID
Referenced by SetItemID, Throw.
uint ThrowItemInstance.m_itemID
Referenced by SetItemID, Throw.
Vector3 ThrowItemInstance.m_throwPower
Referenced by Throw.
Rigidbody ThrowItemInstance.m_rigidbody
Referenced by Throw.
Collider ThrowItemInstance.m_collider
Referenced by Throw.
bool ThrowItemInstance.m_onece
Referenced by Throw.
Transform ThrowItemInstance.m_handTrans
Referenced by SetHandTrans, Throw.
ItemTypeID ThrowItemInstance.ItemTypeID
uint ThrowItemInstance.ItemID
Vector3 ThrowItemInstance.ThrowPower
void ThrowItemInstance.SetHandTrans(Transform _handTrans)
References m_handTrans.
Referenced by CharacterCore.ActionState_ThrowItem.OnEnter.
void ThrowItemInstance.SetItemID(ItemTypeID _itemTypeID, uint _itemID)
References m_itemID, m_itemTypeID.
Referenced by CharacterCore.ActionState_ThrowItem.OnEnter.
void ThrowItemInstance.Throw()
References SoundManager.Instance, BaseManager< T >.instance, InventoryManager.instance, m_collider, m_handTrans, m_itemID, m_itemTypeID, m_onece, m_rigidbody, m_throwPower, InventoryManager.RemoveItem, SoundManager.Start3DPlayback.
Referenced by CharacterCore.ActionState_ThrowItem.OnEnter, CharacterCore.ActionState_ThrowItem.OnExit.
void ThrowItemInstance.Awake()
References m_tag, m_targetObject.