InputActionButton_ChangeInputActionReference
System.IDisposable InputActionButton_ChangeInputActionReference.m_disposable
Referenced by ChangeActionReference.
void InputActionButton_ChangeInputActionReference.ChangeInputActionReference(InputActionReference _nextInputAction)
References ChangeActionReference, InputActionButton.m_inputActionReference.
Referenced by AnyActionUIController.ChangeStateUI.
void InputActionButton_ChangeInputActionReference.Start()
References ChangeActionReference.
void InputActionButton_ChangeInputActionReference.ChangeActionReference()
References BaseManager< T >.instance, m_disposable, InputActionButton.UpdateButtonImage.
Referenced by ChangeInputActionReference, Start.