TitleScreenManager
CanvasGroup TitleScreenManager.m_titleLogo
Referenced by ShowTitleLogo, StartUp.
CanvasGroup TitleScreenManager.m_pushAnyKey
Referenced by ShowTitleLogo, StartUp, UpdateForWaitAnyKey.
GameObject TitleScreenManager.m_mainMenuPanel
Referenced by StartUp, UpdateForWaitAnyKey.
GameObject TitleScreenManager.m_optionObject
Referenced by OnOption, StartUp.
bool TitleScreenManager.m_isAnyKeyPressed
Referenced by StartUp, Update, UpdateForWaitAnyKey.
readonly InputAction TitleScreenManager.m_pressAnyKeyAction
Referenced by UpdateForWaitAnyKey.
SceneTransitionManager TitleScreenManager.m_sceneChanger
Referenced by OnLoadGame, OnNewGame.
void TitleScreenManager.OnEnable()
void TitleScreenManager.OnDisable()
async UniTask TitleScreenManager.ShowTitleLogo()
References m_pushAnyKey, m_titleLogo.
Referenced by StartUp.
void TitleScreenManager.Update()
References m_isAnyKeyPressed, UpdateForWaitAnyKey.
void TitleScreenManager.UpdateForWaitAnyKey()
キーを押すまで の更新処理 pushAnyKeyが表示されているとき
References m_isAnyKeyPressed, m_mainMenuPanel, m_pressAnyKeyAction, m_pushAnyKey.
Referenced by Update.
void TitleScreenManager.StartUp()
References m_isAnyKeyPressed, m_mainMenuPanel, m_optionObject, m_pushAnyKey, m_titleLogo, ShowTitleLogo.
Referenced by TitleEntryPoint.OnEnter.
void TitleScreenManager.OnNewGame()
References m_sceneChanger, SceneTransitionManager.SceneChange.
void TitleScreenManager.OnLoadGame()
References m_sceneChanger, SceneTransitionManager.SceneChange.
void TitleScreenManager.OnOption()
References m_optionObject.
void TitleScreenManager.OnExit()