LocalizeTipsController
int LocalizeTipsController.m_currentIndex
Referenced by AddIndex, ChangeText, Start.
int LocalizeTipsController.m_maxIndex
Referenced by AddIndex, Start.
LocalizedStringTable LocalizeTipsController.m_localizedSpriteTable
Referenced by AddIndex, GetTableString, Start.
TextMeshProUGUI LocalizeTipsController.m_textUI
Referenced by ChangeText.
void LocalizeTipsController.Start()
References m_currentIndex, m_localizedSpriteTable, m_maxIndex.
string LocalizeTipsController.GetTableString(int index)
References m_localizedSpriteTable.
Referenced by ChangeText.
void LocalizeTipsController.ChangeText()
References GetTableString, m_currentIndex, m_textUI.
Referenced by Decrement, Increment.
void LocalizeTipsController.AddIndex(int index)
References m_currentIndex, m_localizedSpriteTable, m_maxIndex.
Referenced by Decrement, Increment.
void LocalizeTipsController.Increment()
References AddIndex, ChangeText.
void LocalizeTipsController.Decrement()
References AddIndex, ChangeText.