ChangeCreateFoodControllerDescription
CreateFoodController ChangeCreateFoodControllerDescription.m_createFoodController
Referenced by IsChangeDescription, SetCurrentCreateNumText, SetMaxCreateNumText, SetMinCreateNumText.
TextMeshProUGUI ChangeCreateFoodControllerDescription.m_currentCreateNumText
Referenced by SetCurrentCreateNumText.
TextMeshProUGUI ChangeCreateFoodControllerDescription.m_maxCreateNumText
Referenced by SetMaxCreateNumText.
TextMeshProUGUI ChangeCreateFoodControllerDescription.m_minCreateNumText
Referenced by SetMinCreateNumText.
virtual void ChangeCreateFoodControllerDescription.OnInitialize()
References SetDescription.
Referenced by CreateFoodWindow.OnInitialize.
virtual void ChangeCreateFoodControllerDescription.OnUpdate()
References IsChangeDescription, SetDescription.
Referenced by CreateFoodWindow.OnUpdate.
bool ChangeCreateFoodControllerDescription.IsChangeDescription()
References CreateFoodController.IsSelectChangeFlg, m_createFoodController.
Referenced by OnUpdate.
void ChangeCreateFoodControllerDescription.SetDescription()
References SetCurrentCreateNumText, SetMaxCreateNumText, SetMinCreateNumText.
Referenced by OnInitialize, OnUpdate.
void ChangeCreateFoodControllerDescription.SetCurrentCreateNumText()
References CreateFoodController.CurrentCreateNum, m_createFoodController, m_currentCreateNumText.
Referenced by SetDescription.
void ChangeCreateFoodControllerDescription.SetMaxCreateNumText()
References m_createFoodController, m_maxCreateNumText, CreateFoodController.MaxCreateNum.
Referenced by SetDescription.
void ChangeCreateFoodControllerDescription.SetMinCreateNumText()
References m_createFoodController, m_minCreateNumText, CreateFoodController.MinCreateNum.
Referenced by SetDescription.