ShowAndHideForCanvasGroup
CanvasGroup ShowAndHideForCanvasGroup.m_canvasGroup
Referenced by Hide, Show, Start.
bool ShowAndHideForCanvasGroup.m_isShow
Referenced by Hide, InitSetting, OnHide, OnShow, Show.
bool ShowAndHideForCanvasGroup.IsShow
void ShowAndHideForCanvasGroup.Start()
References InitSetting, m_canvasGroup.
void ShowAndHideForCanvasGroup.InitSetting()
References Hide, m_isShow, Show.
Referenced by Start.
void ShowAndHideForCanvasGroup.Show()
References m_canvasGroup, m_isShow.
Referenced by InitSetting, OnShow.
void ShowAndHideForCanvasGroup.Hide()
References m_canvasGroup, m_isShow.
Referenced by InitSetting, OnHide.
void ShowAndHideForCanvasGroup.OnShow()
References m_isShow, Show.
void ShowAndHideForCanvasGroup.OnHide()
References Hide, m_isShow.