CharacterCore::ActionState_IdleAndMove
float CharacterCore.ActionState_IdleAndMove.m_speedStick
bool CharacterCore.ActionState_IdleAndMove.m_isRun
override void CharacterCore.ActionState_IdleAndMove.OnEnter()
override void CharacterCore.ActionState_IdleAndMove.OnExit()
override void CharacterCore.ActionState_IdleAndMove.OnUpdate()
References CharacterCore.ActionState_IdleAndMove.PlayerUpdate.
override void CharacterCore.ActionState_IdleAndMove.OnFixedUpdate()
References CharacterCore.ActionState_IdleAndMove.CheckPlayerDistance, CharacterCore.ActionState_IdleAndMove.UpdateBP, CharacterCore.ActionState_IdleAndMove.UpdateStamina.
bool CharacterCore.ActionState_IdleAndMove.CheckStorySkill(int _slot, StorySkill_ID _skillID, GameObject _obserbSkillObj)
References BaseManager< T >.instance.
Referenced by CharacterCore.ActionState_IdleAndMove.UpdateBP.
void CharacterCore.ActionState_IdleAndMove.PlayerUpdate(Vector3 input)
References CharacterCore.ActionState_IdleAndMove.ManagementScenePlayerUpdate, IMetaAI< T >.ObjectList, CharacterCore.ActionState_IdleAndMove.SearchGatheringItem.
Referenced by CharacterCore.ActionState_IdleAndMove.OnUpdate.
void CharacterCore.ActionState_IdleAndMove.ManagementScenePlayerUpdate()
経営シーンのプレイヤーの更新処理(上甲)
todo特定シーンでのみ実行される処理をデバッグ用に無効化しているため、追々修正
References IMetaAI< T >.ObjectList.
Referenced by CharacterCore.ActionState_IdleAndMove.PlayerUpdate.
bool CharacterCore.ActionState_IdleAndMove.SearchGatheringItem()
References GetItemObject.IsGet, IMetaAI< T >.ObjectList.
Referenced by CharacterCore.ActionState_IdleAndMove.PlayerUpdate.
float CharacterCore.ActionState_IdleAndMove.CheckPlayerDistance()
References IMetaAI< T >.ObjectList.
Referenced by CharacterCore.ActionState_IdleAndMove.OnFixedUpdate.
void CharacterCore.ActionState_IdleAndMove.UpdateStamina()
Referenced by CharacterCore.ActionState_IdleAndMove.OnFixedUpdate.
void CharacterCore.ActionState_IdleAndMove.UpdateBP()
References CharacterCore.ActionState_IdleAndMove.CheckStorySkill.
Referenced by CharacterCore.ActionState_IdleAndMove.OnFixedUpdate.