ActionUIController
MainActionUIState
AnyActionUIState
ActionUIState
ReactiveProperty<ActionUIState> ActionUIController.m_state
ReactiveProperty<ActionUIState> ActionUIController.m_anyActionState
float ActionUIController.m_nowAnyActionDistance
現在のアクション起点との距離
AnyActionUIController ActionUIController.m_anyActionUIController
AnyActionUIの表示するコントローラー
void ActionUIController.AddState(ActionUIState _state)
Referenced by PlayerParameters.AddActionUIState.
void ActionUIController.RemoveState(ActionUIState _state)
Referenced by PlayerParameters.RemoveActionUIState.
void ActionUIController.AddAnyActionState(ActionUIState _state, float _distance)
References SwitchAnyAction.
Referenced by PlayerParameters.AddAnyActionUIState.
void ActionUIController.RemoveAnyActionState(ActionUIState _state)
References SwitchAnyAction.
Referenced by PlayerParameters.RemoveAnyActionUIState.
void ActionUIController.SwitchAnyAction(ActionUIState _state, float _distance=-1.0f)
Referenced by AddAnyActionState, RemoveAnyActionState.
async void ActionUIController.Start()
References SwitchState.
void ActionUIController.SwitchState()
References AnyActionUIController.ChangeStateUI.
Referenced by Start.