ChangeItemDescription
DisplayOneType
PocketType ChangeItemDescription.m_pocketType
Referenced by ChangeDesctiptionSelectUI, ChangeFoodItemDescription.SetCreateNumText, SetCreateNumText, SetNumText.
SelectUIController ChangeItemDescription.m_selectUIController
Referenced by GetCurrentSelectItemSlotData, IsChangeDescription.
TextMeshProUGUI ChangeItemDescription.m_nameTextMeshPro
Referenced by SetCommonActiveList, SetNameText.
TextMeshProUGUI ChangeItemDescription.m_descriptionTextMeshPro
Referenced by SetCommonActiveList, SetDescriptionText.
Image ChangeItemDescription.m_typeImage
Referenced by SetCommonActiveList, SetTypeImage.
TextMeshProUGUI ChangeItemDescription.m_typeTextMeshPro
Referenced by SetCommonActiveList, SetTypeText.
TextMeshProUGUI ChangeItemDescription.m_maxNumText
Referenced by SetCommonActiveList, SetMaxNumText.
TextMeshProUGUI ChangeItemDescription.m_levelTextMeshPro
Referenced by SetCommonActiveList, SetLevelText.
TextMeshProUGUI ChangeItemDescription.m_numTextMeshPro
Referenced by SetCommonActiveList, SetNumText.
DisplayOneType ChangeItemDescription.m_displayOneType
Referenced by SetNumText.
TextMeshProUGUI ChangeItemDescription.m_healingValueTextMeshPro
Referenced by SetEdibleItemActiveList, SetHealingValueText.
Image ChangeItemDescription.m_conditionImage
Referenced by SetConditionImage, SetEdibleItemActiveList.
CreateConditionImage ChangeItemDescription.m_createConditionImage
Referenced by CreateConditionImage, SetEdibleItemActiveList.
TextMeshProUGUI ChangeItemDescription.m_conditionText
Referenced by SetConditionText, SetEdibleItemActiveList.
Image ChangeItemDescription.m_conditionBackColor
Referenced by SetConditionBackColor.
float ChangeItemDescription.m_conditionBackAlpha
Referenced by SetConditionBackColor.
TextMeshProUGUI ChangeItemDescription.m_pocketNumText
Referenced by SetPocketActiveList, SetPocketNumText.
List<GameObject> ChangeItemDescription.m_pocketNumList
Referenced by SetPocketActiveList.
Image ChangeItemDescription.m_itemImage
Referenced by SetCommonActiveList, SetItemImage.
List<GameObject> ChangeItemDescription.m_itemImageList
Referenced by SetCommonActiveList.
List<GameObject> ChangeItemDescription.m_nameList
Referenced by SetCommonActiveList.
List<GameObject> ChangeItemDescription.m_descriptionList
Referenced by SetCommonActiveList.
List<GameObject> ChangeItemDescription.m_typeImageList
Referenced by SetCommonActiveList.
List<GameObject> ChangeItemDescription.m_typeList
Referenced by SetCommonActiveList.
List<GameObject> ChangeItemDescription.m_maxNumTextList
Referenced by SetCommonActiveList.
List<GameObject> ChangeItemDescription.m_levelList
Referenced by SetCommonActiveList.
List<GameObject> ChangeItemDescription.m_numList
Referenced by SetCommonActiveList.
List<GameObject> ChangeItemDescription.m_healingValueList
Referenced by SetEdibleItemActiveList.
List<GameObject> ChangeItemDescription.m_conditionImageList
Referenced by SetEdibleItemActiveList.
List<GameObject> ChangeItemDescription.m_createConditionImageList
Referenced by SetEdibleItemActiveList.
List<GameObject> ChangeItemDescription.m_conditionTextList
Referenced by SetEdibleItemActiveList.
TextMeshProUGUI ChangeItemDescription.m_priceText
Referenced by SetFoodActiveList, SetPriceText.
List<GameObject> ChangeItemDescription.m_priceTextList
Referenced by SetFoodActiveList.
TextMeshProUGUI ChangeItemDescription.m_createNumText
Referenced by SetCreateNumText, SetFoodActiveList.
List<GameObject> ChangeItemDescription.m_createNumTextList
Referenced by SetFoodActiveList.
CreateNeedIngredientSlot ChangeItemDescription.m_createNeedIngredientSlot
Referenced by CreateNeedIngredientSlot.
virtual void ChangeItemDescription.OnInitialize()
References ChangeDesctiptionSelectUI.
Referenced by RecipeWindow.InitializeRecipeData, InventoryWindow.OnInitialize, NewItemWindow.OnInitialize, RecipeWindow.OnInitialize.
virtual void ChangeItemDescription.OnUpdate()
References ChangeDesctiptionSelectUI, IsChangeDescription.
Referenced by InventoryWindow.OnUpdate, NewItemWindow.OnUpdate, RecipeWindow.OnUpdate.
void ChangeItemDescription.ChangeDesctiptionSelectUI()
ItemSlotData
References ChangeDescription, GetCurrentSelectItemSlotData, InitDescription, ItemSlotData.ItemID, ItemSlotData.ItemTypeID, m_pocketType, SetActiveList.
Referenced by OnInitialize, OnUpdate.
void ChangeItemDescription.ChangeDescription(PocketType _pocketType, ItemTypeID _typeID, uint _itemID)
ID
References InitDescription, BaseManager< T >.instance, SetActiveList, SetDescription.
Referenced by ChangeDesctiptionSelectUI, ConfirmationItemWindow.OnInitialize, CreateFoodWindow.OnInitialize, CreateFoodWindow.OnUpdate.
bool ChangeItemDescription.IsChangeDescription()
References SelectUIController.IsSelectChangeFlg, m_selectUIController.
Referenced by OnUpdate.
virtual void ChangeItemDescription.SetDescription(BaseItemData _itemData)
References SetCommonDescription, SetEdibleItemDescription, SetFoodDescription, SetPocketDescription.
Referenced by ChangeDescription.
virtual void ChangeItemDescription.InitDescription()
References InitilizeCommonDescription, InitilizeEdibleItemDescription, InitilizeFoodDescription, InitilizePocketDescription.
Referenced by ChangeDescription, ChangeDesctiptionSelectUI.
virtual void ChangeItemDescription.SetActiveList()
References SetCommonActiveList, SetEdibleItemActiveList, SetFoodActiveList, SetPocketActiveList.
Referenced by ChangeDescription, ChangeDesctiptionSelectUI.
ItemSlotData ChangeItemDescription.GetCurrentSelectItemSlotData()
SelectUIControllerItemSlotData
References SelectUIController.CurrentSelectUI, m_selectUIController.
Referenced by ChangeDesctiptionSelectUI, GetPocketItemData.
void ChangeItemDescription.CheckToSetActiveGameObjectList< T >(T _component, List< GameObject > _list)
List
virtual void ChangeItemDescription.SetItemImage(BaseItemData _itemData, bool _active=true)
References BaseItemData.ItemSprite, m_itemImage.
Referenced by InitilizeCommonDescription, SetCommonDescription.
virtual void ChangeItemDescription.SetTypeText(BaseItemData _itemData, bool _active=true)
References BaseManager< T >.instance, BaseItemData.ItemTypeID, m_typeTextMeshPro.
Referenced by InitilizeCommonDescription, SetCommonDescription.
virtual void ChangeItemDescription.SetTypeImage(BaseItemData _itemData, bool _active=true)
References BaseManager< T >.instance, BaseItemData.ItemTypeID, m_typeImage.
Referenced by InitilizeCommonDescription, SetCommonDescription.
virtual void ChangeItemDescription.SetMaxNumText(BaseItemData _itemData, bool _active=true)
References m_maxNumText, BaseItemData.MaxNum.
Referenced by InitilizeCommonDescription, SetCommonDescription.
virtual void ChangeItemDescription.SetNameText(BaseItemData _itemData, bool _active=true)
References BaseItemData.ItemName, m_nameTextMeshPro.
Referenced by InitilizeCommonDescription, SetCommonDescription.
virtual void ChangeItemDescription.SetDescriptionText(BaseItemData _itemData, bool _active=true)
References BaseItemData.ItemDescriptionText, m_descriptionTextMeshPro.
Referenced by InitilizeCommonDescription, SetCommonDescription.
virtual void ChangeItemDescription.SetNumText(BaseItemData _itemData, bool _active=true)
References BaseItemData.ItemID, BaseItemData.ItemTypeID, m_displayOneType, m_numTextMeshPro, m_pocketType.
Referenced by InitilizeCommonDescription, SetCommonDescription.
virtual void ChangeItemDescription.SetLevelText(BaseItemData _itemData, bool _active=true)
References BaseItemData.ItemLevel, m_levelTextMeshPro.
Referenced by InitilizeCommonDescription, SetCommonDescription.
virtual void ChangeItemDescription.SetHealingValueText(BaseItemData _itemData, bool _active=true)
References CastEdibleItem, m_healingValueTextMeshPro.
Referenced by InitilizeEdibleItemDescription, SetEdibleItemDescription.
virtual void ChangeItemDescription.SetConditionImage(BaseItemData _itemData, bool _active=true)
References CastEdibleItem, BaseManager< T >.instance, m_conditionImage.
Referenced by InitilizeEdibleItemDescription, SetEdibleItemDescription.
virtual void ChangeItemDescription.CreateConditionImage(BaseItemData _itemData, bool _active=true)
References CreateConditionImage.CreateImage, m_createConditionImage.
Referenced by InitilizeEdibleItemDescription, SetEdibleItemDescription.
virtual void ChangeItemDescription.SetConditionText(BaseItemData _itemData, bool _active=true)
References CastEdibleItem, BaseManager< T >.instance, m_conditionText.
Referenced by InitilizeEdibleItemDescription, SetEdibleItemDescription.
virtual void ChangeItemDescription.SetConditionBackColor(BaseItemData _itemData, bool _active=true)
References CastEdibleItem, BaseManager< T >.instance, m_conditionBackAlpha, m_conditionBackColor.
Referenced by InitilizeEdibleItemDescription, SetEdibleItemDescription.
BaseEdibleItem ChangeItemDescription.CastEdibleItem(BaseItemData _itemData)
Referenced by SetConditionBackColor, SetConditionImage, SetConditionText, SetHealingValueText.
FoodData ChangeItemDescription.CastFoodData(BaseItemData _itemData)
Referenced by SetPriceText.
void ChangeItemDescription.SetCommonDescription(BaseItemData _itemData)
References SetDescriptionText, SetItemImage, SetLevelText, SetMaxNumText, SetNameText, SetNumText, SetTypeImage, SetTypeText.
Referenced by SetDescription.
void ChangeItemDescription.InitilizeCommonDescription()
References SetDescriptionText, SetItemImage, SetLevelText, SetMaxNumText, SetNameText, SetNumText, SetTypeImage, SetTypeText.
Referenced by InitDescription.
void ChangeItemDescription.SetCommonActiveList()
References m_descriptionList, m_descriptionTextMeshPro, m_itemImage, m_itemImageList, m_levelList, m_levelTextMeshPro, m_maxNumText, m_maxNumTextList, m_nameList, m_nameTextMeshPro, m_numList, m_numTextMeshPro, m_typeImage, m_typeImageList, m_typeList, m_typeTextMeshPro.
Referenced by SetActiveList.
void ChangeItemDescription.SetEdibleItemDescription(BaseItemData _itemData)
References CreateConditionImage, SetConditionBackColor, SetConditionImage, SetConditionText, SetHealingValueText.
Referenced by SetDescription.
void ChangeItemDescription.InitilizeEdibleItemDescription()
References CreateConditionImage, SetConditionBackColor, SetConditionImage, SetConditionText, SetHealingValueText.
Referenced by InitDescription.
void ChangeItemDescription.SetEdibleItemActiveList()
References m_conditionImage, m_conditionImageList, m_conditionText, m_conditionTextList, m_createConditionImage, m_createConditionImageList, m_healingValueList, m_healingValueTextMeshPro.
Referenced by SetActiveList.
void ChangeItemDescription.SetFoodDescription(BaseItemData _itemData)
References CreateNeedIngredientSlot, SetCreateNumText, SetPriceText.
Referenced by SetDescription.
void ChangeItemDescription.InitilizeFoodDescription()
References SetCreateNumText, SetPriceText.
Referenced by InitDescription.
void ChangeItemDescription.SetFoodActiveList()
References m_createNumText, m_createNumTextList, m_priceText, m_priceTextList.
Referenced by SetActiveList.
void ChangeItemDescription.CreateNeedIngredientSlot(BaseItemData _itemData)
References BaseCreateSlotList.CreateSlot, BaseItemData.ItemID, m_createNeedIngredientSlot, CreateNeedIngredientSlot.SetFoodID.
Referenced by SetFoodDescription.
void ChangeItemDescription.SetPriceText(BaseItemData _data, bool _active=true)
References CastFoodData, m_priceText.
Referenced by InitilizeFoodDescription, SetFoodDescription.
void ChangeItemDescription.SetCreateNumText(BaseItemData _data, bool _active=true)
References FoodData.GetCreateNum, BaseItemData.ItemID, m_createNumText, m_pocketType.
Referenced by InitilizeFoodDescription, SetFoodDescription.
void ChangeItemDescription.SetPocketDescription(BaseItemData _itemData)
References SetPocketNumText.
Referenced by SetDescription.
void ChangeItemDescription.InitilizePocketDescription()
References SetPocketNumText.
Referenced by InitDescription.
void ChangeItemDescription.SetPocketActiveList()
References m_pocketNumList, m_pocketNumText.
Referenced by SetActiveList.
void ChangeItemDescription.SetPocketNumText(bool _active=true)
References GetPocketItemData, m_pocketNumText.
Referenced by InitilizePocketDescription, SetPocketDescription.
PocketItemData ChangeItemDescription.GetPocketItemData()
References GetCurrentSelectItemSlotData, PocketItemSlotData.PocketItemData.
Referenced by SetPocketNumText.