ManagementStateUpdate_Result
WindowController ManagementStateUpdate_Result.m_windowController
Referenced by CreateToUpdateWindow.
WindowController ManagementStateUpdate_Result.m_createWindowController
Referenced by CreateToUpdateWindow, DestoryWindowController.
override async UniTask ManagementStateUpdate_Result.OnInitialize()
初期処理
References CreateToUpdateWindow, BaseManager< T >.instance.
override async UniTask ManagementStateUpdate_Result.OnExit()
終了処理
References DestoryWindowController.
async UniTask ManagementStateUpdate_Result.CreateToUpdateWindow()
References DestoryWindowController, m_createWindowController, BaseManagementStateUpdate.m_nextManagementState, m_windowController, BaseManagementStateUpdate.SetEnd.
Referenced by OnInitialize.
void ManagementStateUpdate_Result.DestoryWindowController()
References m_createWindowController.
Referenced by CreateToUpdateWindow, OnExit.