StorySkillUIController
float StorySkillUIController.m_value
Referenced by SetValue, UpdateFillAmount.
Image StorySkillUIController.m_image
Referenced by UpdateFillAmount.
float StorySkillUIController.m_max
Referenced by SetValue, SetValue.
void StorySkillUIController.SetValue(float _current, float _max)
References m_max, SetValue.
Referenced by BPSkill_1Presenter.BarSetting, BPSkill_2Presenter.BarSetting, BPSkill_1Presenter.BarUpdate, BPSkill_2Presenter.BarUpdate, SetValue.
void StorySkillUIController.SetValue(float _currentHealth)
References m_max, m_value, UpdateFillAmount.
void StorySkillUIController.UpdateFillAmount()
References m_image, m_value.
Referenced by OnBeforeSerialize, SetValue, Update.
void StorySkillUIController.Update()
References UpdateFillAmount.
void ISerializationCallbackReceiver. StorySkillUIController.OnBeforeSerialize()
References UpdateFillAmount.
void ISerializationCallbackReceiver. StorySkillUIController.OnAfterDeserialize()