SelectUIController
SelectUIInterpolation
AlwaysCreateType
Tweener SelectUIController.m_tweener
RectTransform SelectUIController.m_scaleRect
Vector3 SelectUIController.m_defaultScale
string SelectUIController.m_pressInputAction
string SelectUIController.m_holdInputAction
string SelectUIController.m_selectSoundName
List<UIDataList> SelectUIController.m_uiList
Referenced by Down, IsHeightExceed, IsWidthExceed, Left, Right, SelectActionWindowUI, SelectUI, SelectUIActionWindowController.SelectWindowUI, SelectUIActionWindowController.SetSelectUIScale, Up.
bool SelectUIController.m_isLoop
Referenced by Down, Left, Right, Up.
SelectUIInterpolation SelectUIController.m_interpolationType
Referenced by Down, Up.
AlwaysCreateType SelectUIController.m_alwaysCreateType
Referenced by SelectUIActionWindowController.OnUpdate.
UIData SelectUIController.m_currentSelectUIData
Referenced by SelectUIActionWindowController.CheckWithChange, DoScale, OnUpdateInput, PlayPressSound, SelectActionWindowUI, SelectUI, SelectUIActionWindowController.SelectWindowUI, SelectUIActionWindowController.SetSelectUIScale.
int SelectUIController.m_currentWidth
Referenced by SelectUIActionWindowController.CheckWithChange, Down, IsWidthBelow, IsWidthExceed, Left, Right, SelectActionWindowUI, SelectUI, SelectUIActionWindowController.SelectWindowUI, Up.
int SelectUIController.m_currentHeight
Referenced by Down, IsHeightBelow, IsHeightExceed, IsWidthExceed, Left, Right, SelectActionWindowUI, SelectUI, Up.
int SelectUIController.m_currentConstraintCount
bool SelectUIController.m_isSelectChangeFlg
Referenced by SelectActionWindowUI, SelectUI, SelectUIActionWindowController.SelectWindowUI.
int SelectUIController.m_listCount
bool SelectUIController.m_isPress
Referenced by PressUpdate.
List<UIDataList> SelectUIController.UIList
Referenced by ActionItemControllerWindow.CheckNullUIgameObjList, ActionItemControllerWindow.DeleteSprite, ActionItemControllerWindow.SelectItemAction.
UIData SelectUIController.CurrentSelectUIData
Referenced by SelectUICursorPress.Select.
GameObject SelectUIController.CurrentSelectUI
Referenced by ChangeActionItemListPosition.ChangePosition, SelfChangeCurrentSelectUICursorPosition.ChangePosition, JudgeWindow.CheckPressSelectButton, SelectUseItemWindow.CheckPressSelectUseItemButton, RecipeWindow.CreateFood, ActionItemWindow.CreateSelectUseCraftItemWindow, InventoryWindow.CreateSelectUseCraftItemWindow, ChangeItemDescription.GetCurrentSelectItemSlotData, BaseProvideFoodUI.GetCurrentSelectItemSlotData< T >, CreateFoodInputActionButton.IsPress, ChangeScrollViewPosition.OnUpdate, ChangeScrollViewPosition.OnUpdateEveryTime, ActionItemControllerWindow.SelectItemAction, SelectFoodDetailUI.SetCreateNeedIngredientSlot, CurrentSelectManagementProvideFoodSlotData.SetSlot, SelectUICursorPosition.UpdatePosition, SelectUICursorScale.UpdateScale.
bool SelectUIController.IsSelectChangeFlg
現在選択しているスロットが変更されたかどうか確認する、読み取り専用プロパティ
<return> true - 変更された false - 変更されていない
Referenced by CurrentSelectManagementProvideFoodSlotData.Check, ChangeActionItemListPosition.CheckChangePosition, ChangeItemDescription.IsChangeDescription, CreateFoodInputActionButton.IsPress, ChangeScrollViewPosition.OnUpdate, SelectFoodDetailUI.OnUpdate.
bool SelectUIController.IsPress
Referenced by JudgeWindow.CheckPressSelectButton, SelectUseItemWindow.CheckPressSelectUseItemButton, RecipeWindow.CreateFood, ActionItemWindow.CreateSelectUseCraftItemWindow, InventoryWindow.CreateSelectUseCraftItemWindow, SelectProvideFoodUI.SetProvideFood.
string SelectUIController.PressInputAction
string SelectUIController.HoldInputAction
Referenced by SelectUICursorPress.Hold.
void SelectUIController.OnDestroy()
void SelectUIController.DoScale()
References m_currentSelectUIData, SelectUIController.UIData.UI.
Referenced by PressUpdate.
void SelectUIController.Awake()
References SetHeadUIGameObject.
void SelectUIController.CurrentUISelectCheck()
Referenced by NullCheck.
void SelectUIController.SelectActionWindowUI()
References SoundManager.Instance, BaseManager< T >.instance, Left, m_currentHeight, m_currentSelectUIData, m_currentWidth, m_isSelectChangeFlg, m_uiList, Right, SoundManager.StartPlayback.
Referenced by OnUpdateActionWindow.
void SelectUIController.OnPut()
References BaseManager< T >.instance.
Referenced by OnUpdateActionWindow.
void SelectUIController.OnUse()
References BaseManager< T >.instance.
Referenced by OnUpdateActionWindow.
void SelectUIController.SelectUI()
References Down, BaseManager< T >.instance, Left, m_currentHeight, m_currentSelectUIData, m_currentWidth, m_isSelectChangeFlg, m_uiList, PlaySelectSound, Right, Up.
Referenced by OnUpdate.
bool SelectUIController.Up()
References Down, IsHeightBelow, IsWidthExceed, m_currentHeight, m_currentWidth, m_interpolationType, m_isLoop, m_uiList, Up.
Referenced by Down, SelectUI, Up.
bool SelectUIController.Down()
References Down, IsHeightExceed, IsWidthExceed, m_currentHeight, m_currentWidth, m_interpolationType, m_isLoop, m_uiList, Up.
Referenced by Down, SelectUI, Up.
bool SelectUIController.IsWidthExceed()
References m_currentHeight, m_currentWidth, m_uiList.
Referenced by Down, Right, Up.
bool SelectUIController.IsWidthBelow()
References m_currentWidth.
Referenced by Left.
bool SelectUIController.IsHeightExceed()
References m_currentHeight, m_uiList.
Referenced by Down.
bool SelectUIController.IsHeightBelow()
References m_currentHeight.
Referenced by Up.
void SelectUIController.OnUpdateInput()
References BaseManager< T >.instance, m_currentSelectUIData, PressUpdate, SelectUIController.UIData.SelectUIType.
Referenced by OnUpdate.
void SelectUIController.PressUpdate()
References DoScale, m_isPress, PlayPressSound.
Referenced by OnUpdateInput.
virtual void SelectUIController.OnUpdate()
References OnUpdateInput, SelectUI.
Referenced by SelectProvideFoodMenuUI.OnSelectUpdate, SelectProvideFoodUI.OnSelectUpdate, JudgeWindow.OnSelfUpdate, ActionItemWindow.OnUpdate, InventoryWindow.OnUpdate, ManagementResultWindow.OnUpdate, NewItemWindow.OnUpdate, RecipeWindow.OnUpdate, SelectManagementWindow.OnUpdate, SelectUseItemWindow.OnUpdate.
virtual void SelectUIController.OnLateUpdate()
Referenced by BaseProvideFoodUI.OnLateUpdate, OnLateUpdateActionWindow, JudgeWindow.OnSelfUpdate, ActionItemWindow.OnUpdate, InventoryWindow.OnUpdate, ManagementResultWindow.OnUpdate, NewItemWindow.OnUpdate, RecipeWindow.OnUpdate, SelectManagementWindow.OnUpdate, SelectUseItemWindow.OnUpdate.
ButtonID SelectUIController.IsPressButton()
選択したUIにボタンIDがあれば返す
References SelectUIController.UIData.UI.
Referenced by SelectManagementWindow.SelectButton.
virtual void SelectUIController.AddUI(GameObject _ui, SelectUIType _type, int _lineBreak)
スロットリストに引数リストを追加する
References SetHeadUIGameObject.
Referenced by SelectUseItemWindow.AddButton, BaseCreateSlotList.AddSelectUIControler.
void SelectUIController.SetHeadUIGameObject()
Referenced by AddUI, Awake, SetUIActionWindowGameObject.
void SelectUIController.SetUIActionWindowGameObject()
References SetHeadUIGameObject.
Referenced by SelectUIActionWindowController.AddUI, ActionItemControllerWindow.DeleteSprite.
void SelectUIController.NullCheck()
nullのUIを取り除き、現在選択中のUIが配列外でないか確認する
References CurrentUISelectCheck.
Referenced by SelectProvideFoodMenuUI.OnUpdate, SelectUIActionWindowController.OnUpdate.
void SelectUIController.OnUpdateActionWindow()
References OnPut, OnUse, SelectActionWindowUI.
void SelectUIController.OnLateUpdateActionWindow()
References OnLateUpdate.
bool SelectUIController.Left()
References IsWidthBelow, m_currentHeight, m_currentWidth, m_isLoop, m_uiList.
Referenced by SelectActionWindowUI, SelectUI, SelectUIActionWindowController.SelectWindowUI.
bool SelectUIController.Right()
References IsWidthExceed, m_currentHeight, m_currentWidth, m_isLoop, m_uiList.
Referenced by SelectActionWindowUI, SelectUI, SelectUIActionWindowController.SelectWindowUI.
void SelectUIController.PlaySelectSound()
References SoundManager.Instance, SoundManager.StartPlayback.
Referenced by SelectUI.
void SelectUIController.PlayPressSound()
References SoundManager.Instance, m_currentSelectUIData, SelectUIController.UIData.PressSoundPath, SoundManager.StartPlayback.
Referenced by PressUpdate.