LobbyStateUpdate_GoManagementTutorial
WindowController LobbyStateUpdate_GoManagementTutorial.m_windowController
Referenced by CreateWindow.
WindowController LobbyStateUpdate_GoManagementTutorial.m_createWindowController
Referenced by CreateWindow, DestoryControllerWindow.
override async UniTask LobbyStateUpdate_GoManagementTutorial.OnInitialize()
初期処理
References CreateWindow.
override async UniTask LobbyStateUpdate_GoManagementTutorial.OnExit()
終了処理
References DestoryControllerWindow.
async UniTask LobbyStateUpdate_GoManagementTutorial.CreateWindow()
References DestoryControllerWindow, m_createWindowController, BaseLobbyStateUpdate.m_nextLobbyState, m_windowController, BaseLobbyStateUpdate.SetEnd.
Referenced by OnInitialize.
void LobbyStateUpdate_GoManagementTutorial.DestoryControllerWindow()
References m_createWindowController.
Referenced by CreateWindow, OnExit.