LobbyStateUpdate_ReturnAction
WindowController LobbyStateUpdate_ReturnAction.m_returnActionWindowController
Referenced by CreateWindow.
WindowController LobbyStateUpdate_ReturnAction.m_createWindowController
Referenced by CreateWindow, DestoryWindowController.
override async UniTask LobbyStateUpdate_ReturnAction.OnInitialize()
初期処理
References CreateWindow.
override async UniTask LobbyStateUpdate_ReturnAction.OnExit()
終了処理
References DestoryWindowController, NewItemManager.instance, BasePocketItemDataController.ItemDataList, Transfer.
async UniTask LobbyStateUpdate_ReturnAction.CreateWindow()
References DestoryWindowController, m_createWindowController, BaseLobbyStateUpdate.m_nextLobbyState, m_returnActionWindowController, BaseLobbyStateUpdate.SetEnd.
Referenced by OnInitialize.
void LobbyStateUpdate_ReturnAction.DestoryWindowController()
References m_createWindowController.
Referenced by CreateWindow, OnExit.
void LobbyStateUpdate_ReturnAction.Transfer()
References BasePocketItemDataController.AddItem, InventoryManager.instance, ManagementStorageManager.instance, BasePocketItemDataController.ItemDataList.
Referenced by OnExit.