BaseStaffDecorator
FlexibleStaffDataVariable BaseStaffDecorator.m_flexibleStaffDataVariable
Referenced by GetStaffData.
StaffData BaseStaffDecorator.GetStaffData()
スタッフ情報が存在するかのチェック
References m_flexibleStaffDataVariable.
Referenced by DecNullCheckTargetOrderFoodStaff.OnConditionCheck, DecoBeenTargetObjectStaff.OnConditionCheck, DecoCheckStateStaff.OnConditionCheck.