CounterManager
List<CounterPointData> CounterManager.m_counterPointDataList
Referenced by GetRandomPoint.
List<OrderFoodData> CounterManager.m_orderFoodDataList
Referenced by CheckRemove, CreateOrderFood, GetCounterFoodData, IsCooking, IsOrdering, OnUpdateOrderFood.
List<OrderFoodData> CounterManager.OrderFoodDataList
void CounterManager.Update()
References CheckRemove, OnUpdateOrderFood.
OrderFoodData CounterManager.CreateOrderFood(FoodID _foodID, CustomerData _customerData)
References BaseManager< T >.instance, m_orderFoodDataList, FoodData.ManagementFoodPrefab, CustomerData.TargetTableSetData.
Referenced by OrderFood.
void CounterManager.CheckRemove()
References m_orderFoodDataList.
Referenced by Update.
void CounterManager.OnUpdateOrderFood()
References m_orderFoodDataList.
Referenced by Update.
OrderFoodData CounterManager.OrderFood(CustomerData _customerData)
料理を注文する
References CreateOrderFood, BaseManager< T >.instance, IsOrder.
bool CounterManager.IsOrder()
料理を注文できるかどうか
References BaseManager< T >.instance.
Referenced by OrderFood.
bool CounterManager.IsOrdering()
現在料理が注文されているか確認する
References m_orderFoodDataList.
bool CounterManager.IsCooking()
調理中(作成中)の料理があるかどうか
References m_orderFoodDataList.
OrderFoodData CounterManager.GetCounterFoodData()
現在受け取り待ちの料理を取得する
References m_orderFoodDataList.
CounterPointData CounterManager.GetRandomPoint()
ランダムで空いているカウンターポイントを取得(空きがなければnull)
References m_counterPointDataList.