BlinkingCanvasGroup
CanvasGroup BlinkingCanvasGroup.m_canvasGroup
Referenced by Awake, EndEasing, StartEasing.
float BlinkingCanvasGroup.m_blinkSpeed
Referenced by StartEasing.
float BlinkingCanvasGroup.m_minAlpha
Referenced by StartEasing.
float BlinkingCanvasGroup.m_maxAlpha
Referenced by EndEasing, StartEasing.
bool BlinkingCanvasGroup.m_isStartMin
Referenced by StartEasing.
bool BlinkingCanvasGroup.m_isStartBlink
Referenced by Start.
void BlinkingCanvasGroup.Awake()
References m_canvasGroup.
void BlinkingCanvasGroup.Start()
References m_isStartBlink, StartEasing.
void BlinkingCanvasGroup.StartEasing()
References m_blinkSpeed, m_canvasGroup, m_isStartMin, m_maxAlpha, m_minAlpha.
Referenced by TitleMainMenuButton.OnSelected, Start.
void BlinkingCanvasGroup.EndEasing()
References m_canvasGroup, m_maxAlpha.
Referenced by TitleMainMenuButton.OnDeselected.