LobbyStateUpdate_TrialSession
WindowController LobbyStateUpdate_TrialSession.m_trialSessionWindowController
Referenced by CreateWindow.
WindowController LobbyStateUpdate_TrialSession.m_createWindowController
Referenced by CreateWindow, DestoryWindowController.
override async UniTask LobbyStateUpdate_TrialSession.OnInitialize()
初期処理
References CreateWindow.
override async UniTask LobbyStateUpdate_TrialSession.OnExit()
終了処理
References DestoryWindowController, InitializeTrialSession.
async UniTask LobbyStateUpdate_TrialSession.CreateWindow()
References DestoryWindowController, m_createWindowController, BaseLobbyStateUpdate.m_nextLobbyState, m_trialSessionWindowController, BaseLobbyStateUpdate.SetEnd.
Referenced by OnInitialize.
void LobbyStateUpdate_TrialSession.DestoryWindowController()
References m_createWindowController.
Referenced by CreateWindow, OnExit.
void LobbyStateUpdate_TrialSession.InitializeTrialSession()
References BasePocketItemDataController.AllInitializePocketDataList.
Referenced by OnExit.