WindowUIController
List<BaseWindowUI> WindowUIController.m_baseWindowUIList
Referenced by IsGoNext, OnInitialize, OnLateUpdate, OnUpdate, Select, SetAlpha, SetUI.
BaseWindowUI WindowUIController.m_currentUpdateBaseWindowUI
Referenced by OnUpdate, SetAlpha, SetUI.
int WindowUIController.m_currentBaseWindowUICount
Referenced by Back, IsGoBack, IsGoNext, Next, SetUI.
InputActionButton WindowUIController.m_nextInputActionButton
Referenced by Select.
InputActionButton WindowUIController.m_backInputActionButton
Referenced by Select.
async UniTask WindowUIController.OnInitialize()
初期化処理
References m_baseWindowUIList, SetUI.
Referenced by ManagementSelectProvideFoodWindow.OnInitialize.
async UniTask WindowUIController.OnUpdate()
実行処理
References m_baseWindowUIList, m_currentUpdateBaseWindowUI, BaseWindowUI.OnSelectUpdate, Select.
Referenced by ManagementSelectProvideFoodWindow.OnUpdate.
async UniTask WindowUIController.OnLateUpdate()
後実行処理
References m_baseWindowUIList.
Referenced by ManagementSelectProvideFoodWindow.OnUpdate.
bool WindowUIController.IsGoNext()
References m_baseWindowUIList, m_currentBaseWindowUICount.
Referenced by WindowUIControllerInputActionButton.IsPress, Next.
bool WindowUIController.IsGoBack()
References m_currentBaseWindowUICount.
Referenced by Back, WindowUIControllerInputActionButton.IsPress.
async UniTask WindowUIController.SetUI()
UIをセットする
References m_baseWindowUIList, m_currentBaseWindowUICount, m_currentUpdateBaseWindowUI, BaseWindowUI.OnSelectExit, BaseWindowUI.OnSelectInitialize, SetAlpha.
Referenced by OnInitialize, Select.
void WindowUIController.SetAlpha()
色をセット
References m_baseWindowUIList, m_currentUpdateBaseWindowUI.
Referenced by SetUI.
async UniTask WindowUIController.Select()
References Back, InputActionButton.IsInputActionTrriger, m_backInputActionButton, m_baseWindowUIList, m_nextInputActionButton, Next, SetUI.
Referenced by OnUpdate.
bool WindowUIController.Next()
References IsGoNext, m_currentBaseWindowUICount.
Referenced by Select.
bool WindowUIController.Back()
References IsGoBack, m_currentBaseWindowUICount.
Referenced by Select.