BaseDoTweenUI
UpdateType
bool BaseDoTweenUI.m_isGameStopMove
Referenced by DoAlphaCanvasGroup.StartDoTween, DOAnchorPosUI.StartDoTween, DoColorImageUI.StartDoTween, DoScaleUI.StartDoTween.
UpdateType BaseDoTweenUI.m_updateType
Referenced by Start, Update.
int BaseDoTweenUI.m_loopCount
Referenced by DoAlphaCanvasGroup.StartDoTween, DOAnchorPosUI.StartDoTween, DoColorImageUI.StartDoTween, DoScaleUI.StartDoTween.
LoopType BaseDoTweenUI.m_loopType
Referenced by DoAlphaCanvasGroup.StartDoTween, DOAnchorPosUI.StartDoTween, DoColorImageUI.StartDoTween, DoScaleUI.StartDoTween.
Sequence BaseDoTweenUI.m_sequence
Referenced by KillSequence, DoAlphaCanvasGroup.StartDoTween, DOAnchorPosUI.StartDoTween, DoColorImageUI.StartDoTween, DoScaleUI.StartDoTween.
Sequence BaseDoTweenUI.Sequence
実行中のSequence
void BaseDoTweenUI.Start()
References m_updateType, OnInitialize, StartDoTween.
void BaseDoTweenUI.Update()
References m_updateType, OnUpdate.
void BaseDoTweenUI.OnDestroy()
References KillSequence.
void BaseDoTweenUI.KillSequence()
References m_sequence.
Referenced by OnDestroy, DoAlphaCanvasGroup.StartDoTween, DOAnchorPosUI.StartDoTween, DoColorImageUI.StartDoTween, DoScaleUI.StartDoTween.
virtual void BaseDoTweenUI.OnInitialize()
Referenced by Start.
virtual void BaseDoTweenUI.OnUpdate()
Referenced by Update.
void BaseDoTweenUI.StartDoTween()
DOTweenを再生開始する
Referenced by Start.