ShowHIdeSoldOutProvideFoodSlotList
InputActionButton ShowHIdeSoldOutProvideFoodSlotList.m_inputActionButton
Referenced by Update.
bool ShowHIdeSoldOutProvideFoodSlotList.m_isShow
Referenced by SettingPosByFlag, Switch.
Vector3 ShowHIdeSoldOutProvideFoodSlotList.m_hidePosition
Referenced by SettingPosByFlag, Switch.
Vector3 ShowHIdeSoldOutProvideFoodSlotList.m_showPosition
Referenced by SettingPosByFlag, Switch.
bool ShowHIdeSoldOutProvideFoodSlotList.IsShow
void ShowHIdeSoldOutProvideFoodSlotList.Start()
References SettingPosByFlag.
void ShowHIdeSoldOutProvideFoodSlotList.Update()
References InputActionButton.IsInputActionTrriger, m_inputActionButton, Switch.
void ShowHIdeSoldOutProvideFoodSlotList.Switch()
References m_hidePosition, m_isShow, m_showPosition.
Referenced by Update.
void ShowHIdeSoldOutProvideFoodSlotList.SettingPosByFlag()
m_isShow の値に合わせて位置を変更する
References m_hidePosition, m_isShow, m_showPosition.
Referenced by OnBeforeSerialize, Start.
void ISerializationCallbackReceiver. ShowHIdeSoldOutProvideFoodSlotList.OnBeforeSerialize()
References SettingPosByFlag.
void ISerializationCallbackReceiver. ShowHIdeSoldOutProvideFoodSlotList.OnAfterDeserialize()