InputActionButton
InputActionButtonUpdateType
HoldType
InputActionButtonUpdateType InputActionButton.m_updateType
実行の種類 Auto - 勝手に実行:Self - 自身で実行
Referenced by Start, Update.
HoldType InputActionButton.m_holdType
Referenced by UpdateHoldGage.
Image InputActionButton.m_gaugeImage
Referenced by UpdateHoldGage.
string InputActionButton.m_pressSE
Referenced by PlaySE.
CanvasGroup InputActionButton.m_canvasGroup
Referenced by SetColor.
float InputActionButton.m_imPossibleAlpha
Referenced by SetColor.
InputActionButtonUpdateType InputActionButton.UpdateType
InputActionReference InputActionButton.InputActionReference
Referenced by AnyActionUIController.ChangeStateUI.
InputActionReference InputActionButton.m_inputActionReference
Referenced by InputActionButton_ChangeInputActionReference.ChangeInputActionReference, IsInputActionTrriger, PlaySE, UpdateButtonImage, UpdateHoldGage.
Image InputActionButton.m_buttonImage
Referenced by UpdateButtonImage.
void InputActionButton.Start()
References BaseManager< T >.instance, m_updateType, OnInitialize, UpdateButtonImage.
void InputActionButton.Update()
References m_updateType, OnUpdate.
void InputActionButton.UpdateHoldGage()
References IsPress, m_gaugeImage, m_holdType, m_inputActionReference.
Referenced by OnUpdate.
void InputActionButton.PlaySE()
References SoundManager.Instance, IsPress, m_inputActionReference, m_pressSE, SoundManager.StartPlayback.
Referenced by OnUpdate.
void InputActionButton.SetColor()
References IsPress, m_canvasGroup, m_imPossibleAlpha.
Referenced by OnInitialize, OnUpdate.
void InputActionButton.OnInitialize()
初期化処理
References SetColor.
Referenced by Start.
void InputActionButton.OnUpdate()
実行処理
References PlaySE, SetColor, UpdateHoldGage.
Referenced by Update.
bool InputActionButton.IsInputActionTrriger()
ボタンを選択したかどうか
References IsPress, m_inputActionReference.
Referenced by SelectStageController.Back, SelectTutorialController.Back, CreateFoodController.CreateFood, CreateFoodController.Decrement, CreateFoodController.Increment, BaseWindow.IsClose, CreateFoodController.IsPressCreateButton, SelectStageController.IsStart, SelectStageController.Next, SelectTutorialController.Next, WindowUIController.Select, ManagementSelectProvideFoodWindow.Transition, ShowHIdeSoldOutProvideFoodSlotList.Update.
virtual bool InputActionButton.IsPress()
Referenced by IsInputActionTrriger, PlaySE, SetColor, UpdateHoldGage.
void InputActionButton.UpdateButtonImage(DeviceTypes _deviceTypes)
References BaseManager< T >.instance, m_buttonImage, m_inputActionReference.
Referenced by InputActionButton_ChangeInputActionReference.ChangeActionReference, Start.