ShowSpeechBubble
SpeechBubbleType
CanvasGroup ShowSpeechBubble.m_canvasGroup
Referenced by InitText, OnHide, OnShow.
SpeechBubbleType ShowSpeechBubble.m_type
Referenced by CalcDistanceTargetObject, InitText.
string ShowSpeechBubble.m_tag
Referenced by GetTargetObject.
GameObject ShowSpeechBubble.m_tagetObject
Referenced by CalcDistanceTargetObject, GetTargetObject.
float ShowSpeechBubble.m_distance
Referenced by CalcDistanceTargetObject.
float ShowSpeechBubble.m_doSpead
Referenced by OnHide, OnShow.
void ShowSpeechBubble.Start()
References GetTargetObject, InitText.
void ShowSpeechBubble.Update()
References CalcDistanceTargetObject.
void ShowSpeechBubble.CalcDistanceTargetObject()
References m_distance, m_tagetObject, m_type, OnHide, OnShow.
Referenced by Update.
void ShowSpeechBubble.GetTargetObject()
References m_tag, m_tagetObject.
Referenced by Start.
void ShowSpeechBubble.InitText()
References m_canvasGroup, m_type.
Referenced by Start.
void ShowSpeechBubble.OnShow()
References m_canvasGroup, m_doSpead.
Referenced by CalcDistanceTargetObject.
void ShowSpeechBubble.OnHide()
References m_canvasGroup, m_doSpead.
Referenced by CalcDistanceTargetObject.