MyCharacterController
KinematicCharacterMotor MyCharacterController.Motor
Referenced by Jump, SetPositionMotor, Update, UpdateRotation, UpdateVelocity.
float MyCharacterController.MaxStableMoveSpeed
float MyCharacterController.StableMovementSharpness
Referenced by UpdateVelocity.
float MyCharacterController.OrientationSharpness
Referenced by UpdateRotation.
bool MyCharacterController.RotationObstruction
Vector3 MyCharacterController.Gravity
Referenced by UpdateVelocity.
Transform MyCharacterController.MeshRoot
Animator MyCharacterController.CharacterAnimator
Referenced by FindParameter, Start, Update.
float MyCharacterController.ForwardAxisSharpness
Referenced by Update.
float MyCharacterController.TurnAxisSharpness
Referenced by Update.
Vector3 MyCharacterController.m_moveVec
Referenced by UpdateVelocity.
List<string> MyCharacterController.m_tagList
Referenced by AddNoHitTag, IsColliderValidForCollisions.
bool MyCharacterController.m_isRootMotion
Referenced by Start, Update, UpdateVelocity.
float MyCharacterController.m_moveSpeed
Referenced by UpdateVelocity.
Vector3 MyCharacterController.m_lookVector
Referenced by UpdateRotation.
Vector3 MyCharacterController._internalVelocityAdd
Referenced by AddVelocity, UpdateVelocity.
float MyCharacterController.m_speedRate
Referenced by UpdateVelocity.
Vector3 MyCharacterController._rootMotionPositionDelta
Referenced by AfterCharacterUpdate, Start, UpdateVelocity.
Quaternion MyCharacterController._rootMotionRotationDelta
Referenced by AfterCharacterUpdate, Start, UpdateRotation.
float MyCharacterController._targetForwardAxis
Referenced by Update.
float MyCharacterController._targetRightAxis
Referenced by Update.
float MyCharacterController._forwardAxis
Referenced by Update, UpdateVelocity.
float MyCharacterController._rightAxis
Referenced by Update.
bool MyCharacterController.IsRootMotion
float MyCharacterController.MoveSpeed
Referenced by CharacterCore.Move.
Vector3 MyCharacterController.MoveVec
Vector3 MyCharacterController.LookVector
float MyCharacterController.SpeedRate
void MyCharacterController.Start()
References _rootMotionPositionDelta, _rootMotionRotationDelta, CharacterAnimator, m_isRootMotion.
void MyCharacterController.Update()
References _forwardAxis, _rightAxis, _targetForwardAxis, _targetRightAxis, CharacterAnimator, FindParameter, ForwardAxisSharpness, m_isRootMotion, Motor, TurnAxisSharpness.
bool MyCharacterController.FindParameter(string name)
References CharacterAnimator.
Referenced by Update.
void MyCharacterController.BeforeCharacterUpdate(float deltaTime)
(Called by KinematicCharacterMotor during its update cycle) This is called before the character begins its movement update
void MyCharacterController.UpdateRotation(ref Quaternion currentRotation, float deltaTime)
(Called by KinematicCharacterMotor during its update cycle) This is where you tell your character what its rotation should be right now.
This is the ONLY place where you should set the character's rotation
References _rootMotionRotationDelta, m_lookVector, Motor, OrientationSharpness.
void MyCharacterController.UpdateVelocity(ref Vector3 currentVelocity, float deltaTime)
(Called by KinematicCharacterMotor during its update cycle) This is where you tell your character what its velocity should be right now.
This is the ONLY place where you can set the character's velocity
References _forwardAxis, _internalVelocityAdd, _rootMotionPositionDelta, Gravity, m_isRootMotion, m_moveSpeed, m_moveVec, m_speedRate, Motor, StableMovementSharpness.
void MyCharacterController.AfterCharacterUpdate(float deltaTime)
(Called by KinematicCharacterMotor during its update cycle) This is called after the character has finished its movement update
References _rootMotionPositionDelta, _rootMotionRotationDelta.
bool MyCharacterController.IsColliderValidForCollisions(Collider coll)
References m_tagList.
void MyCharacterController.OnGroundHit(Collider hitCollider, Vector3 hitNormal, Vector3 hitPoint, ref HitStabilityReport hitStabilityReport)
void MyCharacterController.OnMovementHit(Collider hitCollider, Vector3 hitNormal, Vector3 hitPoint, ref HitStabilityReport hitStabilityReport)
void MyCharacterController.PostGroundingUpdate(float deltaTime)
void MyCharacterController.AddVelocity(Vector3 velocity)
References _internalVelocityAdd.
Referenced by Jump.
void MyCharacterController.ProcessHitStabilityReport(Collider hitCollider, Vector3 hitNormal, Vector3 hitPoint, Vector3 atCharacterPosition, Quaternion atCharacterRotation, ref HitStabilityReport hitStabilityReport)
void MyCharacterController.OnDiscreteCollisionDetected(Collider hitCollider)
void MyCharacterController.Jump(float _jumpPower)
References AddVelocity, Motor.
void MyCharacterController.SetPositionMotor(Vector3 _pos, bool _bypassInterpolation=true)
References Motor.
Referenced by AppearPasserby.CreateObject, CharacterCore.EnemyResetPos, ChildrenMember.SetPosition, AppearCustomer.UpdateCreate.
void MyCharacterController.AddNoHitTag(string _tagName)
References m_tagList.