BaseCustomerStateBehaviour
FlexibleCustomerDataVariable BaseCustomerStateBehaviour.m_flexibleCustomerDataVariable
Referenced by GetCustomerData.
CustomerData BaseCustomerStateBehaviour.GetCustomerData()
客情報が存在するかのチェック
References m_flexibleCustomerDataVariable.
Referenced by AddCameCustomerDataCustomer.Add, AddQueueCustemor.AddQueue, CheckIsOrderCustomer.Check, TransitionTargetOrderFoodStateCustomer.Check, WaitFoodCustomer.CheckCurry, WaitFoodCustomer.Count, CreateCustometCanvasCustomer.Create, DestroyTargetCounterFoodCustomer.DestroyTargetFood, QueueFindChairCustomer.FindChair, StartFindChairCustomer.FindChair, CheckTargetOrdetFoodCustomer.OnStateUpdate, OrderFoodCustomer.Order, PayMoneyCustomer.Pay, RemoveChairCustomer.Remove, RemoveQueueCustomer.RemoveQueue, SetTargetOrderFoodActiveCustomer.Set, SetStateCutomer.SetState, CheckStateCustomer.Transition, WaitQueueCustomer.UpdateQueue, WaitEatCustomer.Wait.
void BaseCustomerStateBehaviour.SetTransition(StateLink _link)
Referenced by AddQueueCustemor.AddQueue, CheckIsOrderCustomer.Check, TransitionTargetOrderFoodStateCustomer.Check, WaitFoodCustomer.CheckCurry, WaitFoodCustomer.Count, QueueFindChairCustomer.FindChair, StartFindChairCustomer.FindChair, CheckTargetOrdetFoodCustomer.OnStateUpdate, OrderFoodCustomer.Order, CheckStateCustomer.Transition, WaitQueueCustomer.UpdateQueue, WaitEatCustomer.Wait.
GameObject BaseCustomerStateBehaviour.GetRootGameObject()
Referenced by AddQueueCustemor.AddQueue, CreateCustometCanvasCustomer.Create, AppearEffectCustomer.OnLoadVisualEffect, WaitEffectStop.OnStateUpdate, AddPopUpEffcetCustomer.Start.