BaseCreateSlotList
CreateSlotType
CreateSlotType BaseCreateSlotList.m_createSlotType
Referenced by AddSelectUIControler, SetLineBreak.
SelectUIController BaseCreateSlotList.m_selectUIController
Referenced by AddSelectUIControler, SetLineBreak.
GameObject BaseCreateSlotList.m_slot
Referenced by CreateActionItemSlotList.CreateSlotInstance, CreateCreateFoodNeedIngredientSlotList.CreateSlotInstance, CreateManagementProvideFoodControllerSlotList.CreateSlotInstance, CreateManagementProvideFoodSlotList.CreateSlotInstance, CreateNeedIngredientSlot.CreateSlotInstance, CreatePocketItemSlotList.CreateSlotInstance, CreateProvideFoodUseIngredientSlotList.CreateSlotInstance, CreateRecipeSlotList.CreateSlotInstance.
List<ItemSlotData> BaseCreateSlotList.m_slotList
Referenced by CreateRecipeSlotList.CheckCreate, CreateActionItemSlotList.CreateSlotInstance, CreateCreateFoodNeedIngredientSlotList.CreateSlotInstance, CreateManagementProvideFoodControllerSlotList.CreateSlotInstance, CreateManagementProvideFoodSlotList.CreateSlotInstance, CreateNeedIngredientSlot.CreateSlotInstance, CreatePocketItemSlotList.CreateSlotInstance, CreateProvideFoodUseIngredientSlotList.CreateSlotInstance, CreateRecipeSlotList.CreateSlotInstance, DestroyItemSlotData, DestroySlotList, CreateManagementProvideFoodControllerSlotList.GetCreateList, CreateActionItemSlotList.GetItemSlotDataList, CreateManagementProvideFoodSlotList.GetProvideFoodList, RemoveItemSlotData, RemoveNullSlotList.
int BaseCreateSlotList.m_lineBreak
Referenced by AddSelectUIControler, SetLineBreak.
List<ItemSlotData> BaseCreateSlotList.SlotList
Referenced by ActionItemControllerWindow.DeleteSprite, ActionItemControllerWindow.SelectItemAction, ActionItemControllerWindow.SetItemInfomation.
virtual void BaseCreateSlotList.OnInitialize()
References CreateSlot, SetLineBreak.
Referenced by PutItemInstance.Craft, ChangeResultDescription.CreateProvideFoodSlot, ActionItemControllerWindow.OnInitialize, ActionItemWindow.OnInitialize, InventoryWindow.OnInitialize, NewItemWindow.OnInitialize, RecipeWindow.OnInitialize, SelectProvideFoodMenuUI.OnInitialize, SelectProvideFoodUI.OnInitialize.
virtual void BaseCreateSlotList.CreateSlot()
References CreateSlotInstance, RemoveNullSlotList.
Referenced by FoodSlotData.CreateNeedIngredient, ChangeFoodItemDescription.CreateNeedIngredientSlot, ChangeItemDescription.CreateNeedIngredientSlot, ChangeResultDescription.CreateProvideFoodUseIngredientSlot, SelectProvideFoodMenuUI.CreateSlot, OnInitialize, ManagementUI.OnStart, ActionItemControllerWindow.OnUpdate, SelectFoodDetailUI.SetCreateNeedIngredientSlot.
virtual void BaseCreateSlotList.DestroyItemSlotData(ItemSlotData _data)
References m_slotList.
virtual void BaseCreateSlotList.RemoveItemSlotData(ItemSlotData _data)
References m_slotList.
virtual void BaseCreateSlotList.RemoveNullSlotList()
References m_slotList.
Referenced by CreateSlot.
virtual void BaseCreateSlotList.SetLineBreak()
References m_createSlotType, m_lineBreak, m_selectUIController.
Referenced by OnInitialize.
virtual void BaseCreateSlotList.AddSelectUIControler(GameObject _addObject)
References SelectUIController.AddUI, m_createSlotType, m_lineBreak, m_selectUIController.
Referenced by CreateActionItemSlotList.CreateSlotInstance, CreateCreateFoodNeedIngredientSlotList.CreateSlotInstance, CreateManagementProvideFoodControllerSlotList.CreateSlotInstance, CreateManagementProvideFoodSlotList.CreateSlotInstance, CreateNeedIngredientSlot.CreateSlotInstance, CreatePocketItemSlotList.CreateSlotInstance, CreateProvideFoodUseIngredientSlotList.CreateSlotInstance, CreateRecipeSlotList.CreateSlotInstance.
void BaseCreateSlotList.DestroySlotList()
References m_slotList.
Referenced by CreateCreateFoodNeedIngredientSlotList.CreateSlotInstance, CreateNeedIngredientSlot.CreateSlotInstance.
virtual void BaseCreateSlotList.CreateSlotInstance()
Referenced by CreateSlot.