VisualFieldJudgment
bool VisualFieldJudgment.SearchTarget(GameObject _target, ChaseParameters _chaseParameters, Collider _myCollider, ref float _nearestDist)
References ChaseParameters.NoticeDist, ChaseParameters.SearchCharacterDist, ChaseParameters.ViewAngle.
Referenced by SearchEnemy.OnConditionCheck.
bool VisualFieldJudgment.ChaseTarget(GameObject _target, ChaseParameters _chaseParameters, Collider _myCollider)
References ChaseParameters.NoticeDist, ChaseParameters.ViewAngle.
Referenced by Arbor.BehaviourTree.Actions.AgentChaseToTransform.OnFixedUpdate.
bool VisualFieldJudgment.SearchTargetNearSpawn(GameObject _target, ChaseParameters _chaseParameters, Collider _myCollider, Vector3 _startPos, ref float _nearestDist, float _searchDist)
References ChaseParameters.DistAwayFromSpawnPos, ChaseParameters.NoticeDist, ChaseParameters.ViewAngle.
Referenced by BewareTarget.OnConditionCheck, EnemySearchTarget.OnConditionCheck.