JudgeWindow
SelectUIController JudgeWindow.m_selectUIController
Referenced by CheckPressSelectButton, OnSelfUpdate.
GameObject JudgeWindow.m_yesUI
Referenced by CheckPressSelectButton.
GameObject JudgeWindow.m_noUI
Referenced by CheckPressSelectButton.
bool JudgeWindow.m_judgeFlg
Referenced by CheckPressSelectButton, OnSelfUpdate, GameOverWindow.UpdateJudge, NoTimeWindow.UpdateJudge, ReturnHomeWindow.UpdateJudge.
override async UniTask JudgeWindow.OnUpdate()
References OnSelfUpdate.
async UniTask< bool > JudgeWindow.OnSelfUpdate()
References CheckPressSelectButton, m_judgeFlg, m_selectUIController, SelectUIController.OnLateUpdate, SelectUIController.OnUpdate, UpdateJudge.
Referenced by OnUpdate.
virtual async UniTask JudgeWindow.UpdateJudge()
Referenced by OnSelfUpdate.
bool JudgeWindow.CheckPressSelectButton()
References SelectUIController.CurrentSelectUI, SelectUIController.IsPress, m_judgeFlg, m_noUI, m_selectUIController, m_yesUI.
Referenced by OnSelfUpdate.