BaseGameStateUpdate
bool BaseGameStateUpdate.m_isEnd
Referenced by BaseLobbyStateUpdate.SetEnd, BaseManagementStateUpdate.SetEnd.
bool BaseGameStateUpdate.IsEnd
終了したか
Referenced by BaseGameStateUpdateController.UpdateState.
virtual int BaseGameStateUpdate.GetState()
virtual int BaseGameStateUpdate.GetNextState()
Referenced by BaseGameStateUpdateController.UpdateState.
virtual async UniTask BaseGameStateUpdate.OnInitialize()
初期処理
Referenced by BaseGameStateUpdateController.InitializeState.
virtual async UniTask BaseGameStateUpdate.OnUpdate()
実行処理
Referenced by BaseGameStateUpdateController.UpdateState.
virtual async UniTask BaseGameStateUpdate.OnExit()
終了処理
Referenced by BaseGameStateUpdateController.ExitState.
virtual async UniTask BaseGameStateUpdate.OnDestroy()
削除処理
Referenced by BaseGameStateUpdateController.DestroyState.