DetailUI
CanvasGroup DetailUI.m_canvasGroup
Referenced by SetDisplay.
bool DetailUI.m_isDisplay
Referenced by CheckDisplay, OnInitialize, SetDisplay.
virtual async UniTask DetailUI.OnInitialize()
初期化処理
References m_isDisplay, SetDisplay.
virtual async UniTask DetailUI.OnUpdate()
実行処理
References CheckDisplay.
void DetailUI.CheckDisplay()
References BaseManager< T >.instance, m_isDisplay, SetDisplay.
Referenced by OnUpdate.
void DetailUI.SetDisplay(bool _isDeisplay)
References m_canvasGroup, m_isDisplay.
Referenced by CheckDisplay, OnInitialize.