InventoryManager
InventoryManager InventoryManager.instance
Referenced by Awake, PutItemInstance.Craft, GetItemObject.DebugGet, ActionItemControllerWindow.DeleteSprite, EatItem.Eat, GetItemObject.Get, GetItemObject.GetItem, CreateActionItemSlotList.GetItemSlotDataList, PocketItemDataInfo.PocketItemDataInfoExtensions.GetPocketItemDataManager, GetItemObject.OnTriggerEnter, ThrowItemInstance.Throw, LobbyStateUpdate_ReturnAction.Transfer, UseItemInstance.UseItem.
virtual void InventoryManager.Awake()
References instance.
override bool InventoryManager.AddItem(ItemTypeID _itemTypeID, uint _itemID)
アイテムリストに引数アイテムを追加する
_itemTypeID 追加したいアイテムの種類 _itemID 追加したいアイテムのID /// true - 追加できた false - 追加できなかった
References BasePocketItemDataController.AddItem, NewItemManager.instance.
Referenced by GetItemObject.DebugGet, GetItemObject.Get, GetItemObject.GetItem.
override bool InventoryManager.RemoveItem(ItemTypeID _itemTypeID, uint _itemID, int _removeNum=1)
アイテムリストに存在する引数アイテムを減算/削除する
_itemTypeID 減算/削除したいアイテムの種類 _itemID 減算/削除したいアイテムのID _removeNum 減算数 /// true - 減算/削除できた false - 減算/削除できなかった
References NewItemManager.instance, BasePocketItemDataController.RemoveItem.
Referenced by PutItemInstance.Craft, EatItem.Eat, ThrowItemInstance.Throw, UseItemInstance.UseItem.