Arbor::BehaviourTree::Actions::AgentChaseToTransform
FlexibleTransform Arbor.BehaviourTree.Actions.AgentChaseToTransform.m_targetTransform
Referenced by Arbor.BehaviourTree.Actions.AgentChaseToTransform.LostSightTarget, Arbor.BehaviourTree.Actions.AgentChaseToTransform.OnFixedUpdate, Arbor.BehaviourTree.Actions.AgentChaseToTransform.WatchTarget.
FlexibleFloat Arbor.BehaviourTree.Actions.AgentChaseToTransform.m_stoppingDistance
Referenced by Arbor.BehaviourTree.Actions.AgentChaseToTransform.OnIntervalUpdate.
FlexibleChaseParameters Arbor.BehaviourTree.Actions.AgentChaseToTransform.m_chaseParameters
Referenced by Arbor.BehaviourTree.Actions.AgentChaseToTransform.OnFixedUpdate, Arbor.BehaviourTree.Actions.AgentChaseToTransform.WatchTarget.
FlexibleFloat Arbor.BehaviourTree.Actions.AgentChaseToTransform.m_maxSearchInterval
Referenced by Arbor.BehaviourTree.Actions.AgentChaseToTransform.OnFixedUpdate, Arbor.BehaviourTree.Actions.AgentChaseToTransform.OnStart.
OutputSlotBool Arbor.BehaviourTree.Actions.AgentChaseToTransform.m_outIsWatch
Referenced by Arbor.BehaviourTree.Actions.AgentChaseToTransform.OnIntervalUpdate.
Collider Arbor.BehaviourTree.Actions.AgentChaseToTransform.m_myCollider
Referenced by Arbor.BehaviourTree.Actions.AgentChaseToTransform.OnAwake, Arbor.BehaviourTree.Actions.AgentChaseToTransform.OnFixedUpdate.
Vector3 Arbor.BehaviourTree.Actions.AgentChaseToTransform.m_targetPos
Referenced by Arbor.BehaviourTree.Actions.AgentChaseToTransform.LostSightTarget, Arbor.BehaviourTree.Actions.AgentChaseToTransform.OnIntervalUpdate, Arbor.BehaviourTree.Actions.AgentChaseToTransform.WatchTarget.
float Arbor.BehaviourTree.Actions.AgentChaseToTransform.m_chaseTime
Referenced by Arbor.BehaviourTree.Actions.AgentChaseToTransform.LostSightTarget, Arbor.BehaviourTree.Actions.AgentChaseToTransform.OnFixedUpdate, Arbor.BehaviourTree.Actions.AgentChaseToTransform.WatchTarget.
bool Arbor.BehaviourTree.Actions.AgentChaseToTransform.m_isWatch
Referenced by Arbor.BehaviourTree.Actions.AgentChaseToTransform.LostSightTarget, Arbor.BehaviourTree.Actions.AgentChaseToTransform.OnIntervalUpdate, Arbor.BehaviourTree.Actions.AgentChaseToTransform.WatchTarget.
float Arbor.BehaviourTree.Actions.AgentChaseToTransform.m_searchInterval
Referenced by Arbor.BehaviourTree.Actions.AgentChaseToTransform.OnFixedUpdate, Arbor.BehaviourTree.Actions.AgentChaseToTransform.OnStart.
readonly VisualFieldJudgment Arbor.BehaviourTree.Actions.AgentChaseToTransform.m_judgement
Referenced by Arbor.BehaviourTree.Actions.AgentChaseToTransform.OnFixedUpdate.
override void Arbor.BehaviourTree.Actions.AgentChaseToTransform.OnAwake()
References Arbor.BehaviourTree.Actions.AgentChaseToTransform.m_myCollider.
override void Arbor.BehaviourTree.Actions.AgentChaseToTransform.OnStart()
References Arbor.BehaviourTree.Actions.AgentChaseToTransform.m_maxSearchInterval, Arbor.BehaviourTree.Actions.AgentChaseToTransform.m_searchInterval, Arbor.BehaviourTree.Actions.AgentChaseToTransform.WatchTarget.
override void Arbor.BehaviourTree.Actions.AgentChaseToTransform.OnFixedUpdate()
References VisualFieldJudgment.ChaseTarget, Arbor.BehaviourTree.Actions.AgentChaseToTransform.LostSightTarget, Arbor.BehaviourTree.Actions.AgentChaseToTransform.m_chaseParameters, Arbor.BehaviourTree.Actions.AgentChaseToTransform.m_chaseTime, Arbor.BehaviourTree.Actions.AgentChaseToTransform.m_judgement, Arbor.BehaviourTree.Actions.AgentChaseToTransform.m_maxSearchInterval, Arbor.BehaviourTree.Actions.AgentChaseToTransform.m_myCollider, Arbor.BehaviourTree.Actions.AgentChaseToTransform.m_searchInterval, Arbor.BehaviourTree.Actions.AgentChaseToTransform.m_targetTransform, Arbor.BehaviourTree.Actions.AgentChaseToTransform.WatchTarget.
override bool Arbor.BehaviourTree.Actions.AgentChaseToTransform.OnIntervalUpdate(AgentController agentController)
References Arbor.BehaviourTree.Actions.AgentChaseToTransform.m_isWatch, Arbor.BehaviourTree.Actions.AgentChaseToTransform.m_outIsWatch, Arbor.BehaviourTree.Actions.AgentChaseToTransform.m_stoppingDistance, Arbor.BehaviourTree.Actions.AgentChaseToTransform.m_targetPos.
void Arbor.BehaviourTree.Actions.AgentChaseToTransform.WatchTarget()
References Arbor.BehaviourTree.Actions.AgentChaseToTransform.m_chaseParameters, Arbor.BehaviourTree.Actions.AgentChaseToTransform.m_chaseTime, Arbor.BehaviourTree.Actions.AgentChaseToTransform.m_isWatch, Arbor.BehaviourTree.Actions.AgentChaseToTransform.m_targetPos, Arbor.BehaviourTree.Actions.AgentChaseToTransform.m_targetTransform.
Referenced by Arbor.BehaviourTree.Actions.AgentChaseToTransform.OnFixedUpdate, Arbor.BehaviourTree.Actions.AgentChaseToTransform.OnStart.
void Arbor.BehaviourTree.Actions.AgentChaseToTransform.LostSightTarget()
References Arbor.BehaviourTree.Actions.AgentChaseToTransform.m_chaseTime, Arbor.BehaviourTree.Actions.AgentChaseToTransform.m_isWatch, Arbor.BehaviourTree.Actions.AgentChaseToTransform.m_targetPos, Arbor.BehaviourTree.Actions.AgentChaseToTransform.m_targetTransform.
Referenced by Arbor.BehaviourTree.Actions.AgentChaseToTransform.OnFixedUpdate.