SceneTransitionManager
string SceneTransitionManager.m_sceneName
Referenced by SceneChange.
UniTask SceneTransitionManager.Method()
References SceneChange.
async UniTask SceneTransitionManager.SceneChange()
References m_sceneName, SceneChange.
Referenced by Method, TitleScreenManager.OnLoadGame, TitleScreenManager.OnNewGame, SceneChange, SelectStageWindow.Transion, ManagementResultWindow.Transition, ManagementSelectProvideFoodWindow.Transition, AnyKeyPushInSceneChange.Update, BattlePartSceneChange.Update, CountDownTimer.Update, TrialSessionWindow.UpdateConfirmation, NoTimeWindow.UpdateJudge, ReturnHomeWindow.UpdateJudge.
async UniTask SceneTransitionManager.SceneChange(string sceneName)
References BaseManager< T >.instance.