BaseManagementEvent
ManagementEventID BaseManagementEvent.m_eventID
bool BaseManagementEvent.m_isEventEnd
動作が終了したかどうか
Referenced by OnUpdate, SetEventEnd.
ManagementEventID BaseManagementEvent.EventID
Referenced by ManagementEventUI.SetUI.
bool BaseManagementEvent.IsEventEnd
動作終了かどうかの参照用
virtual void BaseManagementEvent.OnStart()
イベントの開始 継承先でオーバーライドする
イベント開始処理
Referenced by ManagementEventManager.AddEventList.
virtual void BaseManagementEvent.OnUpdate()
イベント実行処理
References m_isEventEnd.
virtual void BaseManagementEvent.OnExit()
イベント終了処理
void BaseManagementEvent.SetEventEnd(EventSolutionType _type)
イベント終了処理 イベントの解決での終了か失敗での終了か指定できる
_type
References BaseManager< T >.instance, m_isEventEnd.
Referenced by GenerateCleaningEvent.CheckDirt, GenerateCleaningEvent.CountEndTime, AppearGangsterEvent.OnUpdate, DineDashEvent.OnUpdate, GenerateEmptyDishEvent.OnUpdate.