CreateConditionImage
Vector2 CreateConditionImage.m_imageSize
Referenced by SetRectTransform.
Color CreateConditionImage.m_maxColor
Referenced by SetImage.
Color CreateConditionImage.m_minColor
Referenced by SetImage.
List<GameObject> CreateConditionImage.m_imageList
Referenced by CreateImage, DestroyConditionImage.
ConditionID CreateConditionImage.m_conditionID
Referenced by CreateImage, SetImage.
uint CreateConditionImage.m_level
Referenced by CreateImage, SetImage.
bool CreateConditionImage.CreateImage(BaseItemData _itemData)
References BaseEdibleItem.ConditionID, DestroyConditionImage, m_conditionID, m_imageList, m_level, SetImage, SetRectTransform.
Referenced by ChangeItemDescription.CreateConditionImage.
void CreateConditionImage.SetImage(GameObject _obj, int _current)
References BaseManager< T >.instance, m_conditionID, m_level, m_maxColor, m_minColor.
Referenced by CreateImage.
void CreateConditionImage.SetRectTransform(GameObject _obj)
References m_imageSize.
Referenced by CreateImage.
void CreateConditionImage.DestroyConditionImage()
References m_imageList.
Referenced by CreateImage.