ChangeResultDescription
TextMeshProUGUI ChangeResultDescription.m_soldNumText
Referenced by SetSoldNumText.
TextMeshProUGUI ChangeResultDescription.m_earnedMoneyText
Referenced by SetEarnedMoneyText.
TextMeshProUGUI ChangeResultDescription.m_totalEarnedMoneyText
Referenced by SetTotalEarnedMoneyText.
CreateManagementProvideFoodSlotList ChangeResultDescription.m_createProvideFoodSlotList
Referenced by CreateProvideFoodSlot.
CreateProvideFoodUseIngredientSlotList ChangeResultDescription.m_createProvideFoodUseIngredientSlotList
Referenced by CreateProvideFoodUseIngredientSlot.
TextMeshProUGUI ChangeResultDescription.m_cameCustomerNumText
Referenced by SetCameCustomerNumText.
TextMeshProUGUI ChangeResultDescription.m_cameNormalCustomerNumText
Referenced by SetCameAngryCustomerNumText, SetCameNormalCustomerNumText.
TextMeshProUGUI ChangeResultDescription.m_cameAngryCustomerNumText
Referenced by SetCameAngryCustomerNumText.
TextMeshProUGUI ChangeResultDescription.m_eventSolutionNumText
Referenced by SetEventSolutionNumText.
TextMeshProUGUI ChangeResultDescription.m_eventUnSolutionNumText
Referenced by SetEventUnSolutionNumText.
virtual void ChangeResultDescription.OnInitialize()
References SetDescription.
Referenced by ManagementResultWindow.OnInitialize.
void ChangeResultDescription.SetDescription()
References CreateProvideFoodSlot, CreateProvideFoodUseIngredientSlot, SetCameAngryCustomerNumText, SetCameCustomerNumText, SetCameNormalCustomerNumText, SetEarnedMoneyText, SetEventSolutionNumText, SetEventUnSolutionNumText, SetSoldNumText, SetTotalEarnedMoneyText.
Referenced by OnInitialize.
void ChangeResultDescription.SetSoldNumText()
References BaseManager< T >.instance, m_soldNumText.
Referenced by SetDescription.
void ChangeResultDescription.CreateProvideFoodSlot()
References m_createProvideFoodSlotList, BaseCreateSlotList.OnInitialize.
Referenced by SetDescription.
void ChangeResultDescription.CreateProvideFoodUseIngredientSlot()
References BaseCreateSlotList.CreateSlot, m_createProvideFoodUseIngredientSlotList.
Referenced by SetDescription.
void ChangeResultDescription.SetEarnedMoneyText()
References BaseManager< T >.instance, m_earnedMoneyText.
Referenced by SetDescription.
void ChangeResultDescription.SetTotalEarnedMoneyText()
References BaseManager< T >.instance, m_totalEarnedMoneyText.
Referenced by SetDescription.
void ChangeResultDescription.SetCameCustomerNumText()
References BaseManager< T >.instance, m_cameCustomerNumText.
Referenced by SetDescription.
void ChangeResultDescription.SetCameNormalCustomerNumText()
References BaseManager< T >.instance, m_cameNormalCustomerNumText.
Referenced by SetDescription.
void ChangeResultDescription.SetCameAngryCustomerNumText()
References BaseManager< T >.instance, m_cameAngryCustomerNumText, m_cameNormalCustomerNumText.
Referenced by SetDescription.
void ChangeResultDescription.SetEventSolutionNumText()
References BaseManager< T >.instance, m_eventSolutionNumText.
Referenced by SetDescription.
void ChangeResultDescription.SetEventUnSolutionNumText()
References BaseManager< T >.instance, m_eventUnSolutionNumText.
Referenced by SetDescription.