AppearanceItemOutline
Material AppearanceItemOutline.m_addMat
Referenced by AddMaterial, OnDestroy, OnHide, OnShow.
void AppearanceItemOutline.Start()
References OnMaterialLoaded.
void AppearanceItemOutline.AddMaterial(Material _originalMat)
References m_addMat.
Referenced by OnMaterialLoaded.
void AppearanceItemOutline.OnMaterialLoaded(AsyncOperationHandle< Material > handle)
References AddMaterial.
Referenced by Start.
void AppearanceItemOutline.OnShow(float _duration)
References m_addMat.
Referenced by GetItemObject.SwitchOutline.
void AppearanceItemOutline.OnHide(float _duration)
References m_addMat.
Referenced by GetItemObject.SwitchOutline.
void AppearanceItemOutline.OnDestroy()
References m_addMat.