CurrentAnimatorCheckerState
FlexibleComponent CurrentAnimatorCheckerState.m_animator
アニメーターをエディタからセットする
Referenced by SetAnimator.
Animator CurrentAnimatorCheckerState.m_currentAnimator
Referenced by Check, SetAnimator.
string CurrentAnimatorCheckerState.m_animationName
識別するアニメーションの名前
Referenced by Check.
StateLink CurrentAnimatorCheckerState.m_successLink
遷移先のリンク
Referenced by SetTransition.
void CurrentAnimatorCheckerState.SetAnimator()
アニメーターのセット 初期化
References m_animator, m_currentAnimator.
Referenced by OnStateBegin.
void CurrentAnimatorCheckerState.Check()
アニメーションが指定のものであれば遷移する
References m_animationName, m_currentAnimator, SetTransition.
Referenced by OnStateUpdate.
void CurrentAnimatorCheckerState.SetTransition()
遷移先のセット
References m_successLink.
Referenced by Check.
override void CurrentAnimatorCheckerState.OnStateBegin()
References SetAnimator.
override void CurrentAnimatorCheckerState.OnStateUpdate()
References Check.