IsDeadGangster
CharacterCore IsDeadGangster.m_characterCore
Referenced by IsHPDead, SetCharacterCore.
StateLink IsDeadGangster.m_deadLink
Referenced by DeadCheck, SetCharacterCore.
void IsDeadGangster.SetCharacterCore()
References BaseGangsterStateBehaviour.GetGangsterData, m_characterCore, m_deadLink, BaseGangsterStateBehaviour.SetTransition.
Referenced by OnStateBegin.
void IsDeadGangster.DeadCheck()
死亡状態か確認 Updateで回す
References IsHPDead, IsStateDead, m_deadLink, BaseGangsterStateBehaviour.SetTransition.
Referenced by OnStateUpdate.
bool IsDeadGangster.IsStateDead()
ステート(GangsterState)が死亡状態か確認
References BaseGangsterStateBehaviour.GetGangsterData.
Referenced by DeadCheck.
bool IsDeadGangster.IsHPDead()
HPが0以下か確認
References m_characterCore, CharacterCore.CharatcerStatus.m_hp, CharacterCore.Status.
Referenced by DeadCheck.
override void IsDeadGangster.OnStateBegin()
References SetCharacterCore.
override void IsDeadGangster.OnStateUpdate()
References DeadCheck.