BaseChangeText
TextMeshProUGUI BaseChangeText.m_text
Referenced by SetEarnedMoneyText.ChangeText, SetTotalEarnedMoneyText.ChangeText.
List<BaseEffectText> BaseChangeText.m_effectList
Referenced by PlayEffect.
List<BaseDoTweenUI> BaseChangeText.m_baseDoTweenUIList
Referenced by PlayDoTween.
void BaseChangeText.Update()
References ChangeText.
virtual void BaseChangeText.ChangeText()
Referenced by Update.
virtual void BaseChangeText.PlayEffect()
References m_effectList.
Referenced by SetEarnedMoneyText.ChangeText, SetTotalEarnedMoneyText.ChangeText.
virtual void BaseChangeText.PlayDoTween()
References m_baseDoTweenUIList.
Referenced by SetEarnedMoneyText.ChangeText, SetTotalEarnedMoneyText.ChangeText.