OrderFoodData
string OrderFoodData.m_seName
Referenced by FindCounterPointData.
GameObject OrderFoodData.m_effectPrefab
Referenced by FindCounterPointData.
OrderFoodState OrderFoodData.m_currentOrderFoodState
Referenced by IsCounterFood, IsFindStaff.
FoodID OrderFoodData.m_foodID
TableSetData OrderFoodData.m_targetTabelSetData
CounterPointData OrderFoodData.m_counterPointData
Referenced by FindCounterPointData.
bool OrderFoodData.m_isCreate
Referenced by CreatCount, FindCounterPointData.
float OrderFoodData.m_createDelay
Referenced by CreatCount.
float OrderFoodData.m_currentCreateDelayCount
Referenced by CreatCount.
OrderFoodState OrderFoodData.CurrentOrderFoodState
FoodID OrderFoodData.FoodID
Referenced by CustomerCanvas.SetFoodImage.
TableSetData OrderFoodData.TargetTableSetData
CounterPointData OrderFoodData.CounterPointData
bool OrderFoodData.IsCreate
void OrderFoodData.OnUpdate()
References CreatCount, FindCounterPointData.
bool OrderFoodData.IsFindStaff()
客を探している状態か
References m_currentOrderFoodState.
bool OrderFoodData.IsCounterFood()
カウンターに設置されている料理かどうか
References m_currentOrderFoodState.
Referenced by CounterPointData.CheckOrderFoodData, CreatCount, FindCounterPointData.
void OrderFoodData.CreatCount()
作成時間をカウントする
References IsCounterFood, m_createDelay, m_currentCreateDelayCount, m_isCreate.
Referenced by OnUpdate.
void OrderFoodData.FindCounterPointData()
References SoundManager.Instance, BaseManager< T >.instance, IsCounterFood, m_counterPointData, m_effectPrefab, m_isCreate, m_seName, CounterPointData.SetPoint, SoundManager.StartPlayback.
Referenced by OnUpdate.