ICondition
ConditionInfo.ConditionID ICondition.ConditionID
Referenced by ConditionManager.AddCondition, ConditionManager.IsCondition.
GameObject ICondition.Owner
Referenced by ConditionManager.Update.
bool ICondition.IsEffective()
Referenced by ConditionManager.DamageMulti, ConditionManager.Update.
float ICondition.DamageMulti(ConditionInfo.ResistanceID[] resistances)
Referenced by ConditionManager.DamageMulti.
void ICondition.ReplaceCondition(ICondition newCondition, ConditionInfo.ResistanceID[] resistances)
Referenced by ConditionManager.AddCondition.